### ISSUE TITLE
Is this an alternative to sw-precache? (newb question)

### ISSUE THREAD

**Issue by jasan-s** [NekR/offline-plugin#101]

**Comment by NekR** [comment]
Probably. If you are using `sw-precache` already then you don't need to switch. 

The idea of this plugin is that it's integrated to `webpack`, it's easy to setup and it supports AppCache if it's needed. Also it's probably written differently than `sw-precache` and may not have all features `sw-precache` has.

**Comment by NekR** [comment]
Okay, closing this. Feel free to ask other questions :-)
