### ISSUE TITLE
Add load modifiers

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#107]
For example, adding Google Fonts `.css` file to the cache doesn't pre-cache fonts listed in that CSS. It could be fixed with load modifiers:

``` js
new OfflinePlugin({
  externals: [
    'fonts-css:https://fonts.googleapis.com/css?family=Roboto'
  ]
})
```

**Comment by KyleAMathews** [comment]
Can you use globs or regex e.g. `https://fonts.google*`?

**Comment by NekR** [comment]
@KyleAMathews for precaching? No. I need to know that ahead of time, i.e. on install event. For dynamic caches, yeah, it should use some pattern/regexp, but there is a separate issue for that.

**Comment by NekR** [comment]
Too complicated for the moment.
