### ISSUE TITLE
files loaded from css not included

### ISSUE THREAD

**Issue by KyleAMathews** [NekR/offline-plugin#110]
I have a font-faces css file that includes some custom fonts. The font files are pulled into my output folder by Webpack but aren't being included in the service worker. Is this a deliberate decision or just something not gotten to yet?

**Comment by NekR** [comment]
Hmm.. Everything generated by webpack should be included. Do you use file-loader or some plugin to transfer files? If plugin, are you sure what offline-plugin is the last in webpack's plugins array?

**Comment by KyleAMathews** [comment]
Oooo, I figured it out. I'm using offline-plugin in Gatsby which has separate build steps for css and js so I had been just using the null-loader for css while building js which meant the css loaded files we're handled then. I switched to extracting the css (and just tossing it — not too expensive as it turns out) and now the font files are being added correctly.

**Comment by NekR** [comment]
Great and thanks for the info! 👍
