### ISSUE TITLE
Add example apps section to README.md

### ISSUE THREAD

**Issue by sarmadsangi** [NekR/offline-plugin#114]
Hi,

Just wondering if this will be useful for anyone getting started with this `offline-plugin` to see it in action in another project, I am pretty sure there are many projects out there.

Here is one i did,
https://github.com/sarmadsangi/offline-kanban

Let me know your thoughts and i can send a PR by adding this section to README if this is useful.

**Comment by NekR** [comment]
Hey @sarmadsangi! Great idea. I actually saw your project and thought to contribute to it to make it a PWA 👍 

Any PR is welcome here too. But if you are going to send a PR, please do it against `v4` branch.

**Comment by NekR** [comment]
Btw, not sure how many real projects you it, but I know couple of Open Source project which do:

* [react-boilerplate](https://github.com/mxstbr/react-boilerplate)
* [angular-cli](https://github.com/angular/angular-cli)
* [phemonic](https://github.com/MoOx/phenomic)

**Comment by sarmadsangi** [comment]
@NekR Thanks for letting me send a PR. Please feel free to contribute to `offline-kanban` project in anyway you want, glad to know that someone is interested in it :)

Here is PR for above issue, feel free to comment and i ll ammend,
https://github.com/NekR/offline-plugin/pull/115

**Comment by NekR** [comment]
Yeah, I'll help you make `offline-kanban` a PWA when I'll release `v4` of `offline-plugin`.

**Comment by GGAlanSmithee** [comment]
> I'll help you make offline-kanban a PWA

Sorry for crashing your issue, just wanted to say that it will be interesting to see. :)

**Comment by NekR** [comment]
@GGAlanSmithee no problem :) Just out of curiosity: Why interesting? Do you use `offline-kanban`?

**Comment by GGAlanSmithee** [comment]
@NekR I am testning it in a hobby project atm, really liking it! If all goes well we might use it at work too.

**Comment by NekR** [comment]
@GGAlanSmithee  ah, I see. I think you just misread my comment. @sarmadsangi has his own project called offline-**kanban**, that is a web app. That web app is using my `offline-plugin`.

And yeah, I won't be converting `offline-plugin` into PWA, I just will help @sarmadsangi to have a PWA in his project. That actually isn't related to my plugin, I just like that web app and want to help with it.

>  really liking it!

This is great to hear :-) If something, here is a PR where I track progress of `v4` of `offline-plugin`: https://github.com/NekR/offline-plugin/pull/109

**Comment by GGAlanSmithee** [comment]
Ah, I half misunderstood u.

I know you were talking about making `offline-canban` a PWA, and I am interested in that process :)

I misunderstood your question though; no, I am not using `offline-canban`.

**Comment by NekR** [comment]
@GGAlanSmithee I see, thanks for you interest :-)

@sarmadsangi I'm closing this then, right? Thanks for contributing!
