### ISSUE TITLE
Several web apps with offline plugin on the same domain

### ISSUE THREAD

**Issue by VincentFTS** [NekR/offline-plugin#116]
Hi,

when deploying two (or more !) web apps on the same domain, the installation of the last one deletes the cache of the previously installed web app.

I don't see anything in the configuration that could make a work around. Am I wrong ?

It is a really bing constraint to limit the number of installable web apps on a unique domain.

I'm quiet under pressure on this as I should have already delivered these two applications to my client ...

Let me know if I can help.

**Comment by NekR** [comment]
Hi @VincentFTS,

Yes, I hear. That's indeed unfortunate to not be able to run multiple apps on the same domain. I'll add that now, but only to `v4` branch (which isn't released yet). There is nothing wrong `v4`, but it's kind of in beta, so potentially, there could be some issues.

**Comment by NekR** [comment]
Okay, I just added it to `v4`. You can use it this way:

```js
new OfflinePlugin({
  ServiceWorker: {
    cacheName: 'my-project'
  }
})
```

Here are more details on how to install `v4`: https://github.com/NekR/offline-plugin/pull/109

Thanks for reproting this!

**Comment by VincentFTS** [comment]
Thanks for your very quick replies !

Seems to be quiet a simple patch. Why not applying it to v3 ? It's seems to carry no risk of regression.

If you decide to not do it, it would be interesting to add an explanation about the 'only one app per domain' limitation in the README.

**Comment by NekR** [comment]
@VincentFTS I don't want to do it because `v4` should be released shortly and even now everyone should start using `v4`. `v3` is mostly dead. Not that `v4` is a bad release. It's just that there is a lot of time invested in `v4` and that is the way to go.

What is the problem of using `v4`?

**Comment by VincentFTS** [comment]
You said it is a beta, and I need to go in production. When do you plan to release v4 ?

Envoyé de mon iPad

**Comment by NekR** [comment]
That's right, it's in beta. Though, many people are using beta project: a lot of people using beta TypeScript, gulp, html-webpack-plugin (at a time). Facebook for examples uses React on production directly from master branch, i.e. with all latest changes.

I'm trying to release `v4` in this month. Though, that may not happen by any reason. If you don't want to use `v4`, I suggest you to just fork current version (`v3` in master) and just add that small patch in your fork, and then just use that fork until `v4` of `offline-plugin` is released.

**Comment by VincentFTS** [comment]
OK, I switched to v4.3.0, and I added the cacheName key to my config, but it doesn't seem to be taken into account in the cache name I see in chrome dev tools.
Here is my config :
`            new OfflinePlugin({
                ServiceWorker: {
                    events: true
                },
                updateStrategy: 'changed',
                cacheName: 'allo'
            })`

**Comment by NekR** [comment]
It's 

```js
new OfflinePlugin({
  ServiceWorker: {
    cacheName: 'my-project'
  }
})
```

not 

```js
new OfflinePlugin({
  cacheName: 'my-project'
})
```

as you did.

**Comment by VincentFTS** [comment]
Let's say my glasses were too dirty !!
Thanks !
