### ISSUE TITLE
NODE_ENV production disables service worker?

### ISSUE THREAD

**Issue by justinmc** [NekR/offline-plugin#118]
When I run the app in development, with NODE_ENV set to "development" or not set at all, this plugin works fine and uses a service worker as expected.  However, when I set NODE_ENV to "production", it uses the application cache instead of service worker.  If I disable application cache in the options, then neither are used.

Any idea why this would happen?  I tried searching this repository for anywhere it was using NODE_ENV and couldn't find anything.

**Comment by NekR** [comment]
Hi @justinmc, let's solve this. `offline-plugin` doesn't use `NODE_ENV` by any means so it ins't the problem.

As I understand, you run production builds on a production, not locally as with dev builds. Does your website has https? HTTPS is required for a ServiceWorker.

**Comment by justinmc** [comment]
Ah that's it, I'm not yet using https for this app.  I was just reading about service workers and https too...  I'll come back and verify this once I've got https working, but I think it's safe to close.  Thanks again for the help!
