### ISSUE TITLE
Need an absolute path for sw.js

### ISSUE THREAD

**Issue by justinmc** [NekR/offline-plugin#119]
Can I get the plugin to always look for sw.js at the root path localhost/sw.js?

Using the default webpack dev server setup and frontend routing, if I navigate to localhost/imaroute in my browser, then this plugin will look for sw.js at localhost/imaroute/sw.js.  However, it needs to always be looking at localhost/sw.js in this case.  How can I achieve that?

Messing with the ServiceWorker `publicPath` and `output` options seems to not be able to do this.

**Comment by NekR** [comment]
Yeah, you cannot do this right now in `v3`. I added it into `v4` and it's called `ServiceWorker.publicLocation` and `AppCache.publicLocation`, but probably will be renamed to `ServiceWorker.publicPath`/`AppCache.publicPath`. 

Here are instructions on how to get started with `v4`: https://github.com/NekR/offline-plugin/pull/109

**Comment by NekR** [comment]
Even this issue closed, any feedback is welcome. It's closed because problem with changing path is already solved.

**Comment by justinmc** [comment]
Thanks for the help!  Installing v4 and using `publicLocation: '/'` solved it for me.

**Comment by NekR** [comment]
@justinmc great! You probably may need to duplicated it with `publicPath` so it won't break your app when I update the names (since it's still in beta I won't bump major version for that change). 

Also, did you really set it to `publicLocation: '/'`? I mean, it supposed to be `publicLocation: '/sw.js'` for Service Worker. Weird what that works for you..

**Comment by justinmc** [comment]
You're right, not sure why I was seeing it working...  Restarting the server and trying again it worked using:

        publicLocation: '/sw.js',
        publicPath: '/',

**Comment by NekR** [comment]
I mean that it should be this for now:
```js
    publicLocation: '/sw.js',
    publicPath: '/sw.js',
```
Since it's the same prop and I'm just going to rename it.

**Comment by harshmaur** [comment]
Hello, 

I was having the same issue, different routes if loaded are not able to find sw.js. 

Do I still need to add publicLocation?

**Comment by NekR** [comment]
@harshmaur I think adding `publicPath` either to [webpack's configuration](https://webpack.github.io/docs/configuration.html#output-publicpath) or to [`offline-plugin`'s configuration](https://github.com/NekR/offline-plugin#publicpath-string) should be enough.

**Comment by harshmaur** [comment]
@NekR My webpack config already had publicPath set to '/' however offline-plugin was always taking incorrect path based on the route. 

So I added publicPath to `offline-plugin` as well and it seems to work fine now! 

Thanks!

**Comment by NekR** [comment]
@harshmaur hmm.. weird, `offline-plugin` had to take `publicPath` from your webpack's config. What are you using `v4` of `offline-plugin`? Also maybe you had `relativePaths` option set to `true`?

**Comment by harshmaur** [comment]
Yes I am using v4 and I dont have relativePaths set to true.

**Comment by NekR** [comment]
@harshmaur okay, that's just weird then. It would be good if you could share your webpack configuration so I could debug it and check what went wrong (you can send it to my email if you don't want to share it here).
