### ISSUE TITLE
Provide options to fetch calls in sw.js

### ISSUE THREAD

**Issue by TimGeisler** [NekR/offline-plugin#121]
Hi,
I managed to set up offline-plugin using service workers successfully.

However, when I add htaccess/htpasswd authentication to the web site hosting the webpack bundle, then I get an error message "wrong response status":

```
sw.js:115 [SW]: Install event
www.example.com/:1 GET https://www.example.com/demo/offline/?__uncache=9351723014dcb8a99531 401 (Unauthorized)
bundle.js:1 GET https://www.example.com/demo/offline/bundle.js?__uncache=9351723014dcb8a99531 401 (Unauthorized)
sw.js:179 Error: Wrong response status(…)(anonymous function) @ sw.js:179
sw.js:503 Uncaught (in promise) Error: Wrong response status(…)(anonymous function) @ sw.js:503
```

The relevant snippet of sw.js is the following:

```
function addAllNormalized(cache, requests, options) {
	  var bustValue = options && options.bust;

	  return Promise.all(requests.map(function (request) {
	    if (bustValue) {
	      request = applyCacheBust(request, bustValue);
	    }

	    return fetch(request);
	  })).then(function (responses) {
	    if (responses.some(function (response) {
	      return !response.ok;
	    })) {
	      return Promise.reject(new Error('Wrong response status'));
	    }

	    var addAll = responses.map(function (response, i) {
	      return cache.put(requests[i], response);
	    });

	    return Promise.all(addAll);
	  });
	}
```

In my case it helps to add the following option to all calls of fetch in the generated sw.js file:

```
fetch(url, {
  credentials: 'same-origin'
})
```

Then offline using service workers also works with htaccess/htpasswd authentication in my case.

It would be good to extend the API to be able to provide options to fetch calls.

**Comment by NekR** [comment]
Hi @TimGeisler, this indeed sounds like a good to have. But just to clarify, why do you hide static project assets under an authentication?

**Comment by TimGeisler** [comment]
The static project assets contain sensitive data (e.g. product information, prices).

**Comment by NekR** [comment]
I see. Btw, you don't need to set `credentials` on every `fetch()` in SW as you did now. Only for those which is used with synthetic requests, i.e. which isn't coming from your pages. So if there is `fetch(event.request)` then there no need to override credentials since page sends them by default.

**Comment by NekR** [comment]
Fixed in `v4`.

**Comment by TimGeisler** [comment]
Thanks a lot for fixing this issue so fast!

**Comment by NekR** [comment]
Sure, thanks for reporting this!

**Comment by jonniespratley** [comment]
Any way to support `{credentials: 'same-origin'}` in the sw.js generated fetch?

**Comment by NekR** [comment]
Which `sw.js` generated fetch? The ones generated for pre-fetch already use it and other which come from the pages reuse page request's settings.
