### ISSUE TITLE
Make prefetchRequest.credentials default to 'same-origin'

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#123]

**Comment by TimGeisler** [comment]
Perhaps the following problem has to do with the fact that prefetchRequest.credentials does not default to 'same-origin' at the moment.

I configured OfflinePlugin as follows:
```
    new OfflinePlugin({
      version: '[hash]',
      ServiceWorker: {
        events: true,
        prefetchRequest: { credentials: 'same-origin' },
      },
    }),
```

With the current 4.4.0 release I get errors like
`Failed to load resource: the server responded with a status of 401 (Unauthorized)
https://www.example.com/?__uncache=5b8989fde76d911a6e7e`

The authorization for the web site is handled via .htaccess/.htpasswd.

Commit e7275acc1d403b4fbfcd4284e7c19592ba6be435 worked for me.

**Comment by NekR** [comment]
Ah, so changing `ServiceWorker.prefetchRequest` does't work and it still requests everything with `omit`?

**Comment by NekR** [comment]
@TimGeisler I just published, `4.4.1`, can you try it? Sorry for the mess.

**Comment by TimGeisler** [comment]
Wow. You are fast! Thanks a lot - 4.4.1 works for me.

**Comment by NekR** [comment]
Great, thanks for reporting it! 👍

**Comment by GGAlanSmithee** [comment]
@NekR is all that needed to do to change this line https://github.com/NekR/offline-plugin/blob/master/src/index.js#L47 ? Want PR?

**Comment by NekR** [comment]
Yes, only that. PR would be good :-)
