### ISSUE TITLE
Chunk hashes

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#129]
Related to: https://github.com/webpack/webpack/issues/1315

Basically, `offline-plugin` should calculate its own hashes (`SHA-1`) for every `compilation.assets` file which participate in caching. This is needed to not be depended on particular version of webpack or usage of one more third party plugins.

It also probably makes sense to calculate hashes on client side when doing `updateStrategy: 'changed'` install and when performing dynamic caching of assets used in `caches` option (assets used in `additional`/`optional` sub sections) to verify if file is indeed the one we need.

**Comment by jampy** [comment]
Since the linked issues suggest this as a solution: is this already implemented?

And, for better comprehension: what is this hash used for? Does it rename the files / URLs?

**Comment by NekR** [comment]
It's in development. It doesn't change files or its names/URLs. It doesn't change anything in build process. Those hashes will be generated internally only for `offline-plugin` usage and the usage is to compare hashes on SW update and download only changed files. The reason to have `offline-plugin` own hashes for that is to avoid any problems with webpack or its plugins used which affects hashes in any way. i.e. just to be safe.

**Comment by haf** [comment]
...and if I don't add yet another module (https://github.com/zhenyong/webpack-stable-module-id-and-hash), will OfflinePlugin work out of the box when using chunkhashes?

– I don't mind changing hashes and redownloading; but I would mind some modules being renumbered and therefore failing to be loaded properly.

**Comment by NekR** [comment]
@haf 
> ...and if I don't add yet another module (https://github.com/zhenyong/webpack-stable-module-id-and-hash), will OfflinePlugin work out of the box when using chunkhashes?

I'm not really sure what you mean, but `offline-plugin` works independently from any other webpack plugins. This issue only about `offline-plugin`'s implementation detail and doesn't effect anything else in your webpack build. You may use whatever chunk-hash plugin (or none of them) in your build and it will be fine with `offline-plugin`. Right it uses webpack's generated hashes which are modified by some chunk-hash plugins, but after this change landed `offline-plugin` will be using its own hashes for its own things. You still may want to use `[chunkhash]` or `[hash]` wherever you want.

> – I don't mind changing hashes and redownloading; but I would mind some modules being renumbered and therefore failing to be loaded properly.

That is not really related to this issue. `offline-plugin` doesn't affect your change your assets by any means. It also doesn't affect or change webpack build hashes in any way. This change is needed exactly for a situations where webpack generates old hashes even if chunks content changed. So this means it's not safe to rely on webpack's hashes here and hence `offline-plugin` will be generating hashes **for itself** by itself, to ensure that it always knows when content of assets has been updated.

**Comment by NekR** [comment]
Added to `v4`.
