### ISSUE TITLE
Remove AppCache

### ISSUE THREAD

**Issue by oliviertassinari** [NekR/offline-plugin#13]
Shouldn't we remove the AppCache support since it's deprecated?
https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by NekR** [comment]
@oliviertassinari it's just fallback for older browsers. ServiceWorker is supported only in Chrome and upcoming Firefox, while AppCache is supported everywhere.

If you do not like AppCache, you can disable it this way:
```js
new OfflinePlugin({
  // ...
  AppCache: null,
  // ...
})
```

**Comment by oliviertassinari** [comment]
> ServiceWorker is supported only in Chrome and upcoming Firefox, while AppCache is supported everywhere.

Well, let's wait for better support then.
