### ISSUE TITLE
document prerequisites

### ISSUE THREAD

**Issue by jampy** [NekR/offline-plugin#130]
As discussed in #127, please document all prerequisites necessary to make this plugin work properly.

For example, I learned that it's important that "sw.js" is served with headers that disallow caching. A simple note on which headers would be appropriate would be important.

Likewise, if there are other pitfalls, these should be documented as well.

**Comment by NekR** [comment]
Thank you, I'll add it.

**Comment by GGAlanSmithee** [comment]
@jampy we now have the [troubleshooting](https://github.com/NekR/offline-plugin/blob/master/docs/troubleshooting.md) docs. It's not exaclt what you suggested, but should cover the case you points out and more.

Do you (adnd @NekR) feel there is a need for another separate doc regarding this, or would it just fragment the docs more?

**Comment by NekR** [comment]
@GGAlanSmithee good point! I don't think there is a need for another doc file. If someone else has suggestions about prerequisites we can add them as "make sure" or something like that section to the troubleshooting doc.
