### ISSUE TITLE
Add array for includes not just excludes

### ISSUE THREAD

**Issue by KyleAMathews** [NekR/offline-plugin#132]
I often prefer whitelisting over blacklisting so it'd be nice to add that option.

**Comment by NekR** [comment]
I think this should work:

```js
new OfflinePlugin({
  caches: {
    main: ['main.js', 'chunk.*.js']
  }
});
```

That's caches whitelisting. Have you tried that?

**Comment by NekR** [comment]
@KyleAMathews closing this, I hope you solved it. Let me know if not.
