### ISSUE TITLE
occasional service worker failures (causing a broken app)

### ISSUE THREAD

**Issue by jampy** [NekR/offline-plugin#142]
My application uses multiple chunks to split the code.

**From time to time I noticed that the application fails to load chunks/URLs, with no apparent reason.**

Once it fails, it is not able to recover by itself. For example, force-closing the browser or restarting *the device* does not help. The very same URL keeps failing.

The only possibility to "fix" the problem is to manually clear all(!) the application data in the browser.

Right now this problem appeared once again on my phone (Samsung S7 running Chrome 54), so I started a remote debugging session using Chrome devtools.

There isn't much to see in the console log, except for this suspicious message:

```
Service Worker termination by a timeout timer was canceled because DevTools is attached.
```

The network tab shows this for the "failing" request:

![grafik](https://cloud.githubusercontent.com/assets/820758/20926476/bfefd768-bbbc-11e6-82b7-71a7e497e9cc.png)

![grafik](https://cloud.githubusercontent.com/assets/820758/20926491/d525d5b0-bbbc-11e6-9f34-fe0053cd1100.png)

The `Response` tab says `This request has no response data available.`

In case it helps, here you can see all the network requests since application start:

![grafik](https://cloud.githubusercontent.com/assets/820758/20926632/b148adce-bbbd-11e6-97d2-7b3194b3192e.png)

In other browser sessions the URL (which is correct) can be loaded without any problems. In fact, on other computers the same app works fine.

What can cause this?

**Comment by jampy** [comment]
> Service Worker termination by a timeout timer was canceled because DevTools is attached.

After a reload, that message didn't appear anymore (but the URL keeps on failing) - so it may not be relevant.

FYI, this is what the "Service Workers" devtools page shows:

![grafik](https://cloud.githubusercontent.com/assets/820758/20926752/57fd332e-bbbe-11e6-81c5-46883cc80ebe.png)

The first "client" is the application running in PWA mode (no browser UI) in background. The second "client" is the normal Chrome browser which I am debugging (both have the same problem, though).

**Comment by NekR** [comment]
Okay, first of all -- this is weird. If you get a response from the SW which it received from the server (and it was received from the server because of headers) and that response doesn't have body, then this means response from the server didn't had body too. Though, it isn't visible from your screenshot if there is response or not (but I trust you of course).

> Once it fails, it is not able to recover by itself. For example, force-closing the browser or restarting the device does not help. The very same URL keeps failing.

There is no recovery mechanism -- if ServiceWorker received malformed data it won't re-fetch it or similar because it simply doesn't know if data is malformed. Basically, that shouldn't happen because you are using https and in theory no one can hijack that response. In case if that's server problem then that's a bug and you simply need to release new version of SW. Though, you may need to bump all hashes of all assets in such case (probably makes sense to have a recovery for this case).

> The only possibility to "fix" the problem is to manually clear all(!) the application data in the browser.

Not sure how this is related to `offline-plugin`. Clearing website data should be enough. If that isn't the case, then that's browser's bug. 


> There isn't much to see in the console log, except for this suspicious message:

That message is not related.

_____________________________________________________

All data provided here doesn't really help. What you need to provide is:

* Your `OfflinePlugin` config
* SW meta data (located at a top of SW file within `__wpo` variable)
* Inspect `offline-plugin` cache in `DevTools -> Application -> Cache Storage` and check what's there. It doesn't provide info about what content is in there, but if you could extract that manually from `window.caches` it would be great.

**Comment by jampy** [comment]
>  If you get a response from the SW which it received from the server (and it was received from the server because of headers) and that response doesn't have body, then this means response from the server didn't had body too. 

Could this simply be caused by a temporary network problem? You know, connections occasionally fail in Internet... ;-)

I mean, does the SW check if the response is okay? For example, if there is a `Content-Length` header but the body is incomplete, does the SW discard the request as invalid? I guess such a mechanism would be important.

>Basically, that shouldn't happen because you are using https and in theory no one can hijack that response. In case if that's server problem then that's a bug and you simply need to release new version of SW.

I wouldn't say that only bugs can cause this. In a modern infrastructure with load balancers, server clusters etc. I think it can happen from time to time that anything fails. At least the network connection between browser and server can go down at any time (especially on mobile...), there is not much one can do about it, unfortunately. 

OTOH, service workers are (also) meant to mitigate problems with bad connections.

>Not sure how this is related to offline-plugin. Clearing website data should be enough. If that isn't the case, then that's browser's bug.

On mobile, you don't have many options (just "clear & reset"). Anyway, I just wanted to point out that the user needs to take relatively drastic action to "fix" the website. In cases where the website stores important data locally (like in my case) this is a big problem.

>All data provided here doesn't really help. What you need to provide is:

I try to give you as much information as I can :-)

OfflinePlugin config:

```
      new OfflinePlugin({ 
        updateStrategy: "changed",
        version: "[hash]",
        AppCache: {
          events: true
        },
        ServiceWorker: {
          events: true
        }
      }),
```

Here is the _wpo info (pretty printed):

```javascript
var __wpo = {
    "assets": {
        "main": ["/webapp/f805ffc38b1ddd88547a296b69f1d8be.jpg", "/webapp/f2ed1e0a4b396e9342d3a372f80e1613.jpg", "/webapp/e225edee76220e822241be06729e7113.jpg", "/webapp/dd9646bf5692a3f8f96d791255485fd8.jpg", "/webapp/8a16cbb724e272679b628634ed6c7d5b.jpg", "/webapp/fe6588776179f1567fadf2402911ccf7.jpg", "/webapp/7cb0d2482ecadc1b80eb0abe457371b6.png", "/webapp/a98a68a307bd1c36a775495a5f4cfdd3.jpg", "/webapp/42c491c8f73baa9a551efafe8c4264b8.jpg", "/webapp/4b4a03816c41fa2abd85a03a10309357.jpg", "/webapp/435e8e207c0e3e60642c95b46cfd9a89.jpg", "/webapp/64f8534df41b252fa0ace0a252703528.jpg", "/webapp/d208dd4d9b6b031a4bdc20389b7aae2f.jpg", "/webapp/324b4fcaf164735c627269504b7bc28e.png", "/webapp/360d0bda9ff57e8df4d44099e239a994.jpg", "/webapp/main-bundle-15bfb33934cce63c7e37e03d017fef-en.js", "/webapp/db-engine-worker-bundle-15bfb33934cce63c7e37e03d017fef-en.js", "/webapp/2-chunk-0-53-6623f14d4f27c7970076464e4-en.js", "/webapp/3-chunk-0-53-f0989e396cd4b4a4daa2dd506-en.js", "/webapp/4-chunk-0-53-ddfbe740c1ab9b4d1cea36858-en.js", "/webapp/5-chunk-0-53-d715a8d8a8c26a21120696a53-en.js", "/webapp/6-chunk-0-53-defa89ba7ef1717409086b44e-en.js", "/webapp/pdfjs-worker-bundle-15bfb33934cce63c7e37e03d017fef-en.js", "/webapp/8-chunk-0-53-f9d5dbfa5c8f5ca3099eb4a7e-en.js", "/webapp/9-chunk-0-53-a2eed6c34bc1e6e383750486f-en.js", "/webapp/10-chunk-0-53-157da5d2167ce94bf30d4a176-en.js", "/webapp/11-chunk-0-53-19e9ff88d9fe7931cdeb2dd01-en.js", "/webapp/favicon-7251e6e6a768198a0cfd30af9ffaafda-en.ico", "/webapp/app-icon-b38da28e9e64d2e33be74a5128bbecc3-en.png", "/webapp/manifest-0d5d93e25e9e50a4bfd9bac1cb70122f.json", "/webapp/"],
        "additional": [],
        "optional": []
    },
    "externals": [],
    "hashesMap": {
        "d15059993517d4f723a91ea748f9289a09febbbc": "/webapp/f805ffc38b1ddd88547a296b69f1d8be.jpg",
        "a31eb831de6ca0b956b63c09bc026a8681dfcc35": "/webapp/f2ed1e0a4b396e9342d3a372f80e1613.jpg",
        "4f169dae9053df6d79c5274a166b59f90e7d5693": "/webapp/e225edee76220e822241be06729e7113.jpg",
        "632c974f597eb16023c30869a817ea9b504eb82f": "/webapp/dd9646bf5692a3f8f96d791255485fd8.jpg",
        "be24b3140ad226ced8deb26aac3d6c420f78a535": "/webapp/8a16cbb724e272679b628634ed6c7d5b.jpg",
        "0522d90b213a42366a2fe063077fe981ab58f204": "/webapp/fe6588776179f1567fadf2402911ccf7.jpg",
        "0dbc42bf6f9b7166196dd88bdbb45a11307ec8a5": "/webapp/7cb0d2482ecadc1b80eb0abe457371b6.png",
        "969aedf7be117aa1599d74ffa02e9393476dd745": "/webapp/a98a68a307bd1c36a775495a5f4cfdd3.jpg",
        "adad01101cb7122c6b01d2ff415e303025c0dfc1": "/webapp/42c491c8f73baa9a551efafe8c4264b8.jpg",
        "c74b2ca202f02597a37ba80840f5b0dd0eaa1bbe": "/webapp/4b4a03816c41fa2abd85a03a10309357.jpg",
        "3fb74cb5c8594ff686a45ed8bb0cc3241e6543bd": "/webapp/435e8e207c0e3e60642c95b46cfd9a89.jpg",
        "f4918bcce738ee601bb0369199cfd26fd35bb2e2": "/webapp/64f8534df41b252fa0ace0a252703528.jpg",
        "ecd0296ecf18fa7fc50fbb73f65483e82e9a92da": "/webapp/d208dd4d9b6b031a4bdc20389b7aae2f.jpg",
        "34239130c3aea22f21455746284d5a266435fa39": "/webapp/324b4fcaf164735c627269504b7bc28e.png",
        "1a9b288cc09c5350763dbe81e8b225c1a99901af": "/webapp/360d0bda9ff57e8df4d44099e239a994.jpg",
        "7ea8c029393164098795ab02abab4c40a0f35cbf": "/webapp/main-bundle-15bfb33934cce63c7e37e03d017fef-en.js",
        "ce48d7af1cddbe0fc49c954a07b49468728f70bf": "/webapp/db-engine-worker-bundle-15bfb33934cce63c7e37e03d017fef-en.js",
        "94d160614ae6af7a2b3edec82d12c10b53eb56bd": "/webapp/2-chunk-0-53-6623f14d4f27c7970076464e4-en.js",
        "5556aa013d4026568142af828f9f8a1023a5bad9": "/webapp/3-chunk-0-53-f0989e396cd4b4a4daa2dd506-en.js",
        "3c7bc687dbf3eb21abb3efe03f4c9049f903f88a": "/webapp/4-chunk-0-53-ddfbe740c1ab9b4d1cea36858-en.js",
        "1b24945b39ab7f26d3e11c6989fc6d6095c0d4bd": "/webapp/5-chunk-0-53-d715a8d8a8c26a21120696a53-en.js",
        "5fe68400bdcb75d7128794d104fb7d8da1c774d7": "/webapp/6-chunk-0-53-defa89ba7ef1717409086b44e-en.js",
        "ab8e92295ca358d71729acb0ce9631a4413f7439": "/webapp/pdfjs-worker-bundle-15bfb33934cce63c7e37e03d017fef-en.js",
        "7743041b6eaed56ca3eb2df737db8ad1900b3876": "/webapp/8-chunk-0-53-f9d5dbfa5c8f5ca3099eb4a7e-en.js",
        "cdb22ec1cc1cfd904af8a8aba6a4414325d44427": "/webapp/9-chunk-0-53-a2eed6c34bc1e6e383750486f-en.js",
        "7fe415389d594897ab2fc660e28363140f41f82e": "/webapp/10-chunk-0-53-157da5d2167ce94bf30d4a176-en.js",
        "54d9d0144d004c44fee04d045d991596746f1493": "/webapp/11-chunk-0-53-19e9ff88d9fe7931cdeb2dd01-en.js",
        "0488c0b3b673eea709376108bd51c35bfbdda4a8": "/webapp/favicon-7251e6e6a768198a0cfd30af9ffaafda-en.ico",
        "543bb6e3bc8237e2e5b6624848b80769e62c1733": "/webapp/app-icon-b38da28e9e64d2e33be74a5128bbecc3-en.png",
        "e6734c50c15e6f929481486fac15080beac267e6": "/webapp/manifest-0d5d93e25e9e50a4bfd9bac1cb70122f.json",
        "b78e4e31b72174c0cf7a57f55e70e42a5b063ef0": "/webapp/"
    },
    "strategy": "changed",
    "responseStrategy": "cache-first",
    "version": "fbcb072cedf1c185bff15ef8957fc102dfc05c5f",
    "name": "webpack-offline",
    "pluginVersion": "4.5.2",
    "relativePaths": false
};
```

Unfortunately I can't give any details from the browser's cache storage since it has been cleared in the meantime. I recall there have been many entries, though.

Should it happen again (I expect that it will, sooner or later), I will post details here.

Does the provided information give you more insight, hopefully?

**Comment by NekR** [comment]
> Could this simply be caused by a temporary network problem? You know, connections occasionally fail in Internet... ;-)

That actually shouldn't affect anything since SW is still behind the browser and if something fails browser makes it as failed and then SW doesn't use that response. Yes, SW checks if response is okay (one of 2** responses). It doesn't check for `Content-Length` or other headers though because browser by itself should take care of it and if something is wrong with response then it should reject the request.

I mean, it should work this way. But who knows, maybe they miss something.

> I wouldn't say that only bugs can cause this. In a modern infrastructure with load balancers, server clusters etc. I think it can happen from time to time that anything fails.

Fair enough. This indeed should be handled somehow.

> OTOH, service workers are (also) meant to mitigate problems with bad connections.

Yeah, it does, bad connections shouldn't affect anything here. Though wrong response (by any reason) from the server may.

> Does the provided information give you more insight, hopefully?

Not sure yet. Trying to understand why that could happen except of server returning empty response.

**Comment by jampy** [comment]
> if something fails browser makes it as failed

Honestly, I wouldn't take that for granted (at least not with all browsers out there).

Anyway, I did a simple test by forcing an URL to respond with a broken response:

```javascript
  app.use((req, res, next) => {

    if (req.url.indexOf("/3-chunk-") >= 0) {

      console.log("SIMULATE CONNECTION ERROR FOR", req.url);

      // same headers as normal static requests:
      res.set("Cache-Control", "no-cache, no-store, must-revalidate");
      res.set("Pragma", "no-cache");
      res.set("Expires", "0");

      // fake Content-Length header:
      res.set("Content-Length", "123456");

      // short response:
      res.end("// krrrrrsssshhh NO CARRIER ;-)");

    } else {
      next();
    }

  });
```

...then caused a modification of the `3-chunk-...` chunk, so that it needs an update.

When that URL is requested, Chrome keeps that request in a "pending" state and the console shows:

![grafik](https://cloud.githubusercontent.com/assets/820758/20967307/149066da-bc7f-11e6-919d-c3165d6f00db.png)

After a few seconds the request fails and console shows (ignore the yellow lines):

![grafik](https://cloud.githubusercontent.com/assets/820758/20967338/4062078c-bc7f-11e6-9490-d78a4f65d8a3.png)

However, the SW aborts the update process (which is good) and continues to serve the old assets, including the `3-chunk-...` chunk from the local cache. Reverting the webserver to normal behavior allowed offline-plugin to complete the update on next page load.

With other words, I could *not* reproduce the problem described in this issue by simply causing a bad HTTP response. `offline-plugin` did what it probably was meant to do. I did only test with Chrome, though. 

We'll see if this happens again. I'll try to give you the `Cache Storage` info then (if something else could be helpful, please tell me).

**Comment by NekR** [comment]
@jampy I think I can try a potential fix to this problem. There is the only possible way (except of bug in Chrome itself) where and why that problem could be. Would you mind to it from the `master` after that? (not sure when I'll have it done though, will try as soon as possible)

**Comment by jampy** [comment]
@NekR I'll be happy to try anything you want. :-) Are you saying I should install `offline-plugin` from GitHub `master` instead of using the NPMJS release?

**Comment by NekR** [comment]
@jampy yeah, but not yet :-)

**Comment by NekR** [comment]
@jampy Okay, I just pushed potential fix. Can you try if from the `master`?

**Comment by NekR** [comment]
@jampy oh, and please, try locally first and only then to production (if you do deploy that to production)

**Comment by jampy** [comment]
@NekR 

okay, I changed my `package.json` to...

```
"offline-plugin": "github:NekR/offline-plugin#036f3f9"
```

(that's the latest commit hash ATM)

In the last days the problem didn't show up anymore (and I did 10~20 app updates). Anyway, I'll let you know when if happens again or I notice something else...

In the meantime, thanks for your efforts!

**Comment by jampy** [comment]
Okay, I have to correct myself. I did not notice that using offline-plugin master breaks my build:

```
...
    Child __offline_serviceworker:
            + 3 hidden modules

        ERROR in __offline_serviceworker from UglifyJs
        SyntaxError: Unexpected token: name (promises) [./~/async-waituntil-polyfill/async-waituntil.js:8,0]
```

I'm not sure what may causing this. AFAIK `offline-plugin` should be usable right from the GIT repository since the babel-transpiled code is checked in, right?

**Comment by NekR** [comment]
@jampy Yeah, that's weird. I'll check.

**Comment by NekR** [comment]
@jampy I think it's probably babel not processing modules required from `npm`.

**Comment by jampy** [comment]
@NekR can I do/try something?

**Comment by NekR** [comment]
@jampy Hey, sorry, I actually too busy this month so don't do much stuff for `offline-plugin` :-( But I'll try to make this fix soon

**Comment by NekR** [comment]
@jampy okay, I made the modification in separate branch, it should work fine now. You can install it this way:
```
npm install NekR/offline-plugin#feature\/async-waituntil
```

**Comment by jampy** [comment]
@NekR sorry for the late reply - I'm pretty busy ATM

I switched to the `async-waituntil` branch right now. So far everything works fine - we'll see how this behaves...

However, please note:

- The problem did not reveal itself anymore in the last days/weeks anyway. That *might* be because I had to do some changes on my deployment method. Now my deploy script makes sure that all files (except `sw.js` and `index.html`), get unique file names (at least) when their content changes. With other words, no URL is ever reused with changing content. This *may* work around the issue discussed here or not - I don't know...

- I notices that the `async-waituntil` branch **is behind** `master` - maybe rebase?

Anyway, thanks..

**Comment by NekR** [comment]
@jampy sounds good. This seems to me like there is no issues in `offline-plugin`. Yeah, `async-waituntil` is behind `master`, but there is no critical things in it to rebase. I'll just merge it to `master` soon anyway. Thanks for testing it!

**Comment by NekR** [comment]
I think I'll just close this. If issues will raise again then we can re-open.

**Comment by jampy** [comment]
I *guess* there *may* be still an issue with `offline-plugin` if asset *contents* change. It's just that *I* avoid such situations completely now and in that way circumvent the problem. Others may still experience this problem.

Anway, @NekR, should I continue using the `async-waituntil` branch or stick with the normal release now?

**Comment by NekR** [comment]
Yes, I agree there might be a problem or more in `offline-plugin`, but I cannot just keep open or trying to solve unknown problem. Once there will be a repro I'll re-open this for sure. 

There is also a thing that `offline-plugin` is being used by many people but no one else reports this problem. So again, once there is a repro -- I'll be happy to open this again.

> Anway, @NekR, should I continue using the async-waituntil branch or stick with the normal release now?

As you wish. `async-waituntil` eventually will be added to `master` and some release.

**Comment by jampy** [comment]
Okay, if you understand you correctly, then the branch `async-waitutil` has nothing to do with this issue. I'll stick with the NPM release in that case.

BTW, I'm able to build `offline-plugin` from source (`master` branch) by manually installing `npm install babel-runtime` - perhaps just a dependency in package.json is missing.

Just wanted to let you know...

Keep up the great work! :-)

PS: I was about to add a feature to `offline-plugin` but then realized that there is already an `entry` option that does exactly what I need - awesome! :-)

**Comment by NekR** [comment]
> Okay, if you understand you correctly, then the branch async-waitutil has nothing to do with this issue. 

It's related to this issue. I don't know how this issue may happen and have no repro for it, so the potential thing why it may happen is that thing with _async waitUntil_, so I made that change and asked you to test with it. But since you are saying that you don't face this issue at all anyway (even without _async waitUntil_ fix) I assume that there is no issue at all. Once there is repro -- I'll be happy to resolve it and apply needed fixes :-)

> BTW, I'm able to build offline-plugin from source (master branch) by manually installing npm install babel-runtime - perhaps just a dependency in package.json is missing.

`npm run install:build-deps`. It's exclude from normal install to not force CIs install it (because they don't need it).

**Comment by jampy** [comment]
> `npm run install:build-deps`. It's excluded from normal npm install to not force CIs install it (because they don't need it).

Still need to install `babel-runtime` manually, since `buildDependencies` in `package.json` only lists `"babel": "^5.8.23"`.
