### ISSUE TITLE
Add a configuration option to disable non-error/warning console output

### ISSUE THREAD

**Issue by begincalendar** [NekR/offline-plugin#143]
In my opinion it would be ideal if we could disable all the console logging in production, e.g. via a configuration option.

Personally I think it's noise in the console, when in production, or even when it's not wanted at all.

**Comment by NekR** [comment]
@begincalendar see this: https://github.com/NekR/offline-plugin/issues/87

**Comment by begincalendar** [comment]
@NekR Thank you, that's done the trick.

Apologies I didn't find that myself. 
I think I only searched the open issues, as opposed to all of them.

**Comment by NekR** [comment]
@begincalendar no problem, that happens 👌

**Comment by NekR** [comment]
It probably makes to add that to the docs or at least to FAQ. Would you be
interested in adding that to the FAQ?

**Comment by begincalendar** [comment]
I created a [PR](https://github.com/NekR/offline-plugin/pull/146).
