### ISSUE TITLE
Specify/warn that AppCache deprecated

### ISSUE THREAD

**Issue by ctrlplusb** [NekR/offline-plugin#144]
According to the mozilla docs:

https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

<img width="697" alt="screenshot 2016-12-07 08 12 01" src="https://cloud.githubusercontent.com/assets/12164768/20959822/ed8931e0-bc54-11e6-94df-a6122d7ccdd0.png">

**Comment by jampy** [comment]
see #13, which is [still valid](https://jakearchibald.github.io/isserviceworkerready/)

**Comment by NekR** [comment]
Also, I personally use AppCache some times. Right now AppCache is **enabled** by default because SW isn't that popular and many prefer to use AppCache too. In a some time, AppCache will be disabled by default and later removed completely from the plugin. For now, there is nothing bad to supporting it since it affects nothing :-)

**Comment by ctrlplusb** [comment]
Sorry, I should have been clearer with my intentions.  Perhaps we should update the docs to indicate this fact to adopters?

**Comment by NekR** [comment]
@ctrlplusb hm.. that makes sense actually. Any ideas how to do that better?

**Comment by ctrlplusb** [comment]
I would suggest we put the warning in the [configuration section](https://github.com/NekR/offline-plugin#appcache-object--null--false) for the AppCache.

I'm happy to do a PR if you agree.

**Comment by NekR** [comment]
@ctrlplusb Yes, I agree, that makes sense. Please do!

**Comment by NekR** [comment]
@ctrlplusb just put that sentence right. It should be clear that AppCache is deprecated in general and in browsers but not in `offline-plugin`.

**Comment by NekR** [comment]
Fixed in #145
