### ISSUE TITLE
Tag releases in repo

### ISSUE THREAD

**Issue by andykenward** [NekR/offline-plugin#150]
Would be great if you started to tag [releases](https://github.com/NekR/offline-plugin/releases).

https://github.com/NekR/offline-plugin/releases

https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by NekR** [comment]
hey @andykenward, I have nothing against it actually, I just don't see yet why it's needed/makes sense. There is a https://github.com/NekR/offline-plugin/blob/master/CHANGELOG.md actually which has all the data.

**Comment by andykenward** [comment]
@NekR But if you actually want to look at the code for each release via the `CHANGELOG.md` you can't. You have to search through the commit titles to find them and hope the one released on NPM is that one.

I honestly don't see why you wouldn't add a simple tag `v.4.5.3` to the commit that is that version published to NPM.

I use [`git-flow`](http://nvie.com/posts/a-successful-git-branching-model/) workflow for this reason.

If you look at `react` [releases](https://github.com/facebook/react/releases) and [tags](https://github.com/facebook/react/tags) history. Don't you think that makes people's life easier?

Also allows people to use Github drop-down menu to quickly access tags

<img width="350" alt="screen shot 2016-12-20 at 19 35 40" src="https://cloud.githubusercontent.com/assets/4893048/21365094/a0a4af8e-c6eb-11e6-83c7-2c8e1fcd57a7.png">

**Comment by NekR** [comment]
I'm going to be honest about this -- I don't use it because I'm too lazy. But I'll try to reconsider it.

@andykenward have absence of tags/releases made things harder for you? What exactly you were looking for?

**Comment by sokra** [comment]
Try `npm version`. It handles version number commit and tag for you.

`npm version patch && git push && git push --tags && npm publish` is a nice Workflow and not that much work.

**Comment by TheLarkInn** [comment]
There is also semantic-release which handles it all for you based on your commit messages. Using `commitizen` and `cz-conventional-changelog`

**Comment by NekR** [comment]
@sokra that's interesting, I didn't know about `npm version`. Thanks 👍

**Comment by NekR** [comment]
@TheLarkInn `semantic-release` seems too complicated (in comparison to `npm version` for example). But I'll check that too, thanks! :-)

**Comment by NekR** [comment]
Just to not forget: It may make sense to use this for GitHub Releases: https://github.com/zeit/release

**Comment by NekR** [comment]
Okay, I made my first _release_ with `npm version patch && git push && git push --tags && npm publish`: https://github.com/NekR/offline-plugin/releases/tag/v4.5.4
I'll be trying other ways too though.

**Comment by NekR** [comment]
I started doing releases. I do them as @sokra suggested, seems fine enough to me. Thank you!
@andykenward thank you too for reporting this, I think we can close this now :-)
