### ISSUE TITLE
Docs website

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#153]
Maybe use https://docute.js.org/ for docs website

**Comment by egoist** [comment]
Anything I can help with? 😄

**Comment by GGAlanSmithee** [comment]
BTW, there's also this https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by egoist** [comment]
@GGAlanSmithee that's true, you can use jekyll for that

**Comment by NekR** [comment]
@GGAlanSmithee  Thing is that docute is @egoist's thing :-) I like docute, it seems nice.

I'm just not really sure we need docs website right, I just created this to not lost the idea. There is little-to-no docs right now, so it's fine as is I think.

@egoist thanks for help suggestion :-)

**Comment by GGAlanSmithee** [comment]
ah, sorry @egoist, didn't notice!

**Comment by GGAlanSmithee** [comment]
@NekR I decided to try using docute in an other project; http://ggalansmithee.github.io/Entities/#/ it was quite easy to set up, would you like me to give it an attempt for your repo? (Might take a buit if time - not super much free time atm).

**Comment by NekR** [comment]
@GGAlanSmithee if you don't have much time then that's isn't necessary. We can definitely keep in mind this issue and when we'll have time we'll do it :-)

**Comment by NekR** [comment]
@egoist added docute. I'll try to deploy it somewhere soon. 👍

**Comment by GGAlanSmithee** [comment]
nice 💯
