### ISSUE TITLE
Wildcards within the externals option

### ISSUE THREAD

**Issue by amangeot** [NekR/offline-plugin#154]
Hello,
First of all, thank you for this project, this is awesome!

I saw in the documentation that we can use wildcards within the `excludes` option. Does it make sense to use wildcards within the `externals` option ? Is there a way to do it ?

**Comment by NekR** [comment]
@amangeot HI, thanks :-)

I'm cannot find the discussion about it, but it certainly been discussed before. What for you need wildcard in `externals`? Dynamic caching of external urls/assets?

**Comment by amangeot** [comment]
I'd like to add offline to an app to serve it within a webview.

I want to cache a few images that are served within the dist under `/images/...`, without having to mention them one by one. These images are not hashed by webpack as they should not change on every compilation. I don't want the user to download these images every time I recompile.

I'm quite new to this so I might use offline the wrong way. The first time the app loads and the SW is installed, will it download every single file mentioned in `externals` ? Even before a page actually requires these images ?

**Comment by NekR** [comment]
@amangeot you can probably try to those images with `CopyWebpackPlugin`, this way in watch mode they are copied only once or when you change them. I assume you need to copy them to the `dist/` folder somehow anyway?

> The first time the app loads and the SW is installed, will it download every single file mentioned in externals ? Even before a page actually requires these images ?

Yep, it will. `offline-plugin` doesn't really support dynamic caching at a moment (i.e. cache when requested), but that can be done by writing a bit of SW code by hand.

**Comment by NekR** [comment]
@amangeot if you have time it would be good to clarify those things :-)

**Comment by amangeot** [comment]
Thank you for the explanation about dynamic caching.

Regarding my project, it's based on [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit), webpack already copies public assets to the /dist.

Let's say you have an icon pack to cache, I am wondering if the entire icon folder (already under `/dist`) could be served offline using a wildcard (`/icons/*`), or if they need to be mentioned one by one ?

Sorry for the time to reply !

**Comment by NekR** [comment]
@amangeot if they are moved to `/dist` by webpack them you don't need to do anything. They are automatically listed and cached. Check generated `sw.js`, there is a `__wpo` variable with metadata/options. It should have your icons listed there.

**Comment by amangeot** [comment]
Oh ok, I'll check again then. 

I'll close the issue, thank you for the replies !

**Comment by NekR** [comment]
Sure, feel free to ask other questions if something :-)
