### ISSUE TITLE
WebWorker reload page on cash update

### ISSUE THREAD

**Issue by avizaviz** [NekR/offline-plugin#155]
I am using React+webpack+offline-plugin to create a webworker with persistent cashing for the website.

I want to tell the user when a new version is stored in cash and suggest to refresh the page but I dont know how to reference the webworker and what event I should lisiten too (webworker is created automatically by npm "offline-plugin")

Standard flow today:

1. Webmaster publish a site (V1)
2. User visits the website
3. He sees the website (V1) while web worker stores pages in persistent cash
4. Webmaster publishes a new version (V2)
5. User revisits the site seeing old version from persistent cash while web worker loading new version in the background (V2).
6. When the user will refresh the page he will see website version 2

New flow should be:

6. V2 loaded done in the background
7. A popup message tels the user to refresh the page to get the new version.

**Comment by NekR** [comment]
Okay, let's start from the beginning. First of all, it's ServiceWorker, not WebWorker.

> 6. When the user will refresh the page he will see website version 2

Second thing is that this is wrong. With ServiceWorker user gets new version when all tabs of the website are closed, so when user opens it again he/she sees the new version. Reload doesn't count.

> but I dont know how to reference the webworker and what event I should lisiten too

You don't need to reference ServiceWorker manually in this case, though you can do it with `navigator.serviceWorker`. All you need to do is enable events in `OfflinePlugin` and then add couple of things to your project's code:

```js
// OfflinePlugin in webpack.config.js
// Enabling ServiceWorker events

new OfflinePlugin({
  ServiceWorker: {
    events: true
  }
})
```

```js
// Somewhere in your webpack entry

const offline = require('offline-plugin/runtime');

offline.install({
  onUpdating: () => {
    console.log('Update started in background');
  },
  onUpdateReady: () => {
    console.log('Update is ready to be applied');
    // The following is your function
    displayUserUpdatePrompt({
      onAgree() {
        // Apply update
        offline.applyUpdate();
      }
    });
  },
  onUpdated: () => {
    // This called when update is applied (by offline.applyUpdate())
    // Be careful, this even is fired in all tabs, not only in the one
    // which called offline.applyUpdate()

    // Do the page reload
    window.location.reload();
  },

  onUpdateFailed: () => {
    console.log('Update filed by some reason');
  }
});
```

**Comment by avizaviz** [comment]
Thanks that helped.

**Comment by NekR** [comment]
That's great! Feel free to ask questions, if any :-)
