### ISSUE TITLE
Cache dissapearing on reload

### ISSUE THREAD

**Issue by Chrischuck** [NekR/offline-plugin#163]
Hi all,

I'm having a little trouble getting the plugin to work offline. When there is a connection the service worker works normally and will serve from the cache. However when I go offline, the cache simply disappears and the service worker responds with "An unknown error occurred when fetching the script." This is happening both locally (express server) and on my live site (nginx reverse proxy and express, it does have an ssl certificate). Google lighthouse also confirms it doesn't work offline

My webpack config:
https://github.com/Chrischuck/bare-minimum/blob/sw/webpack.production.config.js

Where I register worker: 
https://github.com/Chrischuck/bare-minimum/blob/sw/src/index.js

Both are pretty standard taken from docs.

My cache before I go offline(local):
<img width="556" alt="screen shot 2017-01-21 at 5 53 43 am" src="https://cloud.githubusercontent.com/assets/13311268/22174923/119bde26-df9f-11e6-9afd-8260b99af1d1.png">

My cache before I go offline(actual site):
<img width="799" alt="screen shot 2017-01-21 at 6 11 55 am" src="https://cloud.githubusercontent.com/assets/13311268/22174990/9f5d4ac8-dfa0-11e6-9441-d5f609e189cd.png">

Worker after I go offline:
<img width="558" alt="screen shot 2017-01-21 at 5 54 25 am" src="https://cloud.githubusercontent.com/assets/13311268/22174925/1b3df5ea-df9f-11e6-8ee1-5edb8332365d.png">

As I said before, when I go offline and refresh the page, my cache disappears which I assume why I'm getting that error because the worker can't serve anything from the cache. I've tried restarting my browser, killing all other service workers, and clearing cache on the site but to no avail.

Best regards,
Chris

**Comment by NekR** [comment]
"An unknown erro ..." error means that ServiceWorker file fetching failed. It fails when you are offline, of course.

Those lists of requests/responses aren't actually really useful. If response doesn't display "OK" it doesn't mean it wasn't cached. It actually doesn't mean that response isn't "OK", it just doesn't display the "OK" in there.

What happens in your, I assume it at least, is that you are refreshing your page when you aren't on `/` but rather on some subpage like `/something`. I don't know, may be it's unexpected but `offline-plugin` doesn't cache your routes or applies _app-shell_ by default. It caches only pages you specify which in your case is `/` only. You may need [this option](https://github.com/NekR/offline-plugin/blob/master/docs/cache-maps.md) to fix it or `ServiceWorker.navigateFallbackURL` option.

**Comment by Chrischuck** [comment]
Thank you! I added a cache map and it worked.
