### ISSUE TITLE
[help] Don't cache /api in cacheMaps

### ISSUE THREAD

**Issue by mcchrish** [NekR/offline-plugin#167]
So what I have is an app with two parts, the front-end app with this plugin installed and an API. Both are under the same domain with the app being in the `/` route while the api in the `/api`.

Problem now is that it seems the SW is also caching the requests from the app to the `/api`. Trying to add a match regex to exclude `/api` URLs in cacheMaps but doesn't work.
```js
      cacheMaps: [
        {
          match: /^(?!\/api\/).*/,
          to: '/'
        }
      ],
```
What's the correct way of doing it?

**Comment by NekR** [comment]
@mcchrish if you aren't able to specify correct RegExp (which I expect to be possible though), you can use a function instead, like this:
```js
{
  match: function(url) {
    if (url.origin !== location.origin) return;

    if (url.pathname.indexOf('/api/') === 0) {
      return;
    }

    return new URL('/', location);
  }
}
```

**Comment by NekR** [comment]
or also set `requestTypes: ['navigate']` to match only navigate requests instead of all requests.

**Comment by NekR** [comment]
There is doc about this actually: https://github.com/NekR/offline-plugin/blob/master/docs/cache-maps.md

**Comment by mcchrish** [comment]
`requestTypes: ['navigate']` did it, man. Thanks so much for this! 👍
