### ISSUE TITLE
Usage with .htpassword protected websites

### ISSUE THREAD

**Issue by IljaDaderko** [NekR/offline-plugin#170]
We introduced .htpassword protection to our staging environment today, which seems to be breaking service worker as poor guy can't gets 401 (Access denied) when trying to install.

Any way to add authentication headers or something to the service worker so he can access protected files?

**Comment by NekR** [comment]
I actually have no idea how `.htpassword` works. Does it use cookie for auth or `Authentication` header? If it uses header, then how do you request scripts anyway?

**Comment by NekR** [comment]
Anyway, I think you need this option: 

```js
new OfflinePlugin({
  ServiceWorker: {
    prefetchRequest: {
      credentials: 'same-origin'
    }
  }
})
```

This should work with Basic HTTP Auth, which I assume is used by .htpassword.
It by default should be equal to `same-origin`, so if you interested in it then contributions are very welcome: https://github.com/NekR/offline-plugin/issues/123

**Comment by andyexeter** [comment]
It's actually `.htpasswd`, not `.htpassword` - Could you update the title to make it easier for searchers (like me) to find this issue?

Thanks for the solution btw! :)

**Comment by IljaDaderko** [comment]
@andyexeter done :)

**Comment by NekR** [comment]
Great 👍  🎉
