### ISSUE TITLE
Correct way to cache get requests to api?

### ISSUE THREAD

**Issue by zackify** [NekR/offline-plugin#171]
Sorry about this noob question.... I am doing get requests to an api using cors. (It's hosted on a subdomain). All that is needed for the request is an authorization header with their token. How can I configure this plugin to cache those requests?

**Comment by NekR** [comment]
Unfortunately `offline-plugin` doesn't support dynamic caching at a moment. Though, if you know all those URLs in advance then you can put them in `optional` section of the caches and use `ServiceWorker.prefetchRequest.credentials` option set to `include`. Of course, this isn't idea way.

Other way is that you can write your own SW code to cache those URLs by specifying `ServiceWorker.entry` option, then listening to `fetch` event and do caching. This isn't idea too though.

**Comment by zackify** [comment]
Thanks for the help!
