### ISSUE TITLE
Support for wildcard paths in externals option

### ISSUE THREAD

**Issue by abhijit-paul** [NekR/offline-plugin#173]
Many a times we want to include multiple external artefacts like images, videos. Adding them each one by path is tedious and error-prone. Supporting single level wildcard will help maintainability of the code.

**Comment by NekR** [comment]
@abhijit-paul  how exactly wildcard in `externals` should work? To pre-cache assets it needs to know their URLs and with wildcard it of course doesn't know them.

**Comment by NekR** [comment]
Closing because of a lack of response. If you have some valid points about this feature then I'll open this again. Thank you.

**Comment by likeabbas** [comment]
I'm running a Dex website where I have all images from another CDN's url /images/ and these images are being added routinely. Having the wild card would make this much easier. Also, the actual sw.js does wildcards I believe
