### ISSUE TITLE
Cache all or nothing

### ISSUE THREAD

**Issue by haf** [NekR/offline-plugin#175]
Use case:

 - `index.html` -> `deadbeef1234567.js`
 - `index.html` has `Cache-Control: no-cache`
 - `*.js` are cacheable for a long period of time.
 - `index.html` is in the `main` section;

```
    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',
      caches: {
        main: ['index.html'],
        additional: ['*.js', '*.png', '*.jpg', '*.woff', '*.eot', '*.svg', '*.ico'],
      },
      excludes: [
        '**/*.map'
      ],
      // Removes warning for about `additional` section usage
      safeToUseOptionalCaches: true,
      AppCache: false,
    })
```

Upon deploy, old .js-files are removed.

At runtime in the browser, the service worker makes a network request for a `.js` file despite not having checked `index.html` for updates.

Had `index.html` been revalidated (it's in the `main` section after all), the browser would have known to get the latest versions of the JS files, keeping the old `.js` files cached like is supposedly the aim of `sw.js`.

Output 
<img width="1275" alt="8b724a60-e6d3-11e6-95b8-9bb59fa27c72" src="https://cloud.githubusercontent.com/assets/193115/22522350/8bc613ea-e8bb-11e6-9572-e01ed3b02274.png">

You write:

> First load after a deploy may crash only if requests are going directly to the servers, i.e. to the network.

Yes, this is what happens; it's the bug.

> With ServiceWorker they are cached and request go to the cache.

That's the intended behaviour which is not displaying.

> In your case chunks are requested from the network (console shows it) but index.html seems to be loaded from the SW cache.

Yes.

> So, it loads old index.html which points to old scripts which doesn't exist anymore, so server returns HTML and page doesn't work.

Yes.

> When you first visit the page after new deploy -- you get an old page loaded from the cache.

No, this is not what happens. I get network requests going out instead of going to the cache.

> The new page and its assets are being downloaded in background and that new page will be available for usage only when all tabs of the website will be closed.

Or every 24 hours, yes, and if this was the behaviour, we'd be fine.

> Also, since you are using unique file names for each build, it's a good idea to keep your old files on the server and don't delete them.

This seems like a work-around. We'd have to keep all files on the server, forever in that case since we never know how old a version of the JS a client has.

**Comment by NekR** [comment]
@haf, so, can I have a repro for this?

**Comment by haf** [comment]
Well, I gave you one the day I filed, but it's been removed because it broke our site by downloading older file hashes.

We won't be able to try this plugin out for another few months until we've verified it won't break our app again.
