### ISSUE TITLE
Specify service worker domain

### ISSUE THREAD

**Issue by hanford** [NekR/offline-plugin#180]
Hello! so first of all, thanks for this plugin. It's truly amazing!

I work for a company that is on the verge of using this for our consumer application, but I have one question that I can't seem to find the answer for. 

All of our Js lives on a CDN. We are going to put the service worker behind our domain, but webpack will prefix the service worker with the wrong domain.. Is there a way to specify where the service worker will end up? ie `https://url.com/sw.js` otherwise we can't use this as our assets are on a cloudfront domain

**Comment by hanford** [comment]
Oh, looks like service worker publicPatch will do the trick

**Comment by NekR** [comment]
@hanford yeah, `publicPath` is the way. Anyway, if something won't work feel free to open this again :-)

> Hello! so first of all, thanks for this plugin. It's truly amazing!

Thanks!
