### ISSUE TITLE
generated assets includes trailing slash

### ISSUE THREAD

**Issue by hanford** [NekR/offline-plugin#182]
When generating a service worker to cache files, the last asset is a hash, matched with a trailing slash.. unfortunately our s3 set up will respond with a `403` when request that URL. Is there a way around generating that?

**Comment by NekR** [comment]
Not sure I understand. Can you at least provide so examples of URLs, your webpack config or at least `offline-plugin` config? I particularly don't understand this phrase at all:

> the last asset is a hash, matched with a trailing slash..

**Comment by hanford** [comment]
Yeah sorry, I thought I attached some images. So my problem is that webpack is generating a massive hash map for all of my assets, (which is ok) .. and the offline plugin generates a service worker, which will request all of those assets.

The last generated hash, is linked to a trailing slash, so the service worker is trying to do a request to get all of a s3 bucket, and so s3 responds with a 403.

Basically what I'm wondering is can I pass an array of something like `['*.chunk.js']` and only have the service worker fetch those assets? Because every time it fetches the `/` it fails. 

asset list:
http://d.pr/i/nkPb+

My webpack config is relatively simple, here is the list of plugins:

```
const additionalPlugins = [
  // used to split out our sepcified vendor script
  new webpack.optimize.CommonsChunkPlugin({
    names: ['vendor', 'manifest'],
    minChunks: Infinity,
    filename: '[name]-[chunkhash].js'
  }),
  new HtmlWebpackPlugin({
    template: path.resolve(__dirname, '../../', 'www/index.html'),
    minify: {
      collapseWhitespace: true
    }
  }),
  new OfflinePlugin({
    ServiceWorker: {
      events: true,
      publicPath: `${SWPath}/sw.js`
    },
    AppCache: false
  })
]
```

**Comment by hanford** [comment]
Ended up solving with globs and `{caches: { main: ['**.js', '**.css', .. ] } }`
