### ISSUE TITLE
OfflinePlugin using ApplicationCache instead of Service Worker

### ISSUE THREAD

**Issue by simonfl3tcher** [NekR/offline-plugin#186]
Hey everyone, I am struggling with getting my site to always use the Service Worker (regardless of the hosting), I have tried to debug but to no avail.

### Whats the problem?

It seems that depending how the site is being hosted the browser uses either the Service Worker or the application worker. Clearly I would like to use the Service Worker at all times, but for some reason it doesn't seem to work on some occasions.

I have tried multiple ways of hosting the site in order to try and figure out what is going on, to give you an indication, when hosting with either `webpack-dev-server` or `express` it seems to work as expected. However, when hosting [statically](http://pwa.simonfl3tcher.com/#/) or using `http-server` it decides to use Application cache instead of the Service worker.

### What does the config look like

My webpack.config.js file looks like so:

```
'use strict';

var webpack = require('webpack')
var FlowtypePlugin = require('flowtype-loader/plugin');
var OfflinePlugin = require('offline-plugin');

module.exports = {
  devtool: 'source-map',
  entry: {
    app: './src/App.jsx'
  },
  output: {
    path: __dirname + '/public/',
    filename: 'assets/[name].js',
    publicPath: '/'
  },
  resolve: {
    extensions: ['.js', '.jsx', 'css', 'scss']
  },
  resolveLoader: {
    modules: ['node_modules', __dirname + '/client/node_modules'],
    moduleExtensions: ['-loader']
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [
        ]
      },
      {
        test: /\.jsx?$/,
        loaders: 'babel-loader',
        exclude: /node_modules/,
        query: {
          cacheDirectory: true,
          presets: [
            'react',
            ['es2015', { "modules": false } ]
          ]
        }
      },
      {
        test: /\.css$/,
        use: [
          'style',
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]'
        ]
      },
      {
        test: /\.scss$/,
        use: [
          'style',
          'css?sourceMap',
          'sass?sourceMap'
        ]
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        use: [
            'file?hash=sha512&digest=hex&name=[hash].[ext]',
            'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
        ]
      }
    ]
  },
  plugins: [
    new FlowtypePlugin(),
    new OfflinePlugin({
      externals: ['index.html']
    })
  ]
}

if(process.env.NODE_ENV === 'production') {
    module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
  ])
}
```

### Screenshots

With `webpack-dev-server` or an Express server script:

<img width="1279" alt="screenshot 2017-02-23 09 22 07" src="https://cloud.githubusercontent.com/assets/1643158/23252678/a526f0e4-f9a9-11e6-9c23-c95982a186d9.png">

Statically hosted on S3 or running through `http-server`:

<img width="1280" alt="screenshot 2017-02-23 09 23 20" src="https://cloud.githubusercontent.com/assets/1643158/23252704/bd3f539c-f9a9-11e6-8fb6-4bcf4ebd77de.png">

### Links

I have uploaded the site to S3, you can visit it at [http://pwa.simonfl3tcher.com/](http://pwa.simonfl3tcher.com/)

**Comment by NekR** [comment]
You need https for ServiceWorker to work.

**Comment by NekR** [comment]
Okay, I think I should provide a bit more details. But first of all, again, your website must have `https://` to have ServiceWorker working.

The reason why it works on localhost because `localhost` and `127.0.0.1` are exception and are allowed to run ServiceWorker even without `https://`. `AppCache` is a fallback so in case when ServiceWorker isn't available it's being used. That's the case when you deploy the project to your production.

Everything else seems to be fine.

**Comment by simonfl3tcher** [comment]
@NekR thank you so much for clearing that up. I think I was struggling to understand why it works locally but when running on a different IP/S3 it was failing. I can confirm that once you get `https` running it does indeed use the service worker.
