### ISSUE TITLE
Service Worker install 127.0.0.1

### ISSUE THREAD

**Issue by thomaswelton** [NekR/offline-plugin#187]
I was running my site on 127.0.0.1 instead of localhost which caused this check to fail
https://github.com/NekR/offline-plugin/blob/0fffb644f273612e0b83bb944dd9a3e00689f3b7/tpls/runtime-template.js#L8

Can service workers be installed when running locally at 127.0.0.1?

**Comment by NekR** [comment]
@thomaswelton Yes, I believe `127.0.0.1` is just fine for ServiceWorker. PR is welcome for that :-)
