### ISSUE TITLE
Pass scope options to navigator.serviceWorker.register

### ISSUE THREAD

**Issue by xlc** [NekR/offline-plugin#19]
Currently my service worker script is located at `/web/scripts/sw.js` but I need it to cache some external files at `/images/` so I need to pass the scope `/` to [navigator.serviceWorker.register](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register).

We need to either pass `ServiceWorker.scope` to register or add a new options field for it.

This is my current implementation: https://github.com/KamiHQ/offline-plugin/commit/00ed09d21aad57dc35b593146132a4487fa2f807

**Comment by NekR** [comment]
Thanks! Tracking this to v3 release :+1:
