### ISSUE TITLE
Cache some ajax requests

### ISSUE THREAD

**Issue by hacke2** [NekR/offline-plugin#190]
How to config with offline-plugin if I want to cache some ajax request?

**Comment by NekR** [comment]
If you know those URLs in advance you can use `externals` option, like this:

```js
new OfflinePlugin({
  externals: ['/some-url']
})
```

if you don't know those URLs in advance then you will need to write some SW code manually since `offline-plugin` doesn't support it yet.

**Comment by NekR** [comment]
Let me know if you have other questions. Thanks.

**Comment by hacke2** [comment]
if my api url is 'https://api.xxx.com/user?id=1', The id is variable, How do I configure?

**Comment by NekR** [comment]
@hacke2 you cannot right now form configuration. You have to add `ServiceWorker.entry` and write a bit of its code manually to do so.

**Comment by hacke2** [comment]
Can you provide some demo? I see [the file](https://github.com/NekR/offline-plugin/blob/master/tests/legacy/fixtures/basic-with-sw-custom-entry/sw-entry.js) which file is empty.
