### ISSUE TITLE
Incorrect path of sw.js

### ISSUE THREAD

**Issue by DrakeLeung** [NekR/offline-plugin#191]
When I visit `mysite.com`, 
`sw.js` request path is `mysite.com/cdn.example.com/sw.js`,
However, `cdn.example.com/sw.js` is actually what i want.

What I found in bundle js file:

```js
// should be `//cdn.example.com/sw.js`??
navigator.serviceWorker.register("/cdn.example.com/sw.js")
```

webpack config:

```js
{
  publicPath: '//cdn.example.com',

  plugins: [
    new OfflinePlugin()
  ]
}
```

And *offline-plugin*'s version is: `^4.6.1`.

**Comment by NekR** [comment]
You cannot put ServiceWorker on CDN, it should be on your domain. You can put assets on CDN though, but they will have to served with correct CORS headers and you will have to adjust the config a bit for CDN.

**Comment by DrakeLeung** [comment]
Thanks I will try it. And close the issue if it works.
