### ISSUE TITLE
Events seems bugged when using Application Cache 

### ISSUE THREAD

**Issue by obetomuniz** [NekR/offline-plugin#192]
I'm trying to hit onInstalled, onUpdating, onUpdateReady and onUpdated to give feedbacks for my users after the installation of the cache ends, but it just works in browsers that support SW. Any way to make it usable in browsers that support just Application Cache? (e.g. Safari)

The project is [here](https://github.com/minasdev/minasdev.org).

**Comment by GGAlanSmithee** [comment]
Not sure why, but from `updates.md`:

> AppCache's events are buggy and unstable and some times may not fire at all.

**Comment by obetomuniz** [comment]
Hey, thanks! 

I saw this section there @GGAlanSmithee I just want to understand why are buggy and if you guys have some good proposal to enable these events using some outside approach.

**Comment by NekR** [comment]
https://github.com/NekR/offline-plugin/issues/140

**Comment by NekR** [comment]
Other than that, AppCache events should work at least "fine". They work for me here: https://offline-plugin.now.sh/

**Comment by obetomuniz** [comment]
Great @NekR Thanks for the resources. I'll take a look to try figure out if I'm doing something wrong or are the same things reported for you in #140

**Comment by GGAlanSmithee** [comment]
@NekR want a summary of that explanation you provided in #140 in the docs?

**Comment by NekR** [comment]
@GGAlanSmithee Yeah, would be good if you want to do so :-)

**Comment by NekR** [comment]
@obetomuniz sure, feel free to ask other questions if something.

**Comment by obetomuniz** [comment]
Nice! Thanks @NekR
