### ISSUE TITLE
Cache Invalidation

### ISSUE THREAD

**Issue by zackify** [NekR/offline-plugin#197]
Sorry if this has been asked before, but I'm trying to figure out the best way to push new releases and have the service worker be updated. 

Right now, I upload all of webpack's output to S3 and then serve it through cloudfront. All outputted files have a hash in front of them, except the sw is always the same filename.
 
Should I simply make it so that the serviceworker has a hashed filename as well, or make it so that it is never cached so that any page load grabs the latest version of it? I hope this makes sense.

**Comment by NekR** [comment]
Hi, @zackify!

Short version:
Never cache SW file. Don't change its name, i.e. don't hash it.

Long version:
https://github.com/NekR/offline-plugin/issues/127 -- You'll need to read whole thread to understand all the details.

:-)

**Comment by NekR** [comment]
(I hope that's correct thread, I believe it is)

**Comment by zackify** [comment]
Yes, I have this working perfectly. On AWS I never cache it, and auto update every two minutes and reload my app. Btw this is super fast on the reload since it's after the new worker caches everything! Love this plugin :)

**Comment by NekR** [comment]
> Love this plugin :)

😎

**Comment by ndbroadbent** [comment]
@NekR Thanks for the explanation, here as well as #127. It makes sense why you don't want to add a hash to the service worker JS filename.

I'll treat this file like my `index.html`, where I purge the Cloudflare cache after uploading to S3.

**Comment by NekR** [comment]
@ndbroadbent that's probably okay, I'm not sure actually. Let us know if works or not for you 👍
