### ISSUE TITLE
why offline-plugin couldn't throw the secure origins error?

### ISSUE THREAD

**Issue by hacke2** [NekR/offline-plugin#199]
If I code sw.js by myself, The browser will throw a error: 'Uncaught (in promise) DOMException: Only secure origins are allowed (see: 'https://goo.gl/Y0ZkNV')，I know my site isn't 'https',but the offline-plugin couldn't throw the error, why?

**Comment by NekR** [comment]
Why would it? It's smart enough to not even try to register SW if website isn't HTTPS. It fallbacks to AppCache (if enabled) in non-HTTPS case.

**Comment by hacke2** [comment]
get it, thanks!
