### ISSUE TITLE
On initial load fetch latest assets for user who has already visited website

### ISSUE THREAD

**Issue by vrpruthvi** [NekR/offline-plugin#202]
Thanks for the great plugin. I'm new to SW, wanted to ask a quick question:

Consider a user who has already visited opens website after a few days. Initially old assets from SW will be loaded and then latest assets will be downloaded in the background. Once new version is downloaded an update dialog can be shown to user.

I think its apt to show dialog box for user who is active on site for a while.(using **autoUpdate** feature)

I find it strange in showing the dialog to the user who is visiting after long time, completed a initial webpage load and then showing update dialog to refresh page again. Is it possible to load the latest version for these users?

I have read through docs and couldn't find anything related to this. Let me know if I'm missing something.

**Comment by NekR** [comment]
Just apply update without dialog and reload the page.

**Comment by NekR** [comment]
I wrote that assuming you already know how to handle `offline-plugin` events and already showing a dialog to the users. So pretty much you just need to detect your case somehow (user came back after some time) and just reload the page after update.

**Comment by vrpruthvi** [comment]
Thanks for the reply. I tried what you have mentioned earlier and found that page refreshes twice. Can it be possible to do in a single reload?

**Comment by NekR** [comment]
Nope. It has to update and then reload to has the update to take effect. When users load page they just load it from the cache, so not possible in one load.

You may try to set `responseStrategy: 'network-first'`, in this case all requests first will be trying to get content from the network and if that fails, they will fallback to the cache.

**Comment by vrpruthvi** [comment]
Cool, I will try that out. Thanks for helping out!

**Comment by vrpruthvi** [comment]
@NekR `responseStrategy: 'network-first'` is what I was looking for! works like a charm :)

**Comment by NekR** [comment]
Great :-)
