### ISSUE TITLE
Add an option to uglify

### ISSUE THREAD

**Issue by jameslnewell** [NekR/offline-plugin#204]
Hi,

I'm using `babili-webpack-plugin`, not `webpack.optimize.UglifyJsPlugin` to minify my JS (because `babili` supports ES6 left untranspiled by `babel-preset-env`). Could we add an option to turn minification on?

**Comment by NekR** [comment]
Okay, that makes sense. See my review :-)

**Comment by NekR** [comment]
Closed in #206.
