### ISSUE TITLE
no cache or service worker file  created

### ISSUE THREAD

**Issue by simran66** [NekR/offline-plugin#209]
I am trying to use offline plugin. The options look amazing.I am using React ,SSR with webpack. 

But no service worker gets created.

I have tried in both development and production mode. I am using this https://github.com/erikras/react-redux-universal-hot-example boilerplate. I have added offline plugin in webpack config.
and

  ```
OfflinePluginRuntime.install({
onUpdating: () => undefined,
  onUpdateReady: () => OfflinePluginRuntime.applyUpdate(),
 onUpdated: () => window.location.reload(),
   onUpdateFailed: () => undefined,
});

```

this code in index.js but it does not seem to work. No errors but no service worker or application cache is created.Am I missing out on something?

**Comment by NekR** [comment]
Hi @simran66, it's really hard to tell if you missed something or not. It sounds like you did everything right.

* Before `OfflinePluginRuntime.install()` do you do `var OfflinePluginRuntime = require('offline-plugin/runtime')`?
* Can you share your webpack config?

**Comment by simran66** [comment]
@NekR : Hey, Thanks for your response..

Yes, I required it before calling install.

This is what my webpack looks like:


`require('babel-polyfill');

// Webpack config for development
var fs = require('fs');
var path = require('path');
var webpack = require('webpack');
var assetsPath = path.resolve(__dirname, '../static/dist');
var host = (process.env.HOST || 'localhost');
var port = (+process.env.PORT + 1) || 3001;
//import CodeSplitWebpackPlugin from 'code-split-component/webpack';


// https://github.com/halt-hammerzeit/webpack-isomorphic-tools
var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');
var webpackIsomorphicToolsPlugin = new WebpackIsomorphicToolsPlugin(require('./webpack-isomorphic-tools'));

var babelrc = fs.readFileSync('./.babelrc');
var babelrcObject = {};
var ManifestPlugin = require('webpack-manifest-plugin');


try {
  babelrcObject = JSON.parse(babelrc);
} catch (err) {
  console.error('==>     ERROR: Error parsing your .babelrc.');
  console.error(err);
}


var babelrcObjectDevelopment = babelrcObject.env && babelrcObject.env.development || {};

// merge global and dev-only plugins
var combinedPlugins = babelrcObject.plugins || [];
combinedPlugins = combinedPlugins.concat(babelrcObjectDevelopment.plugins);

var babelLoaderQuery = Object.assign({}, babelrcObjectDevelopment, babelrcObject, {plugins: combinedPlugins});
delete babelLoaderQuery.env;

// Since we use .babelrc for client and server, and we don't want HMR enabled on the server, we have to add
// the babel plugin react-transform-hmr manually here.

// make sure react-transform is enabled
babelLoaderQuery.plugins = babelLoaderQuery.plugins || [];
var reactTransform = null;
for (var i = 0; i < babelLoaderQuery.plugins.length; ++i) {
  var plugin = babelLoaderQuery.plugins[i];
  if (Array.isArray(plugin) && plugin[0] === 'react-transform') {
    reactTransform = plugin;
  }
}

if (!reactTransform) {
  reactTransform = ['react-transform', {transforms: []}];
  babelLoaderQuery.plugins.push(reactTransform);
}

if (!reactTransform[1] || !reactTransform[1].transforms) {
  reactTransform[1] = Object.assign({}, reactTransform[1], {transforms: []});
}

// make sure react-transform-hmr is enabled
reactTransform[1].transforms.push({
  transform: 'react-transform-hmr',
  imports: ['react'],
  locals: ['module']
});

module.exports = {
  devtool: 'inline-source-map',
  // node: {
  //   fs: "empty"
  // },
  target: "node",
  entry: {
    'main': [
      'webpack-hot-middleware/client?path=http://' + host + ':' + port + '/__webpack_hmr',
      'font-awesome-webpack!./src/theme/font-awesome.config.js',
      './src/index.js'
    ]
    // ,
    // vendor: ['react', 'react-lazy-load', 'react-redux', 'react-id-swiper', 'redux', 'react-router',
    //   'react-dom']
    //,
    //'OrderTracking':'./src/components/OrderTracking/OrderTracking.js'
  // 'CatalogPage' : './src/components/catalog/ProductContainer.js'
  },
  output: {
    path: assetsPath,
    chunks: true,
    // filename: '[name]-[hash].js',
    // chunkFilename: '[chunkhash].js',
    chunkFilename: "chunk_[chunkhash].js",
    filename: "[name]_[hash].js",
    publicPath: 'http://' + host + ':' + port + '/dist/'
  },
  module: {
    loaders: [
      { test: /\.jsx?$/, exclude: /node_modules/, loaders: ['babel?' + JSON.stringify(babelLoaderQuery), 'eslint-loader']},
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.css$/, loader: 'style-loader!css-loader'},
      { test: /\.less$/, loader: 'style!css?importLoaders=2&sourceMap!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap' },
      { test: /\.scss$/, loader: 'style!css?importLoaders=2&sourceMap&!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap' },
      { test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
      { test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
      { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
      { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" },
      { test: webpackIsomorphicToolsPlugin.regular_expression('images'), loader: 'url-loader?limit=10240' }
    ]
  },
  progress: true,
  resolve: {
    modulesDirectories: [
      'src',
      'node_modules'
    ],
    extensions: ['', '.json', '.js', '.jsx']
  },
  plugins: [
    // hot reload
    new webpack.HotModuleReplacementPlugin(),
    // new webpack.optimize.CommonsChunkPlugin({
    //   name: 'vendor',
    //   filename: 'vendor.js',
    //   minChunks: Infinity
    // }),
    new webpack.NamedModulesPlugin(),
    new webpack.IgnorePlugin(/webpack-stats\.json$/),
    new webpack.optimize.AggressiveMergingPlugin(),
   // new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"vendor", /* filename= */"vendor.bundle.js"),


    //new CodeSplitWebpackPlugin(
      //{
     // disabled: process.env.NODE_ENV === 'development',
   // }
//),
    new webpack.DefinePlugin({
      __CLIENT__: true,
      __SERVER__: false,
      __DEVELOPMENT__: true,
      __DEVTOOLS__: true  // <-------- DISABLE redux-devtools HERE
    }),
    webpackIsomorphicToolsPlugin.development()
  ]
};`

**Comment by NekR** [comment]
hmm.. I don't know to be honest, everything seems fine and it should generate ServiceWorker/AppCache files.

**Comment by NekR** [comment]
I'm going to close this until we have more info about this situation or a repro.

**Comment by sidhantpanda** [comment]
I'm using the plugin like this in the same boilerplate by @erikras

```javascript
new OfflinePlugin({
  safeToUseOptionalCaches: true,

  externals: [
    '/'
  ],

  caches: 'all',

  ServiceWorker: {
    // publicPath: '/sw.js',
    events: true,
    // navigateFallbackURL: '/'
  },
  AppCache: {
    events: true
  }
})
```

The service worker is getting registered but the app does not load in offline mode:

![Lighthouse screenshot](https://cdn.pbrd.co/images/PZTNAOZ24.png)

The logs show that the assets were cached:

![Console log](https://cdn.pbrd.co/images/Q020aWlvs.png)

@simran66 Please let me know if you happened to find a fix.

**Comment by simran66** [comment]
I did . The problem is scope of the service worker. We are creating service
worker in dist folder. Make it in static folder instead and register and
serve it from there. That will do the trick.

**Comment by sidhantpanda** [comment]
@simran66 Only the service worker or all the assests? Can you share your webpack config file please?

**Comment by simran66** [comment]
only the service worker. yeah.sharing in 5

**Comment by GGAlanSmithee** [comment]
@NekR the scope issue seems to come up fairly often, maybe we should add a bit of info about it in the FAQ section of the docs. Would you like a PR?

**Comment by NekR** [comment]
@GGAlanSmithee Yes, PR would be great. Although I'm not sure if people will be able to find the answer unless they you what they are looking for. Maybe we should create another document, e.g. _ServiceWorker isn't working_ or _`offline-plugin` ins't working_ and list all possible issues there so they could try one-by-one until something helps them. What do you think?

**Comment by GGAlanSmithee** [comment]
@NekR That's a great idea! Should be very "googelable" :) I will try to make a initial PR regarding that.

**Comment by NekR** [comment]
@GGAlanSmithee sounds great, thank you Alan! (no need to rush if something)

**Comment by sidhantpanda** [comment]
@GGAlanSmithee sounds good! 
@simran66 can you share the config please?
