### ISSUE TITLE
Network strategies

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#21]
Consider adding different network strategies to `ServiceWorker` https://jakearchibald.com/2014/offline-cookbook/#serving-suggestions-responding-to-requests

Should it be allowed only when `AppCache` isn't used? Should it automatically disable `AppCache`?

**Comment by MoOx** [comment]
https://github.com/GoogleChrome/sw-toolbox might help here.

**Comment by NekR** [comment]
@MoOx I know, but this was related to cache of webpack generated assets, which isn't written with library. 

You can already use `sw-toolbox` with this plugin if you want, here is very simple example: https://gist.github.com/NekR/06210fc9dea3a9f7850c1f89c9e5dcb5

**Comment by NekR** [comment]
Fixed here: https://github.com/NekR/offline-plugin/pull/112

I someone would want more control about network/response strategies, please open new issue.
