### ISSUE TITLE
service worker failing on localhost with webpack

### ISSUE THREAD

**Issue by simran66** [NekR/offline-plugin#213]
I have added this plugin 

```

    new OfflinePlugin({
      ServiceWorker: {
        events: true
      }
    })
```

in my production webpack config.

in index.js

```
OfflinePluginRuntime.install({
  onUpdating: () => {
    console.log('SW Event:', 'onUpdating');
  },
  onUpdateReady: () => {
    console.log('SW Event:', 'onUpdateReady');
    // Apply update when available
    OfflinePluginRuntime.applyUpdate();
  },
  onUpdated: () => {
    console.log('SW Event:', 'onUpdated');
    // Reload immediately when updated
    window.location.reload();
  }
});
```

I am using react with server side rendering. On service worker installation step, it fails:

Operation has failed. Unknown reason.

In warnings, I see

Long running javascript task took 507 ms.

In debug I see:

Service Worker termination by a timeout timer was canceled because DevTools is attached.

How do I fix this? How is one really supposed to debug a SW?

Please suggest a fix. My sw.js is getting created just fine but fails to install.

I am running on localhost so ofcourse do not have https. Could that be a reason?> I believe it should work on localhost without https.

**Comment by tkh44** [comment]
ServiceWorker will only work over https.

**Comment by simran66** [comment]
@tkh44 : Even on localhost? How do I set https up on localhost? Ofcourse I need to test service worker functionality and write some code

**Comment by NekR** [comment]
On `localhost` and `127.0.0.1` it works without https.

**Comment by NekR** [comment]
@simran66 how do you know that it's ServiceWorker failing and not something else? Why do you think it isn't being installed? 

Also, please, provide a repro. If you cannot provide a live repro website, then a github repo with reproduction would work too.

**Comment by tkh44** [comment]
@NekR sorry, I stand corrected.

**Comment by simran66** [comment]
@NekR : I thought so because It shows "installing" in service worker and then starts showing that error. Other than that, service worker events are never really triggered

**Comment by NekR** [comment]
@tkh44 hey, no problem :-) Just corrected it to remove the confusion.

**Comment by NekR** [comment]
@simran66 where does it show that error? In console? In DevTools -> Application -> ServiceWorker?

**Comment by simran66** [comment]
@NekR : That's right. Right there

**Comment by NekR** [comment]
Okay, that error is Chrome specific error which is thrown when something wrong happens with ServiceWorker. I have no idea what exactly. It might be even related only to your specific Chrome installation.

Anyway, please, provide a repro, I said that a lot of times already. I cannot guess and magically fix things for you, so no repro -- no issue. Sorry.

**Comment by NekR** [comment]
Okay, I'm closing this. If you really want to solve it, then prepare a reproduction. Thanks.

**Comment by jeffposnick** [comment]
FYI, I've seen some other reports of general service worker installation failures in Chrome, unrelated to `offline-plugin`. Feel free to follow https://bugs.chromium.org/p/chromium/issues/detail?id=706491

**Comment by NekR** [comment]
@jeffposnick Yeah, here https://github.com/NekR/offline-plugin/issues/215 is another issue by hero where she explains it in more details. Something with her Chrome installation, maybe current db/cache/file system. It just doesn't work there for any website.

**Comment by NekR** [comment]
@jeffposnick and of course thanks for sharing url to the bug :-)
