### ISSUE TITLE
Question: multiple html payload entrypoints

### ISSUE THREAD

**Issue by jeromecovington** [NekR/offline-plugin#224]
First of all thanks very much for your work on this.

My app currently does not have an ideal architecture, but I'm wondering if there is a way to continue to use `offline-plugin` regardless. It is not a SPA or app shell architecture, something I am actively working on as well.

At the point of this writing however, we can assume that the server sends static markup for the following three kinds of endpoints:
`/` (homepage)
`/post/:slug` (article or post)
`/gallery/:slug` (gallery)

Service worker is at `/sw.js`.

I am able to capture all webpack assets _and_ the homepage html payload with the service worker, and re-serve them when offline, with the following configuration:
```
new OfflinePlugin({
  // ...
  externals: [
    '/'
  ]
})
```

I have tried adding additional matches for the other two html payload types, as follows, to no avail:
```
externals: [
  '/',
  '/post/*',
  '/gallery/*'
]
```

I have also attempted to add these as `':externals:'` to the `optional` property of the `caches` configuration. However, this also does not work as I am hoping.

Any possible guidance on this unconventional (and less that ideal) problem? I'd like to see if I can get this working, in parallel with my app shell refactoring, so that one is not dependent on the other.

**Comment by NekR** [comment]
Hi! I think you architecture is just fine, that's how normal websites are done.
Problem here is that `offline-plugin` doesn't yet support caching of dynamic URLs. Everyone actually asks about that feature, but unfortunately it isn't done. 

What you can do here is add `ServiceWorker.entry` option and implement such caching manually. Essentially it's just listening to `fetch` event and responding from cache or not based on request url.

**Comment by jeromecovington** [comment]
Ha ha, thanks. I'll give that a shot.

**Comment by jeromecovington** [comment]
I'm digging through closed issues as well. Will continue to do so as well as learn better the internals. However if you can think of any examples at some point, please share! Thanks again.

**Comment by NekR** [comment]
@jeromecovington I think you may found something useful in this issue: https://github.com/NekR/offline-plugin/issues/64

**Comment by jeromecovington** [comment]
Yeah, the older issues are giving me a lot to work with. I'll close this and open follow up issues if need be. Thanks.

**Comment by NekR** [comment]
Sure :-)
