### ISSUE TITLE
is this only for webpack?

### ISSUE THREAD

**Issue by filipveschool** [NekR/offline-plugin#225]
Hi @NekR , 

Is this also possible to use with browserify compiling?

I am doing my internship now and am using reactboilerplate which uses your plugin for offline support.

But they are using webpack and my company wants me to use browserify :(.

Is this compatible somehow or not?

I hope you can help me please.

Sincerely

Filip

**Comment by NekR** [comment]
Hi Flip. Unfortunately, yes, it's only for webpack. But why they want you to use exactly browserify and not something else? I suppose you'll have hard times porting everything from reacts boilerplate to browserify.

**Comment by filipveschool** [comment]
@NekR I know and I wanna use webpack also, but they only know browserify and instead of learning webpack they want to make it difficult for me apparently :(.

I am doing my internship in new zealand and those people are very friendly and so on but also very stubborn about everything.

So yeah, dont know what to do now. :(

**Comment by NekR** [comment]
> @NekR I know and I wanna use webpack also, but they only know browserify and instead of learning webpack they want to make it difficult for me apparently :(.

Yeah, it's very sad.

> So yeah, dont know what to do now. :(

I think you may want/need to use [`sw-precache`](https://github.com/GoogleChrome/sw-precache) in case of browserify. `sw-precache` is independent from a build tool you're using, just run it against generated files and that should be it :-)

**Comment by filipveschool** [comment]
@NekR oke will try it. Hopefully it works. Because with your tool and reactboilerplate the whole project is almost finished and it actually works offline. But I just dont know why they are doing so stupid but yeah what can I do as intern? :(

**Comment by NekR** [comment]
> yeah what can I do as intern? :(

Good developer should be able to convince others to use the tool he/she likes, otherwise, what's the point, right? 😄 😇
