### ISSUE TITLE
Follow up: caching arbitrary externals (html payloads)

### ISSUE THREAD

**Issue by jeromecovington** [NekR/offline-plugin#226]
I spent a good amount of time digging into prior issues, certain I would find what I needed, and so I closed https://github.com/NekR/offline-plugin/issues/224

However I still seem to be having trouble caching externals (the html payload for the specific page).

To be clear, the server handles the parsing of all parts of the path in order to extract the various parameters for deriving the data to send in the HTML payload.

So, for example the following URLs would all need their individual, specific payloads cached, rather than doing any matching and correlating to `cachMaps`.

`/`
`/article/foo`
`/article/bar`
`/article/baz`
`/gallery/foo`
`/gallery/bar`
`/gallery/baz`

Again, I seem to be having no issues deriving all of the webpack generated assets, and also the homepage, defined as `externals: [ '/' ]`. I feel like if I could define [`Client.url`](https://developer.mozilla.org/en-US/docs/Web/API/Client/url) as the external, that would sort this out just fine, but I can't seem to figure out how to do so.

One more slight leap in understanding for me and I will be well on my way to a fully functioning offline app.

Thanks again for your work on this, and for helping me in my understanding so far!

**Comment by NekR** [comment]
HI @jeromecovington!

Here is an example (I already pointed you to it): https://github.com/NekR/offline-plugin/issues/64#issuecomment-223949743

**Comment by jeromecovington** [comment]
Ah! Of course I lost track of that during my side trip into the `cacheMaps`, a custom entry point does seem helpful. Thanks.
