### ISSUE TITLE
Question: how do we display a message if the content is stale?

### ISSUE THREAD

**Issue by rstacruz** [NekR/offline-plugin#227]
I'd like to display a message something like:

> A new version of MyApp is available. _Click here_ to reload.

Is there an API I can take advantage of?

**Comment by NekR** [comment]
https://zach.codes/handling-client-side-app-updates-with-service-workers/

**Comment by NekR** [comment]
Here are more info about events if something: https://github.com/NekR/offline-plugin/blob/master/docs/runtime.md#install-options

**Comment by rstacruz** [comment]
Neat! That'd make a good addition to the FAQ. :+1:

**Comment by NekR** [comment]
Yeah, good idea :-)

**Comment by NekR** [comment]
I already created issue for it: https://github.com/NekR/offline-plugin/issues/228 (will consider adding mention about it to the FAQ too)
