### ISSUE TITLE
RegExp in caches doesn't work

### ISSUE THREAD

**Issue by HelloDeadline** [NekR/offline-plugin#238]
When I pass an array of regular expressions, for example:

```
caches: {
      main:  [ /app.*.js/, /vendor.*.js/, /style.*.css/] 
  },
```
I get: `TypeError: cacheKey.indexOf is not a function`  
It seems like the problem is `at OfflinePlugin.setAssets (%projectpath%\node_modules\offline-plugin\lib\index.js:447:11)`

I tried to remove `cacheKey.indexOf('./') !== 0` from source code, but then I got `TypeError: glob pattern string required`  which comes from `_miscUtils.hasMagic`.

Similar glob patterns work fine. 

I use Webpack 2 on Windows 7, I could test same configuration on Linux Mint if needed.

**Comment by NekR** [comment]
That feature is not in v4. It will be in v5: https://github.com/NekR/offline-plugin/issues/234

**Comment by HelloDeadline** [comment]
@NekR oh, okay, I didn't notice #234. It seems like updates to docks were merged before v5 release

**Comment by NekR** [comment]
@HelloDeadline yeah, it's a bit of a mess :-(
