### ISSUE TITLE
Documentation: Fetch external

### ISSUE THREAD

**Issue by christoferw** [NekR/offline-plugin#244]
Hi There!

its not clear for us when externals will be refreshed.

e.g. we have configured:

`            externals: [
                '/users',
				'http://code.jquery.com/jquery-latest.min.js',
				'https://fonts.googleapis.com/css?family=Titillium+Web:400,800'
            ],`

/users is used to get the json-list of users. When i add a users to that list(e.g in a backend) when will the offline-plugin fetch the new /users? is there somthing to do this:

"if data is older then xxx fetch new data, if fetch failed, uses cache anyway".

**Comment by NekR** [comment]
Externals are fetched at the same time as main cache, i.e. on ServiceWorker/AppCache update. There is no TTL for caches, but I wouldn't recommend to cache users data like that. You did better use `window.caches` directly form your main code and cache/update when it's needed. This way  you will have more control.

Also about Google Fonts: it caches only stylesheet that way, not the fonts itself.

**Comment by christoferw** [comment]
When does the ServiceWorker/AppCache update, when the manifest-file changes? e.g. Version change?

**Comment by NekR** [comment]
Right.
