### ISSUE TITLE
Check for update before rendering page

### ISSUE THREAD

**Issue by andylhansen** [NekR/offline-plugin#245]
Is it possible for the service worker to check for an update before the page renders? I'd like to avoid the double page load if possible.

For example:
User visits web app.
User leaves web app.
I push update.
User comes back to web app.
User first sees cached version, then after a few seconds, the service worker finds and applies an update, refreshing the page.

It would be nice for the user if there wasn't a refresh a few seconds after they logged in after an update.
responseStrategy: 'network-first' seems to work, except that overall performance of the web app is decreased because each individual asset is first queried from the network. I'd rather just prevent the page from rendering on initial page load until it has been determined whether an update has occurred. Is there a way to achieve this?

**Comment by NekR** [comment]
It isn't possible with SW, but what are the benefits of such way? What should happen if SW indeed needs a update, wait for all assets to download before showing anything?

**Comment by andylhansen** [comment]
The benefit would be that the user wouldn't see a refresh after the app has already rendered. If the SW needs an update, then it would wait for all the assets to download before rendering the app.

**Comment by NekR** [comment]
> If the SW needs an update, then it would wait for all the assets to download before rendering the app.

That would very poor user experience. Unless you have like 1-2 files in main cache.
Anyway, this isn't possible with SW, so I'm closing this. But if you are filling to discuss this further -- feel free too.

**Comment by NekR** [comment]
Also you best bet on updating right now is this: [Handling Client Side App Updates (with Service Workers)](https://zach.codes/handling-client-side-app-updates-with-service-workers/)
