### ISSUE TITLE
files are listing with out the hash tag

### ISSUE THREAD

**Issue by pavankumarkatakam** [NekR/offline-plugin#25]
Actually for cache busting im using the webpack hash tag for every generate entry point. but the generate sw doeesnt have the hastag i.e., when my webpack generate file is `main.js?78787827878` but sw listed it as only `main.js` this should be problematic when second time loading the site.

**Comment by NekR** [comment]
@pavankumarkatakam You are right, it's a bad thing. Unfortunately, currently there is no right way to deal with it, but I am currently working on a next version (`v3` branch, not usable yet) where will be implemented automatic cache busting.

**Comment by NekR** [comment]
Okay, I just pushed an update to `v3` branch. It's still unstable, but now you can try it (**do not  use `changed` update strategy yet**)

First of all, it now automatically adds cache-bust params to all requests. It looks like this `http://localhost:8080/?__uncache=v3_2016-03-20%2011%3A13%3A05` and depends on what `updateStrategy` you are using.

Seconds is that SW is now always uses `ignoreSearch` mode, so you do not have to have same request params in HTML and inside SW. So if your requests in HTML looks like this `main.js?78787827878` it must be fine and they will catch latest version from SW anyway.

Also, you can try to play with `rewrites` option to rewrite names of your assets to `main.js?78787827878`, but as I said there is no way to disabled built-in cache-busting params passing.

**Comment by NekR** [comment]
Also full CHANGELOG is here: https://github.com/NekR/offline-plugin/blob/v3/CHANGELOG.md

**Comment by pavankumarkatakam** [comment]
Hi @NekR , I just checked that now the hash tags are appending, issue is cleared. And on thing i want to know that is there any relation for this plugin and google [sw-precache](https://github.com/GoogleChrome/sw-precache).

**Comment by NekR** [comment]
`sw-precache` and `sw-toolbox` are cool tools for SW, they are developer by Google engineers so you may expect high quality there. About relation, there is no relation except that both `offline-plugin` and `sw-precache` are tools for ServiceWorkers. While `offline-plugin` is focused on a `webpack` (because I use it), `sw-precache` is focused on a more general use, i.e. with `gulp`.

/cc @jeffposnick

**Comment by pavankumarkatakam** [comment]
Hi @NekR , in `sw-precache` there are three strategies like `cache-first` and `network-first`, so my question is how you are building the `sw.js` using which strategy

**Comment by NekR** [comment]
`cache-first`
