### ISSUE TITLE
Is not found in the output assets

### ISSUE THREAD

**Issue by Khachatour** [NekR/offline-plugin#252]
Hey there folks!
I am fairly new to this plugin and webpack overall.

I am getting these error 

`OfflinePlugin: Cache asset [../index.html] is not found in the output assets,if it's an external asset, put it to the |externals| option to remove this warning
`
What am I doing wrong? Giving wrong paths in main section ? 
Can someone suggest any help ? 
Thanks in advance.

**Comment by GGAlanSmithee** [comment]
As the error message suggests, the asset `index.html` is not generated by webpack. (It's probably a static html page, right?)

To fix this error, add the asset to the [externals option](https://github.com/NekR/offline-plugin/blob/master/docs/options.md#externals-arraystring) as the error message suggests.

If the error persists, please post your webpack config here.

**Comment by Khachatour** [comment]
@GGAlanSmithee oh thanks just a 5 minutes ago I've found that out, so in assets section can I specify file with .vue extension ?

**Comment by NekR** [comment]
In `caches` you reorder already generated assets and historically you're able to specify external URLs there. It's better to not touch `caches` section at all unless you really need it. Use `externals` instead to specify URLs to cache.

If .vue file is an URL, you can specify it. If it's a generated file, then it's already added to `caches` automatically.

**Comment by Khachatour** [comment]
@NekR Thank you very much for the help!

**Comment by NekR** [comment]
Sure 👌
