### ISSUE TITLE
Page is reloading automatically 

### ISSUE THREAD

**Issue by Khachatour** [NekR/offline-plugin#253]
After running a server my page is rapidly reloading itself, what could be a reason ? 
Can someone suggest a solution ? 
Sorry, I am fairly new to webpack and this awesome plugin.
Thanks in advance.

**Comment by NekR** [comment]
Hi @Khachatour. I actually don't know, but it might be because you have "Update on reload" set in your DevTools and also using `offline-plugin`'s events to reload the page. So it gets into the loop.

**Comment by Khachatour** [comment]
@NekR Oh thanks I think I've screwed that part. Thank you!! Will fix
