### ISSUE TITLE
Prefetching js chunks

### ISSUE THREAD

**Issue by pmadar** [NekR/offline-plugin#255]
Does offline plugin with default config prefetch all js files automatically? For example if my app is split to multiple chunks by routes, does all other than actual route's chunk be prefetched?
I tested it with several configs but, it didn't work as I want. Still have to wait for fetching chunks when navigating.

**Comment by NekR** [comment]
Hi @pmadar. Yes, by default it prefetched everything what was generated by webpack.

I'm not sure what issue you have here, but let's try to figure it out. Are you sure SW is being installed/registered at all? What does Chrome DevTools' `Application` Tab says?

**Comment by pmadar** [comment]
Here is what i see in console: 
![image](https://cloud.githubusercontent.com/assets/13347558/26091844/078be498-3a0e-11e7-871c-bdf58e4c03de.png)
Application:
![image](https://cloud.githubusercontent.com/assets/13347558/26091860/234e40b8-3a0e-11e7-85b6-42251e24a66c.png)

**Comment by NekR** [comment]
@pmadar maybe you have to fail for the `.html` file to load? Because you don't cache any of it.

**Comment by pmadar** [comment]
@NekR I dont have html generated by webpack, it's rails app.
Thanks for your help, seem to be my issue. I'll try to figure it out on my own, I have just one question to make it completely clear. Should offline-plugin prefetch and load all js chunks asynchronously after loading main js file?

**Comment by NekR** [comment]
What do you mean "should"? If it's configured to, it will do it.

**Comment by pmadar** [comment]
Ok thank's, I meant if it's capable of...

**Comment by NekR** [comment]
I'm still not sure what exactly you mean, but `offline-plugin` caches all webpack generated assets, unless you specify otherwise. If you'll have any other question let me know.
