### ISSUE TITLE
Extending networkFirstResponse

### ISSUE THREAD

**Issue by kikoanis** [NekR/offline-plugin#257]
I am trying to cache all responses before returning them. Something similar to this
```
        const responseToCache = response.clone()

        // Otherwise cache the downloaded files
        caches.open(CACHE_NAME)
          .then((cache) => {
            cache.put(event.request, responseToCache)
          })
```

Not sure if there is anyway to extend networkFirstResponse method in sw-template to accommodate the code above. 

Great plugin BTW

**Comment by NekR** [comment]
> Great plugin BTW

Thanks!

@kikoanis I'm not 100% sure what you're trying to do here. `offline-plugin` doesn't re-cache downloaded file in `networkFirstResponse` for a reason. If it would do so, you may end-up with cache mismatch where some files will be from one version and some from another. And that isn't good.

**Comment by kikoanis** [comment]
Oh so what you mean is that the networkFirstResponse method (and the corresponding cacheFirstResposne) are for when you visit a URL directly and not for any consecutive requests (Within SPA context). 

I think now I have an idea on how to do this using the entry item in serviceWorker node by trying to query network first and if it fails then we go for the cache. If it succeeds then we try to cache it for furture failing networks. 

Network first obviously is not always recommended for static files I guess but for my purpose is for API requests and the like.

This leads me to my next question for how to implement two (or more) different strategies based on some filtering criteria or that is not possible within the current code.

**Comment by NekR** [comment]
I'm still not 100% sure what you mean :-) 

> are for when you visit a URL directly and not for any consecutive requests 

ServiceWorker handles all, whatever requests. What I meant is that it doesn't update the cached assets when it downloads a new one in `networkFirstResponse`. And you shouldn't do that. 

Yes, there is no filters right now. Response strategy is for all assets.

**Comment by kikoanis** [comment]
> What I meant is that it doesn't update the cached assets when it downloads a new one in 
networkFirstResponse. And you shouldn't do that

This is new to me. May I ask why I should not do that?.

I think I should have put more explanation into what I am after.

As part of full offline experience for users is to cache API responses so that users when they navigate from one URL to another would see previous content (fully) if they already visited them. I use the entry item in the serviceWorker node in your plugin for that.

Now, when I edit some items in my site, I expect when I save and go to the display part of that item I would expect the new content that I last saved. But that is was not the case. I found out that the reason for that is because I used Cache first. Now If I do not use the entry item and use network first strategy nothing happens and I would not see any cached API responses. That is why I was asking to extend it to cache responses.

Hope this makes sense to you now :-)

**Comment by NekR** [comment]
> May I ask why I should not do that?.

I answered that already in my first comment here:

> `offline-plugin` doesn't re-cache downloaded file in `networkFirstResponse` for a reason. If it would do so, you may end-up with cache mismatch where some files will be from one version and some from another. And that isn't good.

**Comment by NekR** [comment]
> Now, when I edit some items in my site, I expect when I save and go to the display part of that item I would expect the new content that I last saved. But that is was not the case. I found out that the reason for that is because I used Cache first. Now If I do not use the entry item and use network first strategy nothing happens and I would not see any cached API responses. That is why I was asking to extend it to cache responses.

I see now. Okay, so that suggestion about "don't do that because that hurts cache and makes version mismatch" is related to scripts/css, i.e. to wepback generated content. If you are doing it with your API requests then that's fine.

Your problem is tough and there isn't really "right" solution for it. You either has to do 2 parallel request: one to cache and one to the network and then decide which one to use or when to store network response to the cache. Or you may try networkFirst approach and update cache when network response arrives, this is what your are trying to do apparently. But why you're trying to do that with the code from the `offline-plugin`'s ServiceWorker?

**Comment by kikoanis** [comment]
> But why you're trying to do that with the code from the offline-plugin's ServiceWorker?

This implies I should not extend the code if it only caches static file. I think the ```entry``` item would suffice for my case. 

> You either has to do 2 parallel request

Not sure about two parallel processes but I think what I should do is to only target responses that are only result of API requests and use Network first. Otherwise, just let the plugin does its job.

Thanks for your input and time into the issue.

**Comment by NekR** [comment]
> This implies I should not extend the code if it only caches static file. I think the entry item would suffice for my case.

You can do whatever you want in your `entry`. What I meant is that you shouldn't copy-paste code from `offline-plugin`'s SW code, unless you know what you're doing of course, because the code isn't guaranteed to be working there.

I know understand what you want to have, but still don't get if you are copy-pasting the code from `sw-template.js` to your SW entry or if you're forking `offline-plugin`.

**Comment by kikoanis** [comment]
> I know understand what you want to have, but still don't get if you are copy-pasting the code from sw-template.js to your SW entry or if you're forking offline-plugin.

My understanding and correct me if I am wrong is that the SW entry would be triggered each time you HTTP request. On the other hand, the network or cache strategies are only when you visit any URL within the site the first time. As you know, in single page applications, you would not down load static files again unless you refresh and you only navigate using javascript code using push and pull requests.

**Comment by kikoanis** [comment]
Her is what I use in the entry

```
const CACHE_NAME = 'my-site'

const listenFunc = (event) => {
  if (event.request.varb === 'POST' ||
      event.request.varb === 'PUT') {
      return null
  }
  const fetchRequest = event.request.clone()
  event.respondWith(
        fetch(fetchRequest).then(
          (res) => {
            if (!res || res.status !== 200) { // network failed
              return caches.match(event.request)
                .then((response) => {
                  if (response) {
                    return response
                  } else {
                    return res
                  }
              })
            }

            const responseToCache = res.clone()

            // Otherwise cache the downloaded files
            caches.open(CACHE_NAME)
              .then((cache) => {
                cache.put(event.request, responseToCache)
              })

            // And return the network response
            return res
          }
        )
        .catch((err) => {
          return caches.match(event.request)
            .then((response) => {
              if (response) {
                return response
              }
          })
        })
    )
}

self.addEventListener('fetch', listenFunc)

**Comment by NekR** [comment]
> My understanding and correct me if I am wrong is that the SW entry would be triggered each time you HTTP request. 

No, that's just SW code. But your listener to `fetch` event indeed will e triggered on any request, any other than those which are already handled by `offline-plugin`.
