### ISSUE TITLE
[Question] Are requests all been hangs up when Service Worker loading the additional caches?

### ISSUE THREAD

**Issue by lmk123** [NekR/offline-plugin#259]
My config looks like this:

```js
new OfflinePlugin({
  caches: {
    main: [':rest:'],
    additional: ['page-a.chunk.js', 'an-huge-image.png']
  }
})
```

In `main.js`:

```js
import { install, applyUpdate } from 'offline-plugin/runtime'

install({
  onUpdateReady () {
    applyUpdate()
  },
  onUpdated () {
    window.location.reload()
  }
})
```

When I updated my site, it takes a long time during Service Worker's `activate` event because of there is an huge image (almost 9MB). Before `activate` event end, every request (such as `page-a.chunk.js` or just reload the page) has been hang up. After `activate` event end, the page reload itself and everything looks good.

Is this an expected behavior, so I shouldn't put huge assets in `additional` caches?

**Comment by lmk123** [comment]
I tested with an huge image (almost 9MB) and capture the Network screenshots: 

<img width="1237" src="https://cloud.githubusercontent.com/assets/5035625/26190210/ca902576-3bda-11e7-8135-a180e3f017d0.png">

**Comment by NekR** [comment]
Are you on http2? If not, then for sure you have a limit with a number of requests at a time.

**Comment by NekR** [comment]
https://medium.com/@paularmstrong/twitter-lite-and-high-performance-react-progressive-web-apps-at-scale-d28a00e780a3#c8cf

**Comment by NekR** [comment]
Okay, what I think you should do is just call `OfflinePluginRuntime.install()` in window's `load` event.
