### ISSUE TITLE
Pattern matching not working for externals

### ISSUE THREAD

**Issue by archansel** [NekR/offline-plugin#261]
Sorry to bother you again @NekR, I want to cache external files, I use this configuration

```
new OfflinePlugin({
      safeToUseOptionalCaches: true,

      caches: {
        main: [':rest:'],
        additional: [':externals:'],
        optional: [],
      },

      externals: [
        '/assets/**/*.@(png|jpg)',
        '/css/**/*',
        '/fonts/**/*',
        '/icons/**/*',
        '/*.html',
      ],

      ServiceWorker: {
        output: '../sw.js',
        publicPath: '/sw.js',
      },
      AppCache: {
        output: '../appcache',
        publicPath: '/appcache',
      },
    }),
```

and the output `sw.js`

```
"assets": {
    "main": [
     ...
    ],
    "additional": [
      "/assets/**/*.@(png|jpg)",
      "/css/**/*",
      "/fonts/**/*",
      "/icons/**/*",
      "/*.html"
    ],
    "optional": []
  },
  "externals": [
    "/assets/**/*.@(png|jpg)",
    "/css/**/*",
    "/fonts/**/*",
    "/icons/**/*",
    "/*.html"
  ],
```

When I open in the browser, service worker throws errors
> Failed to load resource: the server responded with a status of 404 (Not Found) /fonts/**/*?__uncache=5%2F19%2F2017%2C%203%3A17%3A50%20PM

Is there no pattern matching in external?

**Comment by NekR** [comment]
It doesn't support pattern in there.

**Comment by archansel** [comment]
Do you have any suggestion how to get the list of my files in the external option without specifying one by one manually?

**Comment by NekR** [comment]
If assets are generated by webpack, then it's already done for you automatically. If not, then you probably should make them go through webpack. If you don't want, the use something like `glob.sync` (from glob-node) to match assets on the file system.

**Comment by archansel** [comment]
It is static assets (images, fonts, css) so RSK just copy then manually to build folder

I already tried using glob and its not working, turns out that I use asyn one, I'll try with the sync one. Thanks

**Comment by NekR** [comment]
> It is static assets (images, fonts, css) so RSK just copy then manually to build folder

You are saying that like webpack cannot do that :-)

**Comment by archansel** [comment]
Hahaha, I found it, a package to copy using webpack [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin), now `offline-plugin` cache static assets :D
