### ISSUE TITLE
Doesn't install new serviceworker

### ISSUE THREAD

**Issue by mcchrish** [NekR/offline-plugin#267]
Repo: https://github.com/mcchrish/test-offline

Reproduced using react-boilerplate.

The issue is that when reloading, hard reloading, visiting the site on a new tab, or even reopening the browser doesn't change the old SW. It seems the new SW is not being installed successfully.

**Comment by mcchrish** [comment]
Kinda of similar https://github.com/NekR/offline-plugin/issues/247#issuecomment-298470554

**Comment by NekR** [comment]
If it isn't installed successfully who n some file isn't loaded, or SW isn't loaded or whatever.

**Comment by NekR** [comment]
That comment is about old SW loosing its cache and not restoring, that doesn't affect new SW.

**Comment by mcchrish** [comment]
Found the cause. My mistake. The server https://github.com/indexzero/http-server I'm testing with is caching everything including the `sw.js`.

Thanks for the wonderful plugin, man!

**Comment by NekR** [comment]
Thanks! (I just realized my first comment wasn't really useful because of a lot typos I made typing on a phone 😅)

**Comment by NekR** [comment]
Btw, best option for `http-server` is `-c no-store`. I have no idea why they didn't make it a default. Who would use `http-server` on production to utilize that cache-on by default.
