### ISSUE TITLE
Custom template or extension point?

### ISSUE THREAD

**Issue by willdurand** [NekR/offline-plugin#27]
Hi! Thank you for this plugin, really useful and works well.

I would like to hook into the service worker code (I'd like to have custom logic in the `fetch` listener), and I was wondering if there was any way to hook into it right now?

Thanks,
William

**Comment by NekR** [comment]
Hi @willdurand,

Yes, you can have custom entry file for SW where you can handle `fetch` events as you want, but you cannot override behavior for assets listed in `caches` option. i.e. if you do some API request and want to handle them in SW, just set `ServiceWorker.entry` option to some JS file, like this:

```js
var OfflinePlugin = require('offline-plugin');

module.exports = {
  // ...

  plugins: [
    // ... other plugins

    new OfflinePlugin({
      // All options are optional
      caches: 'all',
      scope: '/',
      updateStrategy: 'all',
      version: 'v1',

      ServiceWorker: {
        output: 'sw.js',
        entry: 'sw-handler.js'
      },

      AppCache: {
        directory: 'appcache/'
      }
    })
  ]
  // ...
}
```

and in `sw-handler.js`:

```js
self.addEventListener('fetch', () => {
  // ...
});
```

Is it what you wanted?

**Comment by NekR** [comment]
Okay, I see what you do in your fork. So basically you SPA and for all (some?) requests server returns contents of `/` and you want same for SW, right? Yeah, it would be unfortunate to cache page for every such request separately.

**Comment by willdurand** [comment]
> So basically you SPA and for all (some?) requests server returns contents of / and you want same for SW, right? Yeah, it would be unfortunate to cache page for every such request separately.

Exactly! The SPA has a single entrypoint (`/`) and uses the URI to determine which data to load (e.g. `/123`). This works well online, but I want to be able to refresh the page offline, and still get the content. That is why redirecting any request matching (`/<identifier>`) to the cached version of `/` is interesting to me.

Should the `sw-handler.js` file be a modified version of `sw-template.js`?

**Comment by NekR** [comment]
> Should the sw-handler.js file be a modified version of sw-template.js?

No, it's an additional file to generated SW, it does not replace anything. Unfortunately there is no way at a moment to alter `sw-template.js` 😒

**Comment by willdurand** [comment]
Ok, great. Thank you for your answers. I am not sure to be able to only leverage the `sw-handler.js` file right now, but it is definitely good to know :)

**Comment by NekR** [comment]
Tracking cache mapping issue here now: https://github.com/NekR/offline-plugin/issues/59
Not sure about custom templates though, it reduces whole point of this plugin then since it's an internal thing which depends on particular version of the plugin. I guess just forking plugin and adopt template for your app is fine.
