### ISSUE TITLE
Nextjs example

### ISSUE THREAD

**Issue by Kikobeats** [NekR/offline-plugin#274]
Hey,

Do you think that could be easy connect offline plugin with Next.js?

Currently we can find a sw precaching:
https://github.com/zeit/next.js/tree/v3-beta/examples/with-sw-precache

but would be awesomeness take all the power of offline under nextjs umbrella 😄

**Comment by NekR** [comment]
I have no idea how Next.js works but `offline-plugin` works fine with any webpack projects, unless it doesn't something weird.

Any contributions, examples included, are very welcome :-)

**Comment by Kikobeats** [comment]
I'm going to try 😄

**Comment by astriskit** [comment]
@Kikobeats - what's your conclusion with nextjs?
