### ISSUE TITLE
offline mode is not working when I use domainName in the browser

### ISSUE THREAD

**Issue by vikramIde** [NekR/offline-plugin#277]
@xdamman  

Hello guys,

So I am using webpack to compile this plugin and my webpack.config option looks like thi s

```
plugins.push(new OfflinePlugin({
  publicPath: '/',
  caches: {
    
    additional: [
      ':externals:'
    ],
    optional: [
      ':rest:'
    ]
  },
  externals: [
    '/'
  ],
  ServiceWorker: {
    navigateFallbackURL: '/'
  },
  AppCache: {
    FALLBACK: {
      '/': '/offline-page.html'
    }
  }
}));
```

So My code works fine when I use ```http://localhost:8000/``` but if I use the demo vhot like ```http://ep-sass.local/``` it does not work and I get following error

> Creating Application Cache with manifest http://ep-sass.local/appcache/manifest.appcache
> searchapp:1 Application Cache Checking event
> searchapp:1 Application Cache Downloading event
> searchapp:1 Application Cache Progress event (0 of 1) http://ep-sass.local/offline-page.html
> searchapp:1 Application Cache Error event: Resource fetch failed (404) http://ep-sass.local/offline-page.html
> 

any thing am I missing here ?

**Comment by GGAlanSmithee** [comment]
ServiceWorker, and `offline-plugin` by extension, only works on localhost, or `https`.

**Comment by vikramIde** [comment]
@GGAlanSmithee  Thanks

**Comment by NekR** [comment]
Well, offline-plugin works without https by using AppCache, but in case of this issue AppCache is misconfigured. Localhost is treated as secure context by the browsers and hence SW works there.

**Comment by NekR** [comment]
It probably should be:

```js
AppCache: {
    FALLBACK: {
      '/': '/'
    }
  }
```

Because `/offline-page.html` is not found in your case (I guess you just copied an example code).
