### ISSUE TITLE
Uncaught ReferenceError: ExtendableEvent is not defined

### ISSUE THREAD

**Issue by kolima** [NekR/offline-plugin#278]
There is a bug when you open page

## Observed behavior ##
`Uncaught ReferenceError: ExtendableEvent is not defined`

Problem in this line: [offline-plugin](https://github.com/NekR/offline-plugin/blob/ee654c3fc93c83d7d3b44bed0f38d7c86163c967/lib/misc/async-waituntil.js#L4)

## Environment ##
Browser: Chrome version 59.0.3071.115 (64-bit)
OS: MacOS 10.12.5
offline-plugin: 4.8.3
webpack: 3.3.0

### P.S. ###
With offline-plugin: 4.7.0 works fine

**Comment by NekR** [comment]
Hi @kolima. I'm not sure how that's possible. `ExtendableEvent` is there in that Chrome version.

**Comment by kolima** [comment]
Hi @NekR. I hope this helps. 

<img width="871" alt="screen shot 2017-07-18 at 4 34 09 pm" src="https://user-images.githubusercontent.com/7297942/28319609-076ddb6a-6bd7-11e7-8834-27dcc796d471.png">

**Comment by NekR** [comment]
It isn't defined on Window. `ExtendableEvent` is an constructor on ServiceWorker global object and that code you linked to is running in ServiceWorker.

**Comment by kolima** [comment]
Thanks for answer, and you right. sw.js is included in index.html and running like js file.

**Comment by kresli** [comment]
Sorry to comment on closed issue but I have run into this and its not clear how is this fixed
```
Uncaught ReferenceError: ExtendableEvent is not defined
    at eval (empty-entry.js?5936:4)
    at eval (empty-entry.js?5936:42)
    at Object.../node_modules/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22cacheMaps%22%3A%5B%5D%2C%22navigationPreload%22%3A%22false%22%7D!../node_modules/offline-plugin/tpls/empty-entry.js (sw.js:310)
    at __webpack_require__ (sw.js:233)
    at sw.js:297
    at sw.js:300
```
the sw.js is imported as a very first script in index.html
```
<script src="/build/sw.js"></script>
```
any help?

**Comment by kolima** [comment]
I don't remember the problem and how we fixed it, and now we use another plugin [https://www.npmjs.com/package/workbox-webpack-plugin](https://www.npmjs.com/package/workbox-webpack-plugin)

**Comment by kresli** [comment]
Actually, the issue was to try inject sw.js script directly into html. This would never work because sw.js has node_modules dependencies. For future readers, don't use <script src="sw.js"> at all. All should be sorted for in your main script.
