### ISSUE TITLE
Multiple request for same file one from HTML and one via sw.js

### ISSUE THREAD

**Issue by varghesethomase** [NekR/offline-plugin#280]
http://localhost:3000/utilities/main.ea6de9e17bf574ec02e9.js?__uncache=2017-7-31%2009%3A46%3A59
http://localhost:3000/utilities/main.ea6de9e17bf574ec02e9.js

The two requests seem to be identical but is treated as two separate files getting loaded. How can i prevent this? 
![screen shot 2017-07-31 at 10 07 58 am](https://user-images.githubusercontent.com/5429756/28763126-5d19d210-75d9-11e7-962f-bfea71c68627.png)

**Comment by NekR** [comment]
You don't. One request is for your page to load and the other is to cache the file in ServiceWorker. That happens only on SW install.

**Comment by varghesethomase** [comment]
@NekR But this seems highly unlikely. If you can see the the file size is 318KB which actually is a considerably big file size. And double loading that means you have the largest file being loaded twice. Could you please help me find ways to solve this? All my external dependencies gets packed to that single file. Will code splitting work? And is there a way to make this specific to the offline plugin runtime loading?

**Comment by NekR** [comment]
I already said that you cannot do that, but let's figure out "why it's bad".

> If you can see the the file size is 318KB which actually is a considerably big file size.

How loading it once when ServiceWorker is installed hurts anything? Also it's considerably big to what exactly? I'm pretty sure images on your website (if any) weight x10 of that size and you load them on each page load, not only ~once~ twice.

> And double loading that means you have the largest file being loaded twice.

Yes, just twice.

> Could you please help me find ways to solve this?

Do not use SW and load that file on every page load every time. 

> Will code splitting work?

Code splitting is good for you, but it won't change the situation that ServiceWorker has to load all your scripts anyway.

> And is there a way to make this specific to the offline plugin runtime loading?

I have no idea what this means.
