### ISSUE TITLE
SW detects updates only after page reload

### ISSUE THREAD

**Issue by yantakus** [NekR/offline-plugin#282]
Thanks for the awesome work first of all!

I instantiate the plugin in the following way:

```
const runtime = require('offline-plugin/runtime');

runtime.install({
  onUpdateReady: () => {
    console.log('SW Event:', 'onUpdateReady');
    runtime.applyUpdate();
  },
  onUpdated: () => {
    console.log('SW Event:', 'onUpdated');
    window.swUpdate = true;
  },
});
```

But SW doesn't detect updates without page reload. When I reload the page, these events are fired.

Here is my config:

```
    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',

      autoUpdate: 1000 * 60 * 2,

      excludes: ['.htaccess'],

      caches: {
        main: [':rest:'],
        additional: ['*.chunk.js'],
      },

      safeToUseOptionalCaches: true,

      ServiceWorker: {
        events: true,
        navigateFallbackURL: '/',
      },

      AppCache: false,
    }),
```

Any ideas why this happens?

Here is the [example repo](https://github.com/yantakus/webpack-example) to test it if you need.

**Comment by NekR** [comment]
Make sure you serve sw.js with Cache-Control: no-store. Otherwise it might be cached in browsers.

**Comment by NekR** [comment]
@yantakus reading that linked issues it seems that you have some issues configuring your server. I'm not sure if your issue (as described here) is Cache-Control related, but it seems like that's the case.

I'm going to close this, but if `Cache-Control: no-store` won't help you then feel free to drop a comment here and we'll try to figure out what's going on with it.
