### ISSUE TITLE
Send error with onUpdateFailed

### ISSUE THREAD

**Issue by ismay** [NekR/offline-plugin#285]
It seems that currently the `onUpdateFailed` event does not pass an error to the event handler (judging from the source and docs). It would be nice to receive an error so that I can log and debug what went wrong exactly. Currently I only have the client data (browser, os, etc.), which doesn't tell me exactly what went wrong.

**Comment by NekR** [comment]
@ismay See https://github.com/NekR/offline-plugin/issues/243. Any contributions are welcome. Closing this as a duplicate.

**Comment by ismay** [comment]
Ah, didn't notice that one. Thanks!
