### ISSUE TITLE
using offline-plugin in Laravel Vuejs Project

### ISSUE THREAD

**Issue by maitrungduc1410** [NekR/offline-plugin#288]
Hi everybody
I'm now try to use **offline-plugin** in my **Laravel, Vuejs project** using **laravel-mix**(in 5.4 we don't use elixir anymore). 
But the problem is: I can't add **blade.php** file in **'main' of 'caches'**, It renders error: cache asset ***.blade.php** is not found in the output asset
I tried to add **blade** file to **externals**, **service worker** could be registered OK but when I turn of the network and reload the page the **service worker** was deleted
Can anybody help or give me an example?
Many thanks!

**Comment by NekR** [comment]
What does it mean "deleted"? Adding external links to `externals` option is the right way to do it.

**Comment by maitrungduc1410** [comment]
let me try, thanks :))
