### ISSUE TITLE
Notifying users of new content

### ISSUE THREAD

**Issue by amiuhle** [NekR/offline-plugin#29]
I currently set offline-plugin's version option to the version of my `package.json`, so that it automatically changes when I deploy a new version.

For AppCache, this results in a changed manifest file, which will download the new files and fire an `updateready` event. I can then tell the user that there is new content available and refresh the page.

For ServiceWorker though, changing the version results in a new Cache being used. The current SW will still be active and use the old cache, and the new SW will only become active when the user closes and reopens the tab/window.

Is there a way to notify the user of the changes and force switching to the new SW? Or could the old SW somehow pick up the new cache available?

Or am I doing something completely wrong and this should just work? Right now I can refresh the Browser all day, unless I close the tab the SW will always give me the old, cached content...

**Comment by amiuhle** [comment]
I just noticed there might be some stuff regarding this in the `v3` branch, will have a look at it!

**Comment by NekR** [comment]
> I just noticed there might be some stuff regarding this in the v3 branch, will have a look at it!

Hi @amiuhle, yes, this is resolved in `v3`, but it's not ready yet. `CHANGELOG` contains all the information about what was changed, but if you will need any help--let me know.

> Right now I can refresh the Browser all day, unless I close the tab the SW will always give me the old, cached content...

Yes, this is how SW works by default unless you tell to it to behave differently.

> For AppCache, this results in a changed manifest file, which will download the new files and fire an updateready event. I can then tell the user that there is new content available and refresh the page.

Fun fact, at first I started making those events for AppCache first, but events are so buggy and inconsistent between browsers when AppCache is used from iframe. I literally spent 2 weeks trying to make it "right" and then gave up. I will probably make AppCache disabled by default in `v3`, because I have it now, but still will support it as fallback.

Should we close this now or may be you have some suggestions here?

**Comment by amiuhle** [comment]
Thanks for the feedback!

I just started playing with the v3 branch. I'll mention this issue, should I make any PRs regarding `v3` functionality.

**Comment by NekR** [comment]
> should I make any PRs regarding v3 functionality.

Yes, please. Feel free to do that. Any help is welcome :-)

**Comment by amiuhle** [comment]
So, I'm successfully using the `v3` now, using `updateStrategy: 'all'`.

I'm supplying all supported callbacks for `runtime.install`, and `onUpdateReady` is called when the version changes. However, I can do a `window.location.reload(true)`, but the old SW will still only serve my old content, and the new one is not updated.

Do you have update functionality working? Can you supply your configuration, please?

Also, the README is not up to date in the `v3` branch. I understand you don't want to update the documentation before the features are final, but maybe you could open an issue as a roadmap for v3 where you have a TODO list and a rough outline of where you want to go with v3. I really would like to help, but without understanding where you're going with the next version, it's kind of hard...

**Comment by amiuhle** [comment]
I just saw the `applyUpdate` function, so forget the top half of my last comment.

I still think a 'v3 Roadmap' issue would be a good idea though!

**Comment by NekR** [comment]
> Also, the README is not up to date in the v3 branch.

I am working on update README, but yes, it's not in priority. 

> but maybe you could open an issue as a roadmap for v3 where you have a TODO list and a rough outline of where you want to go with v3.

Sounds good. I can do that. Basically what I plan for `v3` is marked as milestone `3.0` in issue. Not all issues marked `3.0` must be in it, but this is how I mark them "for next release".

I will make a pull request from `v3` to `master` and will describe what I plan for `v3`. But I still prefer to track thing in issues, e.g. one issue per problem/feature. Probably I can just make a list of issues in that PR.

... and, thanks for your suggestions and willingness to help :-)

**Comment by NekR** [comment]
Btw, this is how I use update events: 

```js
const runtime = require('offline-plugin/runtime');

runtime.install({
  onUpdating: () => {
    console.log('SW Event:', 'onUpdating');
  },
  onUpdateReady: () => {
    console.log('SW Event:', 'onUpdateReady');
    runtime.applyUpdate();
  },
  onUpdated: () => {
    console.log('SW Event:', 'onUpdated');
    window.location.reload();
  },

  onUninstalled: () => {
    console.log('SW Event:', 'onUninstalled');
  }
});
```
