### ISSUE TITLE
Error MIME type

### ISSUE THREAD

**Issue by maitrungduc1410** [NekR/offline-plugin#291]
I'm building a Laravel app using Vuejs and when I use this offline-plugin, after loading my page, it's render these errors: 

>The script has an unsupported MIME type ('text/html').
>Failed to load resource: net::ERR_INSECURE_RESPONSE
>Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html')      .............topic:1

Can any body help me?
Thanks!

**Comment by NekR** [comment]
mime-type of ServiceWorker file should be one of JavaScript mime-types. Your server either doesn't server that file correctly your the file doesn't exist of the location where it supposed to be, hence you server send 404 html page or something like that.

**Comment by NekR** [comment]
See this issues for details: https://github.com/NekR/offline-plugin/issues/77
