### ISSUE TITLE
Updatestrategy's effect on assets in the 'main' section of caches

### ISSUE THREAD

**Issue by ismay** [NekR/offline-plugin#292]
I'm currently using the `all` updateStrategy because not all my assets have a hash appended to their filename. Only my clientside js does. And the docs state that in that case the `all` updateStrategy is best since it will re-verify all assets.

However, what confuses me is that the docs also state that for the `changed` updateStrategy:

> With this strategy enabled, index.html file (or other files without dynamic name) should be placed in main section of the cache, otherwise they won't be revalidated.

Does that mean that all assets that are listed in `main` will be re-verified anyway, even when using the `changed` updateStrategy? Because that's a little unclear to me from the docs. Also, wouldn't basically everyone need to use the `all` updateStrategy, since a lot of builds will emit assets that aren't hashed?

---

Just for clarity, this is the current config I'm using, and the above question arose from me thinking about which updateStrategy would be best:

```javascript
// https://github.com/ismay/ismaywolff.nl/blob/develop/webpack.config.client.prod.js#L154-L182
    new OfflinePlugin({
      autoUpdate: true,
      output: 'sw.js',
      version: process.env.RELEASE,
      updateStrategy: 'all',
      caches: {
        main: [
          ':externals:',
          'manifest.json',
          '*.js',
          '*.woff',
          '*.woff2',
          '*.png',
          '*.xml',
          '*.ico'
        ],
        additional: [],
        optional: []
      },
      externals: [
        '/index.html',
        'https://cdn.polyfill.io/v2/polyfill.min.js'
      ],
      AppCache: false,
      ServiceWorker: {
        events: true,
        navigateFallbackURL: '/'
      }
    })
```

**Comment by NekR** [comment]
Actually, you're fighting a problem what doesn't exist. It's weird, but docs for `updateStrategy` are pretty much outdated. With `changed` strategy `offline-plugin` calculates files' hashes on its own, no matter what name they have. This also helps with files being renamed, i.e. if the hash is the same then file isn't redownloaded but rather just renamed.

Also, `updateStrategy` doesn't apply to externals. They're always revalidated/redownloaded on SW update.

**Comment by ismay** [comment]
Ah that's great! Thanks for clarifying!

**Comment by NekR** [comment]
Great! :-)
