### ISSUE TITLE
Help needed: why the service-worker loads my items sequentially?

### ISSUE THREAD

**Issue by pinebit** [NekR/offline-plugin#298]
I have a bunch of files in my reactjs application, which is built with webpack.
I noticed my site is loading pretty slow, and here is what Chrome Tools display when it loads:
![sw-loading-images](https://user-images.githubusercontent.com/6468078/29788707-43f8ed2e-8c3c-11e7-9431-954e2461819d.PNG)
Here, all requests shown in the picture are GET request to load individual SVG files. Nothing unusual except every request is added `_uncache` query parameter, which is Okay I think.
for example:
`GET https://mysite.com/48257e6f7dcef91cea19739ee5c88ef0.svg?__uncache=8%2F28%2F2017%2C%201%3A09%3A48%20PM`

It looks like the service worker is loading items sequentially. I'm wondering if it is possible to make them loading concurrently?

Here is how I configure OfflinePlugin in webpack:
```
new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',
      excludes: ['.htaccess', 'VERSION'],
      caches: {
        main: [':rest:'],
        additional: ['*.chunk.js'],
      },
      ServiceWorker: {
        prefetchRequest: { credentials: 'include' },
      },
      safeToUseOptionalCaches: true,
      AppCache: false,
    }),
```
(this config is almost identical to [reactboilerplate.com](reactboilerplate.com) which I used to bootstrap my app)

Finally, I initialize the plugin as the last step of my app.js initialization sequence:
`require('offline-plugin/runtime').install();`

However, _the last step_ is not a precise phrase here, because I have a lot of stuff loading asynchronously (sagas, redux, etc.), so I just _initialize_ the plugin as the last statement of my app.js.

**Comment by NekR** [comment]
Use http/2 and they will load concurrently, http/1 has a limit n 6 parallel requests at a time. And that isn't SW related, that's for everything.

**Comment by pinebit** [comment]
Thank you!

**Comment by NekR** [comment]
But better solution might be to not preload everything. You may try to move
all those icons to the `optional` section of caches. This way they won't be
preached, but rather cached once requested from your app.

**Comment by pinebit** [comment]
Alright, we enabled HTTP/2 and this indeed helped a lot! The website is now loading blazing fast, so thank you for this advice.
Regarding the optional, am I correct I can simply add this: `additional: ['*.svg'],`?

Also I was testing updates (deployments) and found a quote saying a user needs to close all tabs with this site opened or restart the browser for updates to take into effect. I understand this has little to do with offline-plugin, but still - isn't there an option to clear the entire cache at once programmatically? At the moment, I'm detecting a new version with my custom code (fetching a `git describe` file) and trying to `window.location.reload(true)`, but it seems this strategy is useless when offline-plugin is used.

Thanks!

**Comment by NekR** [comment]
```js
caches: {
  main: [':rest:', ':externals:'],
  optional: ['*.svg']
}
```
For update, in this doc there is a section which shows how to use events and reload tabs when update happens: https://github.com/NekR/offline-plugin/blob/master/docs/updates.md
