### ISSUE TITLE
Unable to use with passport

### ISSUE THREAD

**Issue by ZeroCho** [NekR/offline-plugin#303]
After setting offline-plugin `GET /api/auth/google` doesn't work. This url triggers `passport.authenticate('google')` in server and causes redirection to callback url.
As I inspected Network tab of developer tools, it seems that it tries to fetch /api/auth/google from serviceworker, which causes no redirection.
![image](https://user-images.githubusercontent.com/10962668/30333841-e369cc60-9818-11e7-8672-546ed56d5b5f.png)
I think I have to exclude /api/auth/google from being cached,  so I set up cacheMaps and requestTypes, but of no use.

My setting is like below.
```
  new OfflinePlugin({
      caches: {
        main: ['app.js'],
        additional: [
          ':externals:',
        ],
        optional: [
          ':rest:',
        ],
      },
      responseStrategy: 'network-first',
      updateStrategy: 'changed',
      externals: [
        '/',
        '/category/Javascript',
        '/category/jQuery',
        '/category/HTML',
        '/category/CSS',
        '/category/EcmaScript',
        '/category/NodeJS',
        '/category/React',
        '/category/Algorithm',
        '/category/MongoDB',
        '/category/Webpack',
        '/category/Git',
        '/category/etc',
        '/api/category',
      ],
      cacheMaps: [{
        match(url) {
          if (url.pathname.indexOf('/api/') === 0) {
            return false;
          }
          return new URL('/', location);
        },
        requestTypes: ['navigate'],
      }],
      safeToUseOptionalCaches: true,
      version: VERSION,
      autoUpdate: 1000 * 60,
      ServiceWorker: {
        events: true,
        entry: '../app/serviceworker.js',
        navigateFallbackURL: '/',
      },
    }),
```

**Comment by GGAlanSmithee** [comment]
@ZeroCho 

From a glance, it looks correct.

A few things to check off before troubleshooting further.

1. Have you cleared previously cached service worker? To be 100% sure, you can go to chrome://serviceworker-internals/ and remove your site
2. Are you sure that `url.pathname.indexOf('/api/') === 0` matches your url? ie, it starts with `/api/`

**Comment by ZeroCho** [comment]
@GGAlanSmithee Nice to meet you here

1. I cleared serviceworker but still the same thing happens.
2. url is `/api/auth/google` so I think it matches mine.

**Comment by NekR** [comment]
Hi. So the problem in `navigateFallbackURL: '/'` option which treats redirects as fails. What you need here is either `ServiceWorker.navigateFallbackForRedirects` set to `false` or just use `cacheMaps` and remove `navigateFallbackURL`.

**Comment by ZeroCho** [comment]
@NekR Thanks you so much! I can now stop pulling my hair out. You saved my day.

**Comment by NekR** [comment]
@ZeroCho no problem and sorry for a late answer!

**Comment by GGAlanSmithee** [comment]
Nice to see you too @ZeroCho. :)

Looks like @NekR saved the day once again! :1st_place_medal:
