### ISSUE TITLE
Does not respond with a 200 when offline and start_url is not cached by service worker

### ISSUE THREAD

**Issue by JuanLuisGarciaBorrego** [NekR/offline-plugin#304]
Hi! 
In lighthouse extension i have a 2 error?

**Does not respond with a 200 when offline**

**User will not be prompted to Install the Web App**
Failures: Manifest start_url is not cached by a Service Worker. 

My webpack config is:

```js
new OfflinePlugin({
            excludes: ['https://www.googletagmanager.com/*','https://www.google-analytics.com/*'],
            caches: 'all',
            safeToUseOptionalCaches: true,
            autoUpdate: true,
            updateStrategy: 'all',
            ServiceWorker: {
                events: true,
                prefetchRequest: {credentials: 'same-origin'}
            },
            AppCache: {
                events: true,
                includeCrossOrigin: true
            },
        })
```

file.js
```js
require('offline-plugin/runtime').install();
```

Can you help me?
Thanks!

**Comment by NekR** [comment]
Hey. Just cache your start URL explicitly via `externals` option, e.g. `externals: ['/']`.

**Comment by dangodev** [comment]
Had the same problem and this worked brilliantly. This wasn’t intuitive for me; would there be a good place to add this information to the docs somewhere? This seems like very helpful info given how many people that use this plugin also use Lighthouse.

**Comment by NekR** [comment]
@GGAlanSmithee what do you think, what would be the best place? Troubleshooting doc? Maybe put a disclaimer to the top of README about the doc? Or maybe link it in ISSUE_TEMPLATE or something like that?

@dangodev Yeah, it definitely would be good to make that visible. I think it's this issues is explained somewhere, but I'm not sure where exactly too :-)

**Comment by GGAlanSmithee** [comment]
@NekR

Yes, absolutely, both your suggestions are very reasonable. Tomorrow I will try to give time to

1. As docs regarding this to `troubkeshooting.md`
2. Add link to `troubleshooting.md` from `README.md`
3. Add link to `troubleshooting.md` from `ISSUE_TEMPLATE`

**Comment by NekR** [comment]
@GGAlanSmithee I think I may time for it myself. First one wins 😂

**Comment by GGAlanSmithee** [comment]
@NekR : running:

**Comment by csantiago132** [comment]
@NekR ok so based on Google devs docs, it says to put start url like
```json

"start_url": "./",

```

& based on the docs here 
```js
externals: ['./'],
```

So im assuming these two has to be the same to get rid of this flag in Lighthouse audit?

**Comment by ctaperts** [comment]
I found that if you use another path to your files instead of `'/'` for example
```
app.use('/dist', express.static(path.join(__dirname, '../dist')));
```
will cause some odd behavior... use
```
app.use('/', express.static(path.join(__dirname, '../dist')));
```
to get it to work always
