### ISSUE TITLE
app tries load bundle from disc root

### ISSUE THREAD

**Issue by Zuzon** [NekR/offline-plugin#31]
`GET file:///D:/main.bundle.js net::ERR_FILE_NOT_FOUND`

tried change 'relativePaths' and 'scope' settings, they has no effect

**Comment by NekR** [comment]
Hi @Zuzon

How do you run it? From server/webpack-dev-server/direct from disk?

**Comment by NekR** [comment]
Also, if it's possible, can you show what SW/AppCache plugin generates for you?

**Comment by Zuzon** [comment]
appcache: 
`CACHE MANIFEST
#ver:v1

CACHE:
../0ac1be82bd79e6be47a32376d286480f.png
../polyfills.bundle.js
../vendor.bundle.js
../main.bundle.js
...
`

>How do you run it?
simply open index.html as file

**Comment by NekR** [comment]
SW is not supposed to work this way. AppCache, even it can, there is not reason for it to work. I tested path generation only with usage on servers, so may fail with `file:`.

Btw, what is the problem running/testing it with server? I use `http-server` which is pretty easy to work with:

```
npm install http-server -g # install
http-server # run in output folder
```

**Comment by Zuzon** [comment]
my project is a bit specific.
i need to create a desktop .net app, on this app i integrate gecko browser engine and also that engine runs my web app in offline without webserver

**Comment by NekR** [comment]
@Zuzon hmm.. okay, I will check `file:` support. But, are you sure AppCache is working with `file:` protocol?

**Comment by Zuzon** [comment]
NekR, i found a reason of path problem, because i have baseUrl with slash set (/), with empty string all works perfectly.
I'm sorry to have kept spending your time.

**Comment by NekR** [comment]
@Zuzon no problem! Glad that it works for you know. Feel free to open another issue if something :-)
