### ISSUE TITLE
How to exclude a specific path and all the paths underneath from being cached?

### ISSUE THREAD

**Issue by gazpachu** [NekR/offline-plugin#310]
`/admin` and all the paths underneath are not part of my app, so I want to avoid the SW from caching those paths.

I've tried with `excludes: ['**/*.map', '/lighthouse/admin', '/lighthouse/admin/**'],`, but this is not excluding `/lighthouse/admin`, nor `/lighthouse/admin/whatever` from being cached.

What am I doing wrong?

![screen shot 2017-10-12 at 15 52 00](https://user-images.githubusercontent.com/1721288/31499573-71f974b8-af65-11e7-9081-954572dff185.png)

Full config:

```
new OfflinePlugin({
        safeToUseOptionalCaches: true,
        excludes: ['**/*.map', `/${appName}/admin`, `/${appName}/admin/**`],
        updateStrategy: 'changed',
        autoUpdate: 1000 * 60 * 2,
        caches: {
          main: [
            'assets/styles/app.*.css',
            'assets/scripts/vendor.*.js',
            'assets/scripts/app.*.js',
            'assets/scripts/manifest.*.js'
          ],
          additional: [
            ':externals:'
          ],
          optional: [
            ':rest:'
          ]
        },
        externals: [
          `/${appName}`
        ],
        ServiceWorker: {
          events: true,
          navigateFallbackURL: `/${appName}`
        },
        AppCache: {
          FALLBACK: {
            '/': '/assets/static/offline.html'
          }
        }
      })
```

**Comment by NekR** [comment]
Use `cacheMaps` option instead of `navigateFallbackURL`. The later is deprecated. With `cacheMaps` you can control whatever should be cached. Let me know if that works for you.

**Comment by NekR** [comment]
For AppCache, it most likely isn't possible. You cannot route separate routes to the network with it, but instead of have to route all your routes to offline. Unfortunately.

**Comment by NekR** [comment]
As a workaround for AppCache, you may do:

```js
FALLBACK: {
  '/': '/assets/static/offline.html',
  '/admin': '/not-available.html'
}
```

In this case, when user is offline or the service is not available, it will show `/not-available.html`, i.e. custom error page.

@GGAlanSmithee do you think it would be good to document this on troubleshooting?

**Comment by GGAlanSmithee** [comment]
@NekR definitely. Will try to do that tomorrow! Is `navigateFallbackURL` marked as deprecated in the docs? Should I do it if not?

**Comment by NekR** [comment]
@GGAlanSmithee it's marked as deprecated in my mind and my plans, not in the docs just yet. It would be confusing to mark it as deprecated until I have `appShell` option released, which supposed to be as simple as `navigateFallbackURL` but use `cacheMaps` instead.

Once I have `appShell` done, we will update the docs about `navigateFallbackURL` :-)

**Comment by NekR** [comment]
`appShell` is actually done, but it's in `4.9.0` branch and I cannot merge it until other features in it are done..

**Comment by gazpachu** [comment]
@NekR could you please post here a cacheMaps config example for my use case? I think it would be useful also for other people with similar cases. Many thanks!

**Comment by gazpachu** [comment]
I've been trying with something like this, but still doesn't work :/

```
cacheMaps: [
          {
            match: /^(?!\/lighthouse\/admin).+$/,
            to: '/',
            requestTypes: ['navigate']
          }
        ],
```

**Comment by NekR** [comment]
It's better to use a function in this case. I'll show an example later.

**Comment by gazpachu** [comment]
ok, thanks. I'll wait for the example

**Comment by NekR** [comment]
```js
cacheMaps: [
  {
    match: function(url) {
      if (url.pathname.indexOf('/admin/') === 0) {
        return;
      }

      return new URL('/', location);
    },
    requestTypes: ['navigate']
  }
]
```

**Comment by gazpachu** [comment]
Thanks, it works! :-)

Just had to slightly change it:

```
match: (url) => {
              if (url.pathname.indexOf('/admin/') === 0) {
                return true;
              }
              return new URL('/', url.location);
            },
            requestTypes: ['navigate']
```

**Comment by NekR** [comment]
Why it didn't work without `true` and why you use `url.location` which is `undefined`? `URL` construct should throw in your case .

**Comment by gazpachu** [comment]
I had to use url.location because location is not defined anywhere, so eslint complained. Also complained about returning nothing in one case and something on the other. I also had to add URL to the eslint globals. Did I do anything wrong?

**Comment by NekR** [comment]
Yes, you did. ESLint cannot know anything about your program or libraries especially so it shouldn't dictate what you do with them. It's perfectly fine to return whatever value in JS, that's why such functionality exists. Just disable ESlint for that function or use `new Function(...)` and do what I suggested you to do to fix the problem.

**Comment by danny-wang** [comment]
> eslint

how you add URL to the eslint globals? i meet same question, Browser show: sw.js:3 Uncaught TypeError: Failed to construct 'URL': Invalid URL

**Comment by danny-wang** [comment]
> > eslint
> 
> how you add URL to the eslint globals? i meet same question, Browser show: sw.js:3 Uncaught TypeError: Failed to construct 'URL': Invalid URL

my problem solved, ignore me
