### ISSUE TITLE
How do I cache requests to an external CDN, without specifying all files?

### ISSUE THREAD

**Issue by StephanBijzitter** [NekR/offline-plugin#312]
We have a CDN that hosts a lot of fonts for us, and it's updated independently. We _could_ determine all resources during build time, but is it really needed?

Ideally, I'd just want to specify `**/thumbs/*.woff` as an external and have the service worker cache a request as soon as it matches this. Would that be possible?

**Comment by NekR** [comment]
That indeed would be better, but not possible right now. There is no such API at the moment. It's pretty popular request, although nobody yet contributed it to the plugin. So maybe not that popular.
