### ISSUE TITLE
How to check if service worker already installed?

### ISSUE THREAD

**Issue by s123121** [NekR/offline-plugin#313]
I have to integrate `offline-plugin` with OneSignal. Base on [their suggestion](https://documentation.onesignal.com/v3.0/docs/web-push-sdk-setup-https#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-), I have to manual register the service worker.
Do we have a way to check if plugin's runtime have already installed or not? So I can skip `runtime.install()`

**Comment by s123121** [comment]
Ok, I am stupid. Looking into the api, I can check `navigator.serviceWorker.controller` to identify  the service worker that intercepts fetch requests. However, In case we have multiple service worker( with multiple scope), do `navigator.serviceWorker.controller` return them all or just the the root scope service worker?

**Comment by NekR** [comment]
@s123121 Hi, sorry, missed this issue. `navigator.serviceWorker.controller` current controlling ServiceWorker for your scope.

`offline-plugin` has no special compatibility with OneSignal, so omitting `runtime.install()` is on your own risk.
