### ISSUE TITLE
Webpack 2

### ISSUE THREAD

**Issue by klihelp** [NekR/offline-plugin#317]
Upgrade to Webpack 2?

**Comment by NekR** [comment]
It should support all the webpack versions. I don't perform tests for them, but I successfully used it with webpack 2 and 3, and other people do. What's you issue with it?

**Comment by NekR** [comment]
I'll close this. Feel free to leave a comment here if it doesn't for you in any webpack version and I'll reopen.

**Comment by klihelp** [comment]
It does work wirh webpack 3. Can you update the dependencies for the project here on gihub?

**Comment by NekR** [comment]
I have webpack only as a devDependency for tests, why would I update it?
