### ISSUE TITLE
applyUpdate is fired after entering the page

### ISSUE THREAD

**Issue by morriq** [NekR/offline-plugin#319]
After deploy I'm opening my webapp in new card and onUpdated is fired. It's killing look and feeling, coz user recently refreshed webapp and offline-plugin tells him to do it again

webpack:

```
    plugins: [
      new OfflinePlugin({
        autoUpdate: 1000 * 30,
        ServiceWorker: {
          events: true
        }
      })
]
```

```
OfflinePluginRuntime.install({
  onUpdateReady(): void {
    OfflinePluginRuntime.applyUpdate();
  },

  onUpdated(): void {
    window.dispatchEvent(new CustomEvent(refreshRequiredEventName));
  }
});
```

**Comment by NekR** [comment]
Just don't call `applyUpdate();` in there if you don't want to.

**Comment by morriq** [comment]
Thank you for reply,

Alright, so you're suggesting to control it somehow (detecting "fresh" enter on webapp) and if true then skip `applyUpdate()`.

Could you tell me if I'll do it and script will skip this `applyUpdate()` then after releasing newer version (and still staying on old page when script has skipped first `applyUpdate()`) then it will be detected in runtime?

**Comment by NekR** [comment]
> Alright, so you're suggesting to control it somehow (detecting "fresh" enter on webapp) and if true then skip applyUpdate().

I'm not suggesting anything. If you want to do it -- do it.

> Could you tell me if I'll do it and script will skip this first applyUpdate() then after releasing newer version (and still staying on old page when script has skipped first applyUpdate()) then it will be detected in onUpdateReady?

`onUpdateReady ` is called on every update. When you visit a website and there is an update -- it's called. When an `autoUpdate` check happens and there is an update -- that method is called.

What you do in it is your choice.
