### ISSUE TITLE
Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by postgetme** [NekR/offline-plugin#320]
"Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://static.website.io') does not match the current origin ('https://website.io')."

how should I fix this problem? thanks!

**Comment by NekR** [comment]
Serve ServiceWorker from `https://website.io` as the error suggests.

**Comment by wclr** [comment]
@NekR 

I got this error.

I serve index.html from `https://website.xxx/` that loads bundles from CDN: `https://some.cdn.xxx/..` 
There is available generated `https://website.xxx/sw.js` but the script that installs plugin is loaded from CDN.

While webpack build I use `publicPath: 'https://some.cdn.xxx/..` 

So what should be done to make it work?

**Comment by duyphanz** [comment]
> @NekR
> 
> I got this error.
> 
> I serve index.html from `https://website.xxx/` that loads bundles from CDN: `https://some.cdn.xxx/..`
> There is available generated `https://website.xxx/sw.js` but the script that installs plugin is loaded from CDN.
> 
> While webpack build I use `publicPath: 'https://some.cdn.xxx/..`
> 
> So what should be done to make it work?


Can try:

```javascipt
new OfflinePlugin({
      publicPath: 'https://website.xxx/',
      // others
})
```

or if you're extending service worker

```javascipt
new OfflinePlugin({
    ServiceWorker: {
          entry: pathP.join(process.cwd(), 'app/firebase-messaging-sw.js'), // <-- path for your extended service worker
          publicPath: 'https://website.xxx/firebase-messaging-sw.js',
     },
})
```
