### ISSUE TITLE
Q: Usage when purposefully loading index without 404?

### ISSUE THREAD

**Issue by hunterwilliams** [NekR/offline-plugin#323]
My scenario is using react app on the frontend using this plugin. We always forward all 404 errors to index.html so that the 404 is handled via the react app. However this causes the service worker to explode because it doesn't deal with HTML. 

The app is based off of react boiler plate and I've not modified the plugin usage. I'm looking at cachemaps, but it seems as if it's still going to have an issue. Not sure the best way to go from here. I'm 90% sure it's something quite simple and probably a one to two line fix or something configuration wise incorrect. 

We're never caching sw.js, but the rest of the files are cached including index.html (which I don't think is a problem as sw.js should see it needs new files)
```
new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',

      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],

      caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },

      // Removes warning for about `additional` section usage
      safeToUseOptionalCaches: true,

      AppCache: false,
    }),
```

**Comment by NekR** [comment]
@hunterwilliams hey. Yeah, `cacheMaps` should be the answer. 

Try adding this:

```js
cacheMaps: [
  {
    match: function(url) {
      return new URL('/', location);
    },
    requestTypes: ['navigate']
  }
],
```

**Comment by hunterwilliams** [comment]
@Nekr thank you!! Should this have a side effect of causing cors issues? The main app calls a different subdomain for APIs.

**Comment by NekR** [comment]
@hunterwilliams since it's `requestTypes: ['navigate']` it won't affect CORS requests. It will be handling only browser's navigation requests.

**Comment by hunterwilliams** [comment]
Thanks
