### ISSUE TITLE
Webpack 4 alpha test results

### ISSUE THREAD

**Issue by swarajgiri** [NekR/offline-plugin#325]
From [sokra's reply](https://github.com/webpack/webpack/issues/6064#issuecomment-349209353)
`compilation.fileDependencies` is now a Set. 

We need to update, 
`if (compilation.fileDependencies.indexOf(runtimeTemplatePath)` to use a set instead of an array.

Details of the original test can be found [here](https://github.com/webpack/webpack/issues/6064#issuecomment-349192702)

Can this be a part of the next semver major?

Thanks.

**Comment by GGAlanSmithee** [comment]
@swarajgiri 

Thanks for reporting this. The actual quote from @sokra is

> offline-plugin: compilation.fileDependencies is now a Set. They need to change to has which is faster anyway.

So the fix on our side should be to change 

`if (compilation.fileDependencies.indexOf(runtimeTemplatePath)`

to

`if (compilation.fileDependencies.has(runtimeTemplatePath)`

This would be a breaking change though (I think), so we would probably have to detect this runtime and handle both cases for backwards compatability.

What you think @NekR ?

**Comment by NekR** [comment]
It can be a patch fix, no need for major or minor even. Just detect if it's a Set and use appropriate method, as Alan said. I'll do that later today.

**Comment by NekR** [comment]
Thanks for reporting btw! 👍

**Comment by swarajgiri** [comment]
Happy to help.

**Comment by NekR** [comment]
@swarajgiri I made a fix, can you test with a code from github? (`npm install NekR/offline-plugin`)
If it works as expected, I'll make a release.

**Comment by swarajgiri** [comment]
@NekR - Does not throw this error now.

Side note: I have the runtime added in the entry file
```js
import * as OfflinePluginRuntime from 'offline-plugin/runtime';

// register service worker
OfflinePluginRuntime.install({
    onUpdateReady: () => OfflinePluginRuntime.applyUpdate(),
});
```

But webpack says that i haven't added it
`ERROR in OfflinePlugin: Plugin's runtime wasn't added to one of your bundle entries. See this https://goo.gl/YwewYp for details`

Note: I have lot of breaks from `file-loader`. Can this be caused because of the incomplete error'ed out bundling?

**Comment by NekR** [comment]
It's directly related to this issue, I screwed the logic. Thanks for
testing, making a fix now.

**Comment by NekR** [comment]
Okay, I made another commit, it should work now. Would be great if you could test it again.

**Comment by swarajgiri** [comment]
Error squashed. You are the man. Cheers.

**Comment by NekR** [comment]
Great! Thanks for assisting and testing! 👍

**Comment by NekR** [comment]
Great! Thanks for assisting and testing! 👍

On Dec 7, 2017 1:30 PM, "swarajgiri" <notifications@github.com> wrote:

Error squashed. You are the man. Cheers.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/NekR/offline-plugin/issues/325#issuecomment-349927398>,
or mute the thread

**Comment by NekR** [comment]
https://github.com/NekR/offline-plugin/releases/tag/v4.8.5

**Comment by swarajgiri** [comment]
Happy to help.
