### ISSUE TITLE
Offline mode mulfunction

### ISSUE THREAD

**Issue by PaulLaux** [NekR/offline-plugin#328]
## Issue Type

- [ ] Bug

## Description
Hello guys, getting sw not working while offline.

"Unknown error occurred when fetching the script"

webpack-offline plugin installed and seems to be working (see image), not sure how to debug.

![webpack_offline](https://user-images.githubusercontent.com/3682187/33727448-bca9acca-db80-11e7-80a7-0b9e2b9cc1ae.jpg)

## Steps to reproduce
- Load site on https://eth-hot-wallet.com
- Go Offline
- Reload Site

Site should appear as regular.
code repository: https://github.com/PaulLaux/eth-hot-wallet
 
# Versions
- ETH-Hot-Wallet (see `package.json`): 0.1.2
- Browser: chrome / firefox 
PaulLaux/eth-hot-wallet#2

**Comment by NekR** [comment]
@PaulLaux Your website works for me in offline mode as expected. That `An unknown error occurred when fetching the script` can be safely ignored, Chrome always says that for offline websites. It's long to explain why, just ignore it :-)

**Comment by PaulLaux** [comment]
Thanks for the info regarding the error,
The thing that got me confused is `bypass for network` checkbox, it make the browser to ignore the service worker.
