### ISSUE TITLE
SPA.md seems to be outdated, and contradicts app-shell.md

### ISSUE THREAD

**Issue by JobLeonard** [NekR/offline-plugin#335]
> We should also specify the `ServiceWorker.navigateFallbackURL`, which instructs the service worker to redirect any non-cached navigation request to the specified route.

https://github.com/NekR/offline-plugin/blob/master/docs/examples/SPA.md

> Previously, to achieve the same effect, `ServiceWorker.navigateFallbackURL` and `AppCache.FALLBACK` option had to be used. `ServiceWorker.navigateFallbackURL` is now deprecated and shouldn't be used at all. Instead, `appShell` should be used.

https://github.com/NekR/offline-plugin/blob/master/docs/app-shell.md

I'm not entirely sure what the correct documentation would be, but given that the SPA one is older I assume it's the outdated one. Since it is the first and only linked example from the README.md, this can lead people astray.

**Comment by NekR** [comment]
Indeed! It's outdated and should be updated, thanks for pointing to it!

**Comment by NekR** [comment]
Would be great to have this for v5 release if `navigateFallbackURL` option is going to be removed.

**Comment by JobLeonard** [comment]
Yes it would!

But as much as I'd like to help out, I'm afraid I can't in practice, since the issue is about documentation for changes in the code and API that I don't know about because it's not consistently documented :P

I guess I can proofread though.
