### ISSUE TITLE
How can I output the sw.js to the root of the project so that it can access to root scope?

### ISSUE THREAD

**Issue by ycmjason** [NekR/offline-plugin#336]
I try to make this plugin work but it's a little bit tricky to get the configuration right. So my current situation is I am exporting the webpack bundle to `/dist/bundle.js`. Since I have set the `output` path, the service worker from this plugin also got outputted into `/dist/sw.js`. And obviously it could not be registered with `/` scope.

Should I create a symbolic link from `/sw.js` to `/dist/sw.js` to solve this? (which seems hacky) or is there another official way to do this?

I have tried setting the `ServiceWorker.output` to `../` but there are some fatal error suggesting it's not possible.

Sorry if this question should not appear in this issues section but I am so eager to get this done by today.

**Comment by NekR** [comment]
You need `ServiceWorker.output` option: https://github.com/NekR/offline-plugin/blob/master/docs/options.md#serviceworker-object--null--false

e.g. `ServiceWorker: { output: '../sw.js }`

It should be all that's required, unless there are some issues with `publicPath`. Let me know if works.

**Comment by ycmjason** [comment]
Never mind, I will use the copy webpack plugin to copy everything into the `dist/` and serve files from there. I guess that's the common way of doing things? is it?

**Comment by NekR** [comment]
I don't think it's a common way. in this case, paths generated in ServiceWorker for caching may not be correct, it's unpredictable.

**Comment by ycmjason** [comment]
could you elaborate? I don't understand why it would be unpredictable.
