### ISSUE TITLE
Cannot re-activate service worker when updating codes

### ISSUE THREAD

**Issue by anhpha** [NekR/offline-plugin#339]
I am using Offline plugin for my SPA, here is may config:
```
new OfflinePlugin({
    publicPath: "/",
    caches: {
       main: [":rest:"],

      // All chunks marked as `additional`, loaded after main section
      // and do not prevent SW to install. Change to `optional` if
      // do not want them to be preloaded at all (cached only when first loaded)
      // additional: ["*.chunk.js", ":externals:"],
      optional: ["*.chunk.js"],
      additional: [":externals:"],
      // optional: [":rest:"],
    },
    // Removes warning for about `additional` section usage
    safeToUseOptionalCaches: true,
    externals: ["/"],
    AppCache: false,
    appShell: "/",
    ServiceWorker: {
      navigateFallbackURL: "/",
    },
    excludes: ["/_ajax/{*.*,.*}"],
  }),
```
Whenever I have a new build, sw.js get changed. However when I refresh the page, service worker will be re-installed but cannot activate. In Application tab of google dev tool, I see sw waiting for activate forever as in attached image.
Info:

- Webpack 3.10

- Offline-plugin: 4.9

![capture](https://user-images.githubusercontent.com/9106858/34913033-fb020970-f923-11e7-9da5-db0332cd35a7.PNG)

**Comment by NekR** [comment]
You probably have another tab of your website open, see this article: https://github.com/NekR/offline-plugin/blob/master/docs/updates.md

**Comment by anhpha** [comment]
Added event and worked. Thank you!

**Comment by NekR** [comment]
@anhpha great! Glad it helped.
