### ISSUE TITLE
Uncaught ReferenceError: DEBUG is not defined

### ISSUE THREAD

**Issue by okonet** [NekR/offline-plugin#34]
![2016-04-07 at 16 25](https://cloud.githubusercontent.com/assets/11071/14354372/505e9a4a-fcdd-11e5-807f-8d95d3d7b0eb.png)

I'm getting this error even after unregistering the worker. Any clue why?

**Comment by okonet** [comment]
![2016-04-07 at 16 26](https://cloud.githubusercontent.com/assets/11071/14354408/7c232038-fcdd-11e5-9f06-1ecb317ed1b8.png)

**Comment by NekR** [comment]
Hmm, `DEBUG` is webpack's compile-time variable. Not sure why it was emitted to real output, maybe because `Babel` made it `DEBUG &&` instead of `if (DEBUG)`.

@sokra any ideas why `DEBUG` might not be handled?

**Comment by NekR** [comment]
@okonet see referenced webpack bug, once it's fixed problem will gone.
