### ISSUE TITLE
Cookie not included on request

### ISSUE THREAD

**Issue by timburgess** [NekR/offline-plugin#340]
We have an infrastructure requirement to use a cookie and I've configured webpack to include credentials with:

```
    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',

      // TB - ensure cookies are also sent
      prefetchRequest: { credentials: 'include' },

      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],

      caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },

      // Removes warning for about `additional` section usage
      safeToUseOptionalCaches: true,

      AppCache: false,
    }),
```

however looking at the sw.js initiated requests, there is no cookie in the request headers. I'm using 4.8.1. and I don't see anything past that in the changes that seem relevant. Ideas?

**Comment by NekR** [comment]
@timburgess for which requests you do not see cookie there? do you need them for your regular AJAX requests or for script/style/images requests?

**Comment by timburgess** [comment]
It's for images specifically.

![screenshot from 2018-01-23 11-06-43](https://user-images.githubusercontent.com/28915/35298522-2b80dd0e-00ce-11e8-8fab-de44d16d5f2d.png)

**Comment by timburgess** [comment]
I've reconfigured to not cache images, etc. But the cookie is not being included on the `main.js` request either:

![screenshot from 2018-01-24 11-18-53](https://user-images.githubusercontent.com/28915/35309487-81452540-00f8-11e8-832d-fca3ae7189e6.png)

**Comment by NekR** [comment]
```prefetchRequest: { credentials: 'include' }```
should be
```
ServiceWorker: {
  prefetchRequest: { credentials: 'include' }
}
```

**Comment by timburgess** [comment]
Awesome. Thankyou!
