### ISSUE TITLE
Not serving cached file from service-worker [help wanted]

### ISSUE THREAD

**Issue by lellefood** [NekR/offline-plugin#344]
Probably I'm doing something wrong but I need some help finding my error.
I've added `offline-plugin` to my project following the tree steps. After fighting a bit with webpack the service worker is served and installs correctly on the client browser.
You can see here it is installed and controlling `localhost/packs`:

![sw-status](https://user-images.githubusercontent.com/7169443/35679290-c35b1278-0756-11e8-9b2e-5f287d8a0725.png)

The source seems also correct and the assets are correctly on cache list:

![sw-source](https://user-images.githubusercontent.com/7169443/35679318-e1c52366-0756-11e8-9ad4-ecd304d505ad.png)

![sw-cache](https://user-images.githubusercontent.com/7169443/35679348-ff2fa52a-0756-11e8-9bef-9b5de36fd76a.png)

But looking to the network I can see that the assets are fetched from the network and not served form the service worker. The actual URL you see is truncated only to the resource name but it is anticipated by `packs/`

![page-network](https://user-images.githubusercontent.com/7169443/35679421-40a6a814-0757-11e8-99d8-73feab228355.png)

Can you help me and tell me where I'm wrong?

**Comment by lellefood** [comment]
Maybe the problem is that request to the js and css files are originated from `localhost:3000/auth/login`?

**Comment by NekR** [comment]
> Maybe the problem is that the request to js and css files are originated from localhost:3000/ and the service worker scope is localhost/packs?

Yes, that's the reason. In your case SW should be in the root of the website.

**Comment by lellefood** [comment]
> In your case SW should be in the root of the website.

So, adding the `ServiceWorker : { output: '../sw.js'}` option should fix it, isn't it?

**Comment by NekR** [comment]
Yes, that should help. If it cannot retrieve sw.js from there, then most likely it isn't there. Make sure it's being copied to your server correctly and served from it.

**Comment by NekR** [comment]
@lellefood you resolved the issue?

**Comment by lellefood** [comment]
Yes, simply the scope wasn't correct. I don't know why I didn't close this earlier. Thanks for your help
