### ISSUE TITLE
Is there anyway to use Onesignal with this plugin together ? 

### ISSUE THREAD

**Issue by lsping8** [NekR/offline-plugin#346]
Hi i am currently implementing Onesignal into my project which uses service worker to allow push notification in browser. But the problem is, Onesignal keep overwriting my current app service worker. Is there any way to allow Onesignal to use together with this plugin ?

**Comment by NekR** [comment]
Sorry, OneSignal is a tool which sells your users information to third-parties so you're able to use it for free. Even if it's somehow possible to use OneSignal with this plugin, I wouldn't support such feature.
