### ISSUE TITLE
Gzip

### ISSUE THREAD

**Issue by peteringram0** [NekR/offline-plugin#347]
How does this work if the assets you are producing are .gz?

the sw.js file only seem to be referencing .js files. Shouldn't this be pointing at .gz files?

**Comment by luigiplr** [comment]
Your server should be handling the delivery of .gz/.br assets! 😄 


Here are some relevant guides:

- NGINX: https://www.digitalocean.com/community/tutorials/how-to-add-the-gzip-module-to-nginx-on-ubuntu-14-04

- APACHE: https://knackforge.com/blog/karalmax/how-enable-gzip-compression-apache

- ISS: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/httpcompression/

Hope this helps!

**Comment by NekR** [comment]
> Shouldn't this be pointing at .gz files?

No. Server sends gzipped files (if configured) and browser transparently decodes them, so it looks like there was no encoding at all, i.e. you as a developer do not need to perform it manually. 

This isn't SW related or this plugin related. SW is just a layout on top of that and it operates on all basic web/http primitives. 

@luigiplr provided great articles to help you getting started with gz. Thanks @luigiplr!
