### ISSUE TITLE
Caching index.html causes revalidation on every update without changes

### ISSUE THREAD

**Issue by goldfire** [NekR/offline-plugin#350]
We have quite a few assets that are dependent on device/browser (different DPI assets, different audio files, etc), so we are using the `additional` and `optional` caches so that we don't cache a bunch of files that will never be needed for that user.

However, when we try to cache the index file (shown in main below, but had the same issue with it in externals), calling `update` without even doing a re-build or changing any files causes it to delete the previous cache and re-download everything. Since we use the events to check for a new update, this causes the user to get stuck in an infinite loop of updating over and over when they load the site.

Am I simply approaching this wrong or is there some other issue? My configuration for offline-plugin is:

```javascript
new OfflinePlugin({
  safeToUseOptionalCaches: true,
  caches: {
    main: ['/'],
    additional: ['*.js?*', '*.css?*', 'assets/*.svg?*'],
    optional: [':rest:'],
  },
  ServiceWorker: {events: true},
  AppCache: {events: true},
})
```

and I generate my index.html with html-webpack-plugin:

```javascript
new HTMLPlugin({
  template: './src/index.template.html',
})
```

**Comment by NekR** [comment]
Sounds bad. Do you have a live version where I could possibly debug it? Feel free to send it to my email (it's on the profile page) if you don't want to share the URL here.

**Comment by goldfire** [comment]
Well, I found what was probably part of the issue. We are load balancing across multiple servers, and each individual server builds with webpack. So, depending on the server you hit, you got a slightly different version value since it was using date. I've now changed it to use the hash from the most recent git commit, but the issue persists. I've also removed the `main` section completely and I'm still seeing the issue.

You can see it at https://beta.goldfire.me/exocraft (click the play now button and just enter anything for the username). You can force the update by calling `game.offline.update()` from the console (change your console's context to `beta.exocraft.io` since it is in an iframe).

**Comment by NekR** [comment]
Can you please disable redirect on `beta.exocraft.io` so it won't redirect to the top frame? It really messes up the debugging and kinda might be the root of your issue.

**Comment by NekR** [comment]
Also, FWIW, if user has set "disable third-part cookie" option in the browser, then ServiceWorkers from iframes won't be registered.

**Comment by goldfire** [comment]
We can't disable the redirect because our auth system is based on the game being wrapped with the goldfire.me site. I wasn't aware of the third party cookie issue, and though that certainly isn't the current issue, knowing that may make this implementation useless for us after all.

**Comment by NekR** [comment]
That's unfortunate because Chrome's SW debugging tools behave weirdly hen
it's in an iframe, actually they almost don't work. But for now I may guess
that your server performs an redirect when main page is being downloaded
from the SW and tries to redirect it to the other domain. And that somehow
messes up the caching (e.g. update cannot be applied and wants to perform
it again and again), but I'm not sure tbh.

**Comment by goldfire** [comment]
The redirect is actually in the app code, not performed on the server, so I can't imagine it has to do with that. I suspect I'm just configuring something wrong because it seems to work fine on localhost with the same iframe setup.

**Comment by goldfire** [comment]
Actually, I hadn't thought to do a diff on the sw.js files on each server since the versions were now the same. The diff shows that the hash on the vendor file is different on each server (the has that webpack generates). Since the hash on vendor is different, the hash on index.html is different as well. Each server should be generating the exact same file, not quite sure why they would have different hashes.

**Comment by goldfire** [comment]
Yes, this turned out to be the issue. For anyone running into the same problem, this webpack docs page on caching proved very helpful: https://webpack.js.org/guides/caching/.

**Comment by GGAlanSmithee** [comment]
Can't you generate the app on one physical computer and distribute it to all nodes?

**Comment by GGAlanSmithee** [comment]
Ah, glad you got it sorted.
