### ISSUE TITLE
Issues with Webpack 4

### ISSUE THREAD

**Issue by lukeshiru** [NekR/offline-plugin#351]
Hi!

There is a problem with the [recently released](https://github.com/webpack/webpack/releases) Webpack 4. It seems to be an issue with this plugin ussing `UglifyJsPlugin`, that now is deprecated. The following error is shown:

```
webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
```

If I remove offline-plugin, then this error isn't there anymore.

**Comment by luigiplr** [comment]
Until the plugin is updated you can get around this by disabling minification via the configuration parameter. 😃 (if you want it to be minified you will need to do this yourself as a post-build step)

![](https://i.imgur.com/dlh8r1b.png)

**Comment by csantiago132** [comment]
@luigiplr nice! Will implement like this when I update my branch, great workaround and thanks for the example

**Comment by NekR** [comment]
Yes, I'm aware of the issue, but have no time to fix it. Any help is welcome. @luigiplr thanks for a workaround!
