### ISSUE TITLE
appcache: index.html is not updated, assets updated

### ISSUE THREAD

**Issue by whitecolor** [NekR/offline-plugin#356]
Problem refers to AppCache:

I have following manifest.appcache generated:
```
CACHE MANIFEST
#ver:2018-3-11 13:35:39
#plugin:4.9.0

CACHE:
/bundles/18f4426789edc9a053f7.worker.js
/bundles/1003.lp.ru-a44a7d31aed2d2ca761b.js
/bundles/1003.geonames.ru-462503c69cce3478b69e.js
/bundles/1003.geonames.en-dc8c20d9907dea8ddcc5.js
/bundles/cities15000-adc4e48b045b562cb739.js
/bundles/app-a8be2215cc9efc183576.js
/bundles/fonts-1aefc31d27b1f6d39445.js
/bundles/vendor-54dd93533d758f6efd98.js
/bundles/../

NETWORK:
*
```
After new version has arrived (new assets/manifest/index), while update
index.html (loaded from /bundles/../index.html) **is not updated each time**, but assets are updated and this actually causes that on next reload page being broke because browser tries to loads resources which are in not actual cached `index.html` version, which was not updated.

`Index.htmi` has `Cache-Control:no-cache` header.

What can be the reason for this?

**Comment by NekR** [comment]
`/bundles/../` this actually looks like a broken path (generated incorrectly). I guess it should be just `/`, right?

e.g. you have a `/` page and load assets on that page as `/bundles/app-a8be2215cc9efc183576.js`, etc. right?

**Comment by whitecolor** [comment]
> /bundles/../ this actually looks like a broken path (generated incorrectly). I guess it should be just /, right?

Well right, though `/bundles/../`  actually should be equals to`/`, so I wouldn't call it broken.

> e.g. you have a / page and load assets on that page as /bundles/app-a8be2215cc9efc183576.js, etc. right?

Yes.
I have following  webpack `output` config:

```
    publicPath: '/bundles/'
```

and for HTMLPlugin:
```
filename: '../index.html',
```

**Comment by NekR** [comment]
Yeah, I see now why it generated such url, because of `'../index.html'`. Indeed, it should be a valid url, afaik, but who knows that AppCache.

Assuming that's valid URL for the AppCache, I have no idea why it fails. The generated manifest looks alright to me. Can you share a url of your website so I could take a look at the problem? Also, in what browser you're testing it?

**Comment by whitecolor** [comment]
> Yeah, I see now why it generated such url, because of '../index.html'. Indeed, it should be a valid url, afaik, but who knows that AppCache.

Is it possible to with plugin settings to override this path?

I'm testing on chrome desktop (http), and iOS safari.

Anyway, I try first to find out if the problem persists with another path like '/' or `/index.html`, and if it will persist (hope it will not) I'll point to the published version.

**Comment by NekR** [comment]
@whitecolor  Yes, it should be possible to override. Have you had a chance to check if problem persist with other paths? You may even change it manually after a build, just for testing purposes.

**Comment by whitecolor** [comment]
Yes, I'm testing, thanks for the concern, you know, I think that the problem was probably the absence of `no-cache` header on served index.html, from the moment I ensured the header I didn't experienced it. So I will close the issue, for now If I experience it again will reopen.

**Comment by NekR** [comment]
Sounds good, thanks for the update 👍
