### ISSUE TITLE
Determine if app is running in offline mode

### ISSUE THREAD

**Issue by adi-darachi** [NekR/offline-plugin#359]
It feels  a bit obvious but I could not find it the documentation.
I'm looking for a way to determine if the app is running in offline mode.

Thanks in advance!

**Comment by DJTB** [comment]
https://github.com/ReactTraining/react-network

the main code is `window.navigator.onLine`

**Comment by NekR** [comment]
Yes, `navigator.onLine` and `online` and `offline` events on `window`.
See example here: https://github.com/NekR/offline-plugin-pwa/blob/master/src/main.js#L52-L69
