### ISSUE TITLE
How to integrate Firebase Cloud Messaging(FCM) push notifications with offline-plugin

### ISSUE THREAD

**Issue by dsaket** [NekR/offline-plugin#360]
I'm using offline-plugin to generate the service-worker file to cache static assets which is working as expected. Now I also need to implement **Firebase's FCM service** (for push notifications) which requires a service worker file named `firebase-messaging-sw.js` which would contain the background message handling code ([See docs](https://firebase.google.com/docs/cloud-messaging/js/receive)). 

The solutions that I have found so far is,

1. Use `importScripts()` in the generated sw file to load the `firebase-messaging-sw.js` file. However `offline-plugin` doesn't seem to have any option for that. :(
2. Somehow append the code in the generated SW file at the end and let FCM know about the existing service worker file.

However, I currently have no clue how to implement any of the above solutions. Please help me out with this.

**EDIT:** I came across the `Serviceworker.entry` config option but not sure how to use this. Can someone please provide an example. Also how to get the `registration` object after install(I would need to pass the `registration` object to FCM) as I am using the `runtime.install()` method.

**EDIT 2** Ok...thanks to the `Serviceworker.entry` option...I finally am able to inject code into the generated SW file. Also I am able to get the `registration` object by doing the `navigator.serviceWorker.ready.then((reg) => ... )`.

**Comment by musfiqurcse** [comment]
@dsaket > Can you kindly share in details about how you inject firebase code in service worker? It will be really helpful.
