### ISSUE TITLE
[Feature request] Cache then network

### ISSUE THREAD

**Issue by JouzaLoL** [NekR/offline-plugin#361]
Hi, would it be possible to add a [cache then network](https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#cache-then-network) strategy? Right now I'm using the network first, which is better than nothing, but it's still slow on slow networks. Cache first would allow the end user to see the cached version, and then whenever the new version is fetched from network, see that instead.

**Comment by stern-shawn** [comment]
https://github.com/NekR/offline-plugin/blob/master/docs/options.md#responsestrategy-cache-first--network-first

The plugin's default is 'cache-first' already, which then falls back to requesting from the network. No settings required!

**Comment by JouzaLoL** [comment]
Yes, however cache-first and cache then network is different. Cache first consults the cache, loads the page from cache and that's it. Only if the cache is empty it loads from network.


Cache then network tries to load it from cache, and regardless of  success or failure of loading from data, it tries to load new data from network. This way, the user gets the speed of cached data along with the updated data from network.

This is a perfect strategy for apps that are used over slow networks and at the same time updated data is critical to them.
________________________________

**Comment by whitecolor** [comment]
maybe you should by yourself reload the page on `update ready` event?

**Comment by NekR** [comment]
Not sure if this would be possible for the plugin, but I'll think about it. It mostly caches webpack generated assets and updating them independently isn't a good idea, it simply will stop working and users may stuck with broken build and broken SW cache.

**Comment by whitecolor** [comment]
@NekR actually now I don't think that is it really a good idea (to reload the page without user prompt), I believe it should be a userland
