### ISSUE TITLE
offline-plugin still loading even I delete the package

### ISSUE THREAD

**Issue by iroy2000** [NekR/offline-plugin#367]
I have deleted the offline plugin few months back, but why it is still loading again everytime when I close my browser? Currently I need to delete that everytime when it shows up manually.  How to clean that once and for all ?

![screen shot 2018-04-12 at 9 44 17 am](https://user-images.githubusercontent.com/487520/38691620-356b7cd4-3e36-11e8-8932-b267bb3502c9.png)

**Comment by NekR** [comment]
Removing the package obviously doesn't remove already installed caches and ServiceWorker from the browsers.

This may help: https://medium.com/@nekrtemplar/self-destroying-serviceworker-73d62921d717

**Comment by yeyuguo** [comment]
i have  the same problem!!!!!
