### ISSUE TITLE
Serivce worker failed to install

### ISSUE THREAD

**Issue by pavankumarkatakam** [NekR/offline-plugin#37]
I just added the plugin to webpack config with the below configuration, 
```
  new OfflinePlugin({
            AppCache: false,
            caches: 'all',
            scope: '/',
            relativePaths: true,
            updateStrategy: 'hash'
        }),
```
but it is only firing the install event but not the actiavte event, so i debugged in the `chrome://serviceworker-internals/` , there i found this line
`Error: {"columnNumber":-1,"lineNumber":-1,"message":"ServiceWorker failed to install","sourceURL":""}` but this error is telling that it is failed, but why?

**Comment by pavankumarkatakam** [comment]
And im using the inbuilt install method 
`require('offline-plugin/runtime').install();`

**Comment by pavankumarkatakam** [comment]
When debugging using the Firefox this error is reported
`Service worker event waitUntil() was passed a promise that rejected with 'TypeError: Argument 2 of WorkerGlobalScope.fetch can't be converted to a dictionary.'.`

**Comment by NekR** [comment]
@pavankumarkatakam what version of `offline-plugin` you are using?

**Comment by pavankumarkatakam** [comment]
From Package.json file it is 3.0.0

```
{
  "name": "offline-plugin",
  "version": "3.0.0",
```

**Comment by NekR** [comment]
If you are using `v3`, then it mostly likely is this: https://github.com/NekR/offline-plugin/pull/35
So, just update then.

**Comment by NekR** [comment]
Yeah, it's `v3`. You can use `npm install offline-plugin@next` to get relatively stable version on next release (`v3` currently).

**Comment by pavankumarkatakam** [comment]
Yeah, updating to v3.0.1 solved my problem closing it.

**Comment by NekR** [comment]
Btw, It's probably better to set you dependency in `package.json` right to `"3.0.1"` instated to `"^3.0.1"`, because things may change until final release of `v3`.

**Comment by pavankumarkatakam** [comment]
Yeah, I have changed `package.json` file already.
