### ISSUE TITLE
`isNotRedirectedResponse` function is used without an argument

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#370]
https://github.com/NekR/offline-plugin/commit/fbdd643f9886ed4f3563b5e433f6aad3922ede60#diff-1d7b31069861fdf22fcaeba0f48ba565R559

**Comment by NekR** [comment]
@Tuch

https://github.com/NekR/offline-plugin/releases/tag/v4.9.1
https://github.com/NekR/offline-plugin/releases/tag/v5.0.0

**Comment by Tuch** [comment]
@NekR good job, and thank you :thumbsup: :thumbsup: :thumbsup:
