### ISSUE TITLE
Proper error messages

### ISSUE THREAD

**Issue by cornerman** [NekR/offline-plugin#371]
Just had a case, where the config for the `entry` path to the js-file was wrong. In this case, I just got an error `Something went wrong`. Can we improve this message to let the user know that a file cannot be found?

**Comment by NekR** [comment]
The reason of `Something went wrong` error is that something unknown went wrong. In your case it was a missing file. If you know a way to improve and detect what error actually happened -- feel free to make a PR, I'll be happy to merge it.

**Comment by NekR** [comment]
Okay, do it.

**Comment by NekR** [comment]
If someone wants to do this, feel free to make a PR.
