### ISSUE TITLE
Error: webpack.optimize.UglifyJsPlugin has been removed

### ISSUE THREAD

**Issue by karolisgrinkevicius** [NekR/offline-plugin#372]
I'm getting this error using latest webpack version:
`Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead`.

**Comment by NekR** [comment]
A version with wepback 4 support isn't release yet.

**Comment by tim-soft** [comment]
Do you know what's involved for a fix?

**Comment by NekR** [comment]
Fix is done, I just need to do other things for the release to make it. Webpack 4 put everyone in a position where a major release should be done.

**Comment by NekR** [comment]
Okay, so v5 was released few days ago so this should work now.
