### ISSUE TITLE
Content not being loaded from cache

### ISSUE THREAD

**Issue by melloc01** [NekR/offline-plugin#374]
Hello :wave: 

I'm using Offline Plugin to cache a relatively big app and there's something weird happening.

The symptom:
Assets are being cached but not retrieved from cache.

The cause (my guess):
There's no `Clients` associated with this service-worker as seen here:
![image](https://user-images.githubusercontent.com/4994258/39069972-f6c7862a-44b7-11e8-910a-6947890cbd17.png)

On `dev.to` it shows a client as seen here:
![image](https://user-images.githubusercontent.com/4994258/39070011-1f96578e-44b8-11e8-9d1c-898965ebbd8a.png)

My config:
```js

        new OfflinePlugin({
            excludes: ['**/*.map'],
            ServiceWorker: {
                minify: false,
                prefetchRequest: { credentials: 'include' }
            },
            AppCache: {}
        })
```

**Comment by melloc01** [comment]
Turns out I was serving my service worker from: `/public/assets/sw.js` so its scope is limited to requests that has its origins in `/public/assets/`, `index.html` stays on the `/` (call it root) scope.

I had to set the header `Service-Worker-Allowed: /" so I could config my plugin with `ServiceWorker.scope = /` and everything worked fine : )

**Comment by NekR** [comment]
@melloc01 hey! great that you were able to solve 👌feel free to open issues if something

**Comment by melloc01** [comment]
Thanks @NekR! Appreciate your effort here :grinning: 

I am kind of concerned about sw updates with caches generated by other libs like [svgstore](https://github.com/mrsum/webpack-svgstore-plugin), didn't test thoroughly still, but I remember seeing some 404 until I hard reload, might not be related.

**Comment by NekR** [comment]
@melloc01 if it isn't processed through webpack when it isn't being cached by default. You need to add them manually to `externals` option. Then they will be updating as other assets -- when a webpack build happens.
