### ISSUE TITLE
Described `rewrites` default function in the docs [Edited]

### ISSUE THREAD

**Issue by bjornbos** [NekR/offline-plugin#378]
I've successfully installed the offline-plugin. In my Webpack config I have the output.publicPath set to the URL of the CDN that is serving the static files (https://subdomain.cloudfront.net/assets/). The Service Worker is correctly referencing all of the files, but it's also including the "root" URL of the CDN (https://subdomain.cloudfront.net/assets/). This results in an error, as there is no file present in that URL. I'm trying to exclude that URL by adding it to the excludes option, but this seems to be ignored. How do I keep the public path root url from being listed in the sw.js assets?

**Comment by bjornbos** [comment]
Ah, figured it out. Apparently there is a default rewrite rule that rewrites index.html to /. So now I've added index.html to the excludes and everything is fine.

**Comment by NekR** [comment]
Yeah, it seems that default function isn't shown in the docs.
