### ISSUE TITLE
Minify option auto-detection not working on webpack 4

### ISSUE THREAD

**Issue by edmorley** [NekR/offline-plugin#379]
Hi :-)

The [options docs](https://github.com/NekR/offline-plugin/blob/master/docs/options.md) say:
> * **`minify`**: `boolean`. If set to `true` or `false`, the `ServiceWorker`'s output will be minified or not accordingly. If set to something else, the `ServiceWorker` output will be minified **if** you are using `webpack.optimize.UglifyJsPlugin` in your configuration.  
_Default:_ `null`

The check for that uses `plugins` to determine whether the user has activated minification:
https://github.com/NekR/offline-plugin/blob/v5.0.2/src/service-worker.js#L143-L146

However in webpack 4, UglifyJsPlugin is typically not added to plugins, but instead used via the new `optimization.minimizers` option (the plugin is added there by default, but people can override) which is toggled via the `optimization.minimize` bool:
https://github.com/webpack/webpack/blob/v4.6.0/lib/WebpackOptionsDefaulter.js#L270-L289
https://github.com/webpack/webpack/blob/v4.6.0/lib/WebpackOptionsApply.js#L334-L338

To allow the `minify` option auto-detection to work under both webpack 2-3 and webpack 4, I guess the conditional needs to be a combination of the existing plugins check and also `optimization.minimize`?

**Comment by NekR** [comment]
Hi @edmorley!

I think the definition of `ServiceWorker.minify` is quite right. It exactly does what it says.

> However in webpack 4, UglifyJsPlugin is typically not added to plugins, but instead used via the new optimization.minimizers option (the plugin is added there by default, but people can override) which is toggled via the optimization.minimize bool:

The `optimization.minimize` supposed to add Uglify plugin to plugins list, unless you're using some custom minifier. 

> To allow the minify option auto-detection to work under both webpack 2-3 and webpack 4, I guess the conditional needs to be a combination of the existing plugins check and also optimization.minimize?

That would be too complicated, I think. I would prefer it to be as is, but if it doesn't work and isn't able to catch the plugin added by `optimization.minimize`, then it probably has to be changed.

**Comment by edmorley** [comment]
Many thanks :-)

**Comment by NekR** [comment]
Should be fixed now: https://github.com/NekR/offline-plugin/releases/tag/v5.0.3
