### ISSUE TITLE
Support for serviceWorker events

### ISSUE THREAD

**Issue by pavankumarkatakam** [NekR/offline-plugin#38]
SW has some events like `install` , `activated` , but there is also special events like `push` and `sync`, keep these events in the config so that generate sw.js file will have this like

```
new OfflinePlugin({
            AppCache: false,
            caches: 'all',
            scope: '',
            relativePaths: true,
            updateStrategy: 'hash',
            events:{
                push:function(){
                   // Developer choice
                }
            }
        }),
```

Or any much better way it is okay.

**Comment by NekR** [comment]
There is a `entry` option, which can be point to your JS file which will be used as an entry for ServiceWorker. Like this:

```js
// webpack.config.js
new OfflinePlugin({
    AppCache: false,
    caches: 'all',
    scope: '',
    relativePaths: true,
    updateStrategy: 'hash',
    entry: 'sw-handler.js'
}),
```

```js
// sw-handler.js

self.addEventListener('push', () => ...)

```

**Comment by pavankumarkatakam** [comment]
Oh thanks for response but the config is 

// webpack.config.js
new OfflinePlugin({
    AppCache: false,
    caches: 'all',
    scope: '',
    relativePaths: true,
    updateStrategy: 'hash',
    ServiceWorker:{
      entry: 'sw-handler.js'
    }
}),

**Comment by NekR** [comment]
Yeah, right, my bad..
