### ISSUE TITLE
suggestion: `appShell` should make the SW ignore the generated file sw.js

### ISSUE THREAD

**Issue by julienw** [NekR/offline-plugin#383]
With the current `appShell` option, when requesting the generated file sw.js, the SW serves the index file. This is quite confusing for the generated `sw.js` file that actually exists but because it's not in the list of the SW assets, it's being ignored.

**Comment by NekR** [comment]
Yeah, it's a bit. Though this happens only for navigation requests. But adding this makes sense.

**Comment by julienw** [comment]
Yep. We got an error where reading the actual `sw.js` file helped finding the issue. But we could only look at it using eg `curl` and not load it from the browser.

**Comment by NekR** [comment]
Makes sense. Thanks for reporting this. 🙌

**Comment by NekR** [comment]
https://github.com/NekR/offline-plugin/releases/tag/v5.0.4

**Comment by julienw** [comment]
Nice, I didn't know that service workers had a `location` property. TIL :) Thanks !
