### ISSUE TITLE
Failed to execute 'fetch' on 'ServiceWorkerGlobalScope'

### ISSUE THREAD

**Issue by matheusml** [NekR/offline-plugin#385]
Hey,

I'm getting this error:

`Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode.

This is my config:

```js
new OfflinePlugin({
  externals: ["/"],
  responseStrategy: "network-first"
})
```

**Comment by NekR** [comment]
https://github.com/paulirish/caltrainschedule.io/issues/49

Seems to be Chromium's DevTools issue, but can be fixed on the plugin's side as well.

**Comment by NekR** [comment]
https://github.com/NekR/offline-plugin/releases/tag/v5.0.4
