### ISSUE TITLE
Mix response strategies

### ISSUE THREAD

**Issue by sevenstories** [NekR/offline-plugin#386]
Is it possible to mix response strategies at all?
I'm currently writing an angular application that requires offline functionality. We want to be able to pre cache the application as well as cache some requests with data specific to the user after login. This user data needs to be network first, as the data could have been updated while logged in (we dont need to worry too much about security with this, just that we can get the last known data while offline), whereas the application itself will be cache-first. Is this currently possible or even a likely future addition?

**Comment by NekR** [comment]
This is the most requested feature, and while it is, there is no one to implement it. So I guess it isn't that important to people 🤷🏻‍♀️ or they just move to another library.

**Comment by sevenstories** [comment]
Thanks for the quick response! I might have a look at attempting it myself 👍
