### ISSUE TITLE
Service worker on safari loading encrypted js

### ISSUE THREAD

**Issue by Pranab16** [NekR/offline-plugin#390]
I am using code-splitting through react-loadable and service workers through offline-plugin. It works perfectly in chrome and firefox.

But it is not working properly on Safari. When I go to a different route, chunk js is loaded for that route and it comes from service-worker as expected but service-worker returns encrypted js (I guess) for eg: N��}���S������^+����

Safari version - 11.1.1 
Same is happening in iOS Safari

**Comment by NekR** [comment]
Maybe something wrong with encoding on your web server or with files you generate. Not sure how it might be related to `offline-plugin`.

**Comment by Pranab16** [comment]
Is there any way to disable service worker for safari browsers with `offline-plugin`, until I am not able to figure out the issue?

**Comment by Pranab16** [comment]
@NekR I read somewhere we can use sw-toolbox with offline-plugin but couldn't find any example. Can you help me with it? 

Thanks
