### ISSUE TITLE
why call the "install" function in "offline-plugin/runtime", but the function is "exports.install = function() {};"??

### ISSUE THREAD

**Issue by daffy6537** [NekR/offline-plugin#399]
HERE is code in offline-plugin/runtime.js：

the export function install is noop!

var warn = "offline-plugin: runtime was installed without OfflinePlugin being added to the webpack.config.js. See https://goo.gl/2Ca7NO for details.";

if (window.console) {
  if (console.info) {
    console.info(warn);
  } else if (console.log) {
    console.log(warn);
  }
}

exports.install = function() {};
exports.applyUpdate = function() {};
exports.update = function() {};

**Comment by NekR** [comment]
It's being dynamically replaced with actual implementation when you add plugin's instance to your config.
