### ISSUE TITLE
Runtime doesn't really seem to do anything

### ISSUE THREAD

**Issue by Vinnl** [NekR/offline-plugin#41]
Hi, I'm not sure if this is a bug, but it looks like one... I'm using

    "offline-plugin": "^2.1.0",

I added the following code:

    let runtime = require('offline-plugin/runtime');
    console.log('Runtime', runtime.install.toString());

And got the following output, in Firefox Developer Edition 47.0a2 and regular Firefox:

> Runtime function () {}

In other words: the install function doesn't seem to do anything. I'm not sure if I'm doing something wrong or whether it's a bug. I've added the plugin without any options, as they were said to be optional:

    new OfflinePlugin()

(And if relevant: my code, although without the debugging statements, is located [at Gitlab](https://gitlab.com/Vinnl/makeapoint/tree/master).)

**Comment by NekR** [comment]
Hi @Vinnl, runtime is supposed to be a noop when you are running in dev mode, e.g. when you do not add `new OfflinePlugin()` to your plugins list. This way you do not need to replace runtime from source code when you are in dev-mode. However, when you add `new OfflinePlugin()` runtime is overridden by real runtime content.

Do you have empty runtime on production?

**Comment by Vinnl** [comment]
Hi @NekR, the same is happening in production, unfortunately. I'm still a bit new to Webpack, so it _might_ be that I'm somehow running in development mode. That said, I don't think so. This is what I run:

    webpack -p --config webpack.prd.config.js

The output path is `/build/`, and if I go there and then run `python -m SimpleHTTPServer 9000`, I still get this output: 

>     Runtime function () {}

**Comment by NekR** [comment]
Okay, I will try to run your code, maybe some conflict with other loaders.

**Comment by Vinnl** [comment]
That's very dedicated - let me know if there's anything I should try. I feel a bit guilty since it's not unlikely that it's me doing something wrong...

**Comment by NekR** [comment]
I just do not know how to help you in other way. It's supposed to work and only thing which can cause it to not work is other loaders.

**Comment by NekR** [comment]
This was this issue: https://github.com/webpack/webpack/issues/2377
Just fixed and published as `2.1.1`. Try it please.

**Comment by Vinnl** [comment]
@NekR Excellent, it now works exactly as expected!
