### ISSUE TITLE
Caching external API requests

### ISSUE THREAD

**Issue by fbnklmn** [NekR/offline-plugin#413]
Hi NekR,

For a project I'm using react boilerplate, which uses your plugin to provide offline experience.

After trying to add the API request(s) to "externals" like this:

```
new OfflinePlugin({
  relativePaths: false,
  publicPath: '/',
  appShell: '/',

  // No need to cache .htaccess. See http://mxs.is/googmp,
  // this is applied before any match in `caches` section
  excludes: ['.htaccess'],

  caches: {
    main: [':rest:'],

    // All chunks marked as `additional`, loaded after main section
    // and do not prevent SW to install. Change to `optional` if
    // do not want them to be preloaded at all (cached only when first loaded)
    additional: ['*.chunk.js'],
  },

  // Removes warning for about `additional` section usage
  safeToUseOptionalCaches: true,
}),
```

It didn't work out:

![chrome_2018-09-18_15-29-17](https://user-images.githubusercontent.com/40788739/45690873-a3d51600-bb57-11e8-8cc6-821937c91883.png)

![chrome_2018-09-18_15-31-29](https://user-images.githubusercontent.com/40788739/45690937-cbc47980-bb57-11e8-92d0-805e17cef529.png)

I then searched in the issues here and only found this: https://github.com/NekR/offline-plugin/issues/64

So currently I'm not sure, if 1. I do it wrong, or 2. its not implemented.

May you help me out? :)

**Comment by GGAlanSmithee** [comment]
@fbnklmn did you try the [suggested workaround](https://github.com/NekR/offline-plugin/issues/64#issuecomment-223949743) from the issue you linked?

**Comment by fbnklmn** [comment]
@GGAlanSmithee Not yet, really. I can give it a try though. Just thought there should be something else than a "workaround" after two years :P

**Comment by GGAlanSmithee** [comment]
@fbnklmn okay, please try it if possible and tell us how it went.

The wording "workaround" is a bit unfortunate by me, since it's not really the case - the feature is simply not implemented (yet). Given how relatively easy it is to accomplish this might a contributing factor as to why that is the case :)

**Comment by GGAlanSmithee** [comment]
@fbnklmn did you have a chance to try the suggested solution?

**Comment by fbnklmn** [comment]
@GGAlanSmithee Yes, and it kinda works, although I think a native implementation in the offline plugin would be more convenient. Maybe even with some caching strategies.

**Comment by GGAlanSmithee** [comment]
@fbnklmn ok great,

to quote @NekR in #64 

> I am not sure yet. It's kind of complex and has to be done right.

So, yeah, probably there needs to be a native implementation eventually, but probably not right now, unless someone wants to contribute it :)
