### ISSUE TITLE
appShell config does not correctly serve js and css assets for deep level url paths

### ISSUE THREAD

**Issue by maksimsemenov** [NekR/offline-plugin#414]
I'm using an offline-plugin with appShell option enabled:
```
{
      AppCache: false,
      appShell: '/',
      externals: ['index.html', 'https://fonts.googleapis.com/css?family=Ubuntu'],
      caches: {
        main: ['index.html', ':rest:'],
        additional: [':externals:']
      },
      safeToUseOptionalCaches: true,
      responseStrategy: 'cache-first',
      ServiceWorker: {
        events: true,
        entry: './src/sw/index.js',
        output: 'sw.js',
        navigationPreload: false
      },
      version: '[hash]'
}
```
So when I'm trying to navigate to the index page or a one level deeper everything works fine:
```
https://www.store.com
https://www.store.com/orders
```
service worker serves correct js and css assets:
```
https://www.store.com/app.js
https://www.store.com/app.css
```

However, if I'm trying to load a page from the deeper level, it returns 404 for js and css files. So for:
```
https://www.store.com/orders/
https://www.store.com/orders/orderId
```
browser tries to load:
```
https://www.store.com/orders/app.js
https://www.store.com/orders/app.css
```
and service worker returns 404

Not sure if it is an offline-plugin issue or if I'm missing something. Please let me know if there is a workaround.

**Comment by maksimsemenov** [comment]
It turns out I didn't set `publicPath` correctly.

**Comment by GGAlanSmithee** [comment]
@maksimsemenov good that you figured it out, for future googlers: https://github.com/NekR/offline-plugin/blob/master/docs/options.md#publicpath-string
