### ISSUE TITLE
API + Images/JS/CSS cache

### ISSUE THREAD

**Issue by kodeine** [NekR/offline-plugin#419]
i wonder if its possible to cache the entire website (all the images and js and css files) api get requests except api post/put/delete requests.

**Comment by GGAlanSmithee** [comment]
@kodeine - in general it should be possible to cache any static assets according to the service-worker spec. Regarding caching API requests, there is no built-in solution for this ATM, but it is possible with some coding, see https://github.com/NekR/offline-plugin/issues/64
