### ISSUE TITLE
External assets not added to manifest.appcache

### ISSUE THREAD

**Issue by ncapdevi** [NekR/offline-plugin#424]
Adding external resources, e.g.,
 `        externals: [
          "https://fonts.googleapis.com/css?family=Lato|Oswald"
]` will add it to sw.js but doesn't seem to add the resource to the manifest.appcache and so doesn't work on browsers that don't have serviceworker support.

**Comment by darnaudov** [comment]
Any update guys on this one ?

**Comment by GGAlanSmithee** [comment]
See @NekR's answer in #85 

> AppCache doesn't support cross-origin caches over HTTPS. Do you use https on your site?
