### ISSUE TITLE
Add support for terser-webpack-plugin (webpack@4.26.0+)

### ISSUE THREAD

**Issue by pleunv** [NekR/offline-plugin#426]
Webpack 4.26.0 switched from using `uglifyjs-webpack-plugin` to `terser-webpack-plugin`. Since OfflinePlugin seems to partly piggyback off webpack's minifier but also contains uglifyjs-specific code this is now throwing up the following error:

```
OfflinePlugin: uglifyjs-webpack-plugin is required to preform a minification
```

Messed around a little bit myself but adding terser support while maintaining uglifyjs support for `< webpack@4.26.0` involves a bit more than updating the import, unfortunately.

Those running into this issue can meanwhile explicitly add `uglifyjs-webpack-plugin` to the dev dependencies until this is resolved.

**Comment by GGAlanSmithee** [comment]
@pleunv thanks for the report :+1:

**Comment by Bobgy** [comment]
I tried to patch offline-plugin in my forked branch about this issue. What I did was simply passing `uglifyOptions` as `terserOptions` and that fixed the issue for me because terser seems to only have new options over uglifyjs.

I will try to clean up the implementation and submit a PR.

**Comment by Bobgy** [comment]
@GGAlanSmithee I've submitted the PR. Any chance you can merge it?
It's passing CI, so I need someone for code review.

**Comment by GGAlanSmithee** [comment]
@Bobgy I've left a few comments, and I think we can merge this. However, only @NekR can actually deploy this to npm, so he will have the last word.
