### ISSUE TITLE
I'm getting no internet connection on checked offline in network.

### ISSUE THREAD

**Issue by Reollyn** [NekR/offline-plugin#427]
Hello,

I'm trying to implement `offline-plugin` with `vue.js` but I can't make it work. The `offline-plugin` is storing the files into the cache but when I check the offline checkbox in the network tab or when I turn off the wi-fi then I'm getting the `No internet` message. So it won't render it from cache. Do I miss something?

main.js

```
import * as OfflinePluginRuntime from 'offline-plugin/runtime'

OfflinePluginRuntime.install({
  onUpdateReady: () => {
    // Tells to new SW to take control immediately
    runtime.applyUpdate()
  },
  onUpdated: () => {
    // Reload the webpage to load into the new version
    window.location.reload()
  }
})
```

webpack.base.conf.js

```
const OfflinePlugin = require('offline-plugin');

plugins: [
    ...
    new OfflinePlugin({
      ServiceWorker: {
        events: true
      }
    })
  ],
```

<img width="884" alt="screenshot 2018-11-29 at 16 15 47" src="https://user-images.githubusercontent.com/20517519/49231383-1bde7880-f3f2-11e8-8648-024e7b54f61d.png">

**Comment by rafi16jan** [comment]
@Reollyn I'm also experiencing this issue
