### ISSUE TITLE
Modify generated web worker sw.js

### ISSUE THREAD

**Issue by F-Moody** [NekR/offline-plugin#440]
Hello there,
just wanted to know if there's a way to modify (add event listener and callbacks ) to the generated sw.js. I mean before generating it such as we don't have to re modify it after every build

**Comment by GGAlanSmithee** [comment]
Hi @F-Moody 

To enable events, use the [ServiceWorker](https://github.com/NekR/offline-plugin/blob/master/docs/options.md#serviceworker-object--null--false) option.

For available events, see the [runtime events](https://github.com/NekR/offline-plugin/blob/master/docs/runtime.md#events) config.

**Comment by F-Moody** [comment]
Hi,
thanks for the answer, i get that but what i'm wondering is where should i put the code for that event?

**Comment by GGAlanSmithee** [comment]
@F-Moody In your clients entry point, where you install (`require('offline-plugin/runtime').install()`) the service worker.

See the example code [here](https://github.com/NekR/offline-plugin-pwa/blob/master/src/main.js#L5)

**Comment by F-Moody** [comment]
Great, thanks for the kindness!

**Comment by GGAlanSmithee** [comment]
@F-Moody no problems. Thanks for using this plugin. Will close this issue now.
