### ISSUE TITLE
Live site never updates until hard-refresh

### ISSUE THREAD

**Issue by tr1s** [NekR/offline-plugin#443]
This is more of a general inquiry, I'm not sure if this is a bug or if I need to have more in-depth configuration.

Every time I push new updates to my live site the updates are never visible until I hard refresh (cmd + shift + r). The average user won't know this, and I don't even think it's possible on mobile. So is it even worth it to have offline functionality if the updates are never going to work for returning visitors? I've closed the live site tab, and even chrome, but the updates to go live until hard-refresh.

How have people managed this? I may just remove it from my site, but I'm curious if there's ways to get the best of both worlds. Thanks!

I have my configuration on my [webpack-boilerplate](https://github.com/tr1s/tris-webpack-boilerplate) for reference. This is what I use for my personal static sites I'm referring to. Once I push to master they go live on Netlify.

**Comment by tr1s** [comment]
Any ideas on this? My website on mobile is 3 website updates behind.. I don't even know how to hard-refresh on mobile. I can only see my latest updates on chrome if I hard refresh.

Would love to know how to configure this properly. If anyone can help it would be greatly appreciated!

**Comment by GGAlanSmithee** [comment]
Hi @tr1s 

Hard to say exactly what's wrong in your situation, but here are some steps you can try.

1. You might be caching the sw.sj file on your webserver, making it not updating (this is a common gotcha), see [troubleshooting](https://github.com/NekR/offline-plugin/blob/master/docs/troubleshooting.md#the-serviceworker-is-not-being-updated) for ionfo on this and more.
2. You might be using the wrong [update strategy](https://github.com/NekR/offline-plugin/blob/master/docs/update-strategies.md)
3. Related to above, there might be a problem with files hashes, making the sw not identifying them as changed (this is unlikely)
4. For a better understanding of how updates are applied to a ServiceWorker, and for additional information on debugging your situation, see [this document](https://github.com/NekR/offline-plugin/blob/master/docs/updates.md)

Please get back at us if you fix this and let us know what was the problem, thanks.

**Comment by rossgeesman** [comment]
@tr1s I have been struggling with the same issue on Netlify and finally came across this:
https://www.netlify.com/blog/2018/09/21/international-service-worker-caching-awareness-day/

**Comment by mattgaspar** [comment]
@tr1s try disabling App Cache.  In the offline-plugin config, set AppCache: false
This fixed the issue for me on Android, I haven't testing on iOS yet.

See https://github.com/NekR/offline-plugin/issues/456

**Comment by GGAlanSmithee** [comment]
Closing this, see @mattgaspar's answer in #456
