### ISSUE TITLE
Service-worker intercepting urls to other app on same domain

### ISSUE THREAD

**Issue by Theo-Le-Donne** [NekR/offline-plugin#452]
Hi,
i’m currently setting up 2 apps on the same domain using AWS Cloudfront to manage routes between the apps. One of the 2 apps is a React app, based on React-Boilerplate and using offline-plugin. The other is a legacy AngularJS app. By default, routes of the react app are whitelisted in Cloudfront and the fallback routes go to the other app (/blog for example).

I'm trying to get the apps working together but i keep getting the default 404 of the React app when i want to leave to the other app.

I've tried some options provided by offline-plugin but my understanding of service-workers is not so good... I've tried using `responseStrategy : network-first`, `ServiceWorkers cacheName` but no success.

Everything is working fine when selecting `bypass for network` in chrome application dev tool.

I guess it is possible to blacklist/whitelist some routes, or maybe there is a better solution for this.

Thank you ! :)

**Comment by NekR** [comment]
Hi. Yeah, it should be possible to just white list some URLs and no the
others with `cacheMaps` option. It isn't the most intuitive API, but
unfortunately it's all we have for such use cases right now. I'll try to
make an example code for your case a bit later, but for now you may try to
look into the option on your own. There should be some docs about it too, I
believe.

чт, 2 мая 2019 г., 19:41 Théo Le Donné <notifications@github.com>:

**Comment by Theo-Le-Donne** [comment]
Thanks ! So i tried this used cacheMaps as you recommended (more of a blacklist behaviour) :
```
cacheMaps: [
        {
          match: function(requestUrl) {
            if (
              requestUrl.pathname.includes('/blacklistedUrl') 
            )
              return new URL(requestUrl.pathname, requestUrl.origin);
            return requestUrl;
          },
          requestTypes: ['navigate'],
        },
      ],
```
I was not convinced at first but it seems to be working, for now... 
Let me know what you think if you have time.

**Comment by NekR** [comment]
Hah, yeah, it works, but it's a kinda hacky and weird way, yes. It works because of weird logic inside of the function which checks the results. I need to write a better one and add more options to `appShell`.

I think you're good for know. But I'll work on a better solution.
