### ISSUE TITLE
How can I cache network API requests?

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [NekR/offline-plugin#453]
Hi, could you explain to me, how can I cache some response from API? Because I have dynamic content. Or maybe just html's? SPA with SSR.
example sources:
![image](https://user-images.githubusercontent.com/29048318/58966120-60403c00-87ba-11e9-9ca9-59e2cca8853d.png)

![image](https://user-images.githubusercontent.com/29048318/58966144-69310d80-87ba-11e9-807e-319b81538683.png)

Thx!
@NekR

**Comment by GGAlanSmithee** [comment]
Hi @TchernyavskyDaniil please see if this issue #413 (and the linked issues / docs in that issues) is to any help for you.

**Comment by TchernyavskyDaniil** [comment]
Ok, i will try that. Thx.
Closed. Maybe.
