### ISSUE TITLE
The problem with <HTML> automatically appends manifest.appcache

### ISSUE THREAD

**Issue by crixusshen** [NekR/offline-plugin#455]
I looked at the example in offline-plugin-pwa. The file manifest.appcache is not appended to <HTML> after the build. But this file automatically append to <HTML> after I integration offline-plugin into my project. I found that the implementation of offline-plugin implements the update of appcache through a iframe tag. Does it contradict the automatic injection of HTML tags？

**Comment by crixusshen** [comment]
I do know that pages that contain manifest= "are cached by default. So your iframe hack is the right way to do it. But I don't know that my HTML was automatically injected into the manifest tag, Is it the default behavior of the offline-plugin, or my personal problem^_^

**Comment by crixusshen** [comment]
I use the version of webpack is 4.36.1. the version of offline-plugin is 5.0.7

**Comment by crixusshen** [comment]
😝I found out why. the offline-plugin must be executed after the html-webpack-plugin. Now my HTML is not automatically injected the file of manifest.appcache. I guess that It could be the html-webpack-plugin cause. As long as the chunk contains the.appcache suffix it will be injected automatically.

**Comment by GGAlanSmithee** [comment]
Hey @crixusshen nice investigation 👍 and happy you fixed your issue. I submitted a PR, https://github.com/NekR/offline-plugin/pull/458, adding info regarding this to the docs, do you mind checking it out?
