### ISSUE TITLE
Force SW update in Firefox lower than 46.0.1 on Shift Reload

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#46]
See this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1267733
Basically, if SW is broken and throws an error for navigation request, so request document is never loaded and nothing can tell to Firefox to update SW.

Should we disable support SW for all Firefox version which do not have fix for that? I opinion is -- yes.

**Comment by derikson** [comment]
Fixed in Firefox 46.0.1

**Comment by NekR** [comment]
Yes, I know. Do, do you think we should block Fx versions prior that?

I now think we can just force SW update on Shift+Reload. This should cover those unfixed Fx and possible new browsers with same bug.

**Comment by NekR** [comment]
Okay, will make a force-update for Firefox prior `46.0.1`.

**Comment by NekR** [comment]
Okay, I think we can ignore this since no one reports problems with it.
