### ISSUE TITLE
Uncaught (in promise) DOMException: Only the active worker can claim clients.

### ISSUE THREAD

**Issue by haivx** [NekR/offline-plugin#476]
Hi,

Not sure if I've missed something obvious here.

I have an issues when using offline-plugin with default setting like this error message: ```Uncaught (in promise) DOMException: Only the active worker can claim clients.```.

How can I fix this problem? Thanks?

**Comment by cokeeffekt** [comment]
@haivx i have run into this issue now, i noticed you closed the issue your self, care to share what/where the issue was?

**Comment by haivx** [comment]
@cokeeffekt I think you've aldready registered serviceworker somewhere in your app. It causes the error above.
