### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by JoydS** [NekR/offline-plugin#500]
Hello guys !

Im trying to install your component but I have some issues with. When I try to compile, I have this error :

```
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at afterResolveFn (/var/www/project/node_modules/offline-plugin/lib/index.js:213:42)
    at Hook.eval [as callAsync] (eval at create (/var/www/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/project/node_modules/tapable/lib/Hook.js:18:14)
    at /var/www/project/node_modules/webpack/lib/NormalModuleFactory.js:287:30
    at eval (eval at create (/var/www/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /var/www/project/node_modules/webpack/lib/NormalModuleFactory.js:550:7
    at /var/www/project/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /var/www/project/node_modules/webpack/lib/NormalModuleFactory.js:582:8 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Any idea where is the problem ?  I just added the plugin and used it without options.

**Comment by oller** [comment]
This plugin is not compatible with webpack 5.  I believe the error your encountering is related to that : https://github.com/NekR/offline-plugin/issues/491

**Comment by JoydS** [comment]
Yeah, didn't see this issue, seems a duplicate, thank you for your answer @oller.

**Comment by oller** [comment]
NP, in fact commenting on that I noticed https://github.com/NekR/offline-plugin/issues/497 which seems like a fork with webpack 5 compatibility.  Props to @LeComptoirDesPharmacies

**Comment by ROBYER1** [comment]
> NP, in fact commenting on that I noticed #497 which seems like a fork with webpack 5 compatibility. Props to @LeComptoirDesPharmacies

Thanks so much for linking this!
