### ISSUE TITLE
regex for 'excludes' option?

### ISSUE THREAD

**Issue by jackyon** [NekR/offline-plugin#51]
Hi, great plugin! love it!

just curious about how to use regex for excludes option?

for example, i have list of touch icons and favicon, they all put in 'icons-randomHashNumber' folder, how can I exclude this folder?

plz advise, thx!

**Comment by NekR** [comment]
Hi! In `excludes` property and in most others you can just use pattern matching, e.g. `excludes: 'icon-*'` will exclude everything what starts with `icon-`.

**Comment by jackyon** [comment]
hi @NekR, thx for reply, I have tried that before, but seems not working, now I figure out the problem might be from F

**Comment by NekR** [comment]
Oh, sorry. It has to be an array of strings, try that.

**Comment by NekR** [comment]
@jackyon yep, might be related to that plugin, depends on how it's implemented. I'll look into it. Thanks for reporting!

**Comment by NekR** [comment]
Okay, this seems to be a problem of `minimatch`, its wildcards work in some weird way, e.g. `icons-*` doesn't match dirs and `icons-*/**` doesn't match hidden files (files with leading dot, e.g. `.cache`). So you have to use something like this (it works for me):

```js
excludes: ['icons-*/*.*', 'icons-*/.*'],
```

But I guess it's better to switch off from `minimatch` so something else which works better here.

**Comment by jackyon** [comment]
@NekR , thx for your solution, it works!

**Comment by NekR** [comment]
Great! Closing then. I'll think on how to improve pattern matching here.
