### ISSUE TITLE
Path to appcache/sw.js

### ISSUE THREAD

**Issue by Zhouzi** [NekR/offline-plugin#55]
I am probably missing something but I can't get to find how to configure the path to the appcache directory and sw.js file.

I have an express application serving assets at `/assets` so the current structure looks like:

```
/assets
  /appcache
    /manifest.appcache
    /manifest.html
  /js
    /app.js
    /sw.js
```

The problem is that the runtime installation tries to fetch the manifest from `/appcache/manifest.html` instead of `/assets/appcache/manifest.html`. I tried to play around with publicPath but didn't see any effects, same for relativePaths. I tried to pass options to the runtime function but after digging the code, seems like it's completely ignored.

Is there a way to configure the appcache and sw.js path? Must it be located at the root?

**Comment by NekR** [comment]
As in webpack itself, `publicPath` isn't related to files output place, there is separate option for that. This plugin has such options too:

ServiceWorker
> output: string. Relative (from the webpack's config output.path) output path for emitted script.
> Default: 'sw.js'.

AppCache
> directory: string. Relative (from the webpack's config output.path) output directly path for the AppCache emmited files.
> Default: 'appcache/'.

Example:
```js
new OfflinePlugin({
  ServiceWorker: {
    output: 'something/sw.js'
  },
  AppCache: {
    directory: 'something/appcache'
  }
});
```

But, **to control whole website with SW, it has to be in the root of your website**.

**Comment by Zhouzi** [comment]
Yes, I have actually configured AppCache.directory to move it one level up (`/assets/appcache` instead of `/assets/js/appcache`). But I can't get the runtime script to load the manifest from `/assets/appcache` instead of just `/appcache`. I guess I'll just move it to the root, along with `sw.js`.

Thank you for your time! 👍

**Comment by NekR** [comment]
@Zhouzi what do you mean cannot? `runtime.install()` doesn't load it from `assets/appcache`?

**Comment by NekR** [comment]
It works for me with any custom URL:
![image](https://cloud.githubusercontent.com/assets/1189265/15566879/fa8792aa-232b-11e6-91b4-607518036b3e.png)

**Comment by Zhouzi** [comment]
That is exactly what I am looking for, what's your configuration? Here's a little reproduction of mine:

```javascript
var OfflinePlugin = require('offline-plugin');

module.exports = {
  entry: './index.js',
  output: {
    path: './dist',
    filename: 'bundle.js'
  },
  plugins: [
    new OfflinePlugin({
      publicPath: '/dist/',
      ServiceWorker: null
    })
  ]
};
```

Which end up generating:

```
/dist
  /appcache
  /bundle.js
```

But the runtime installation tries to fetch `/appcache/manifest.html` instead of `/dist/appcache/manifest.html`. What am I missing?

**Comment by NekR** [comment]
@Zhouzi that's weird, it has to work. Just tried setting `publicPath` and it worked for me too. But I'll check with exact your config a bit later.

This is my config, but not sure if it 'll help you:

```js
new OfflinePlugin({
  caches: {
    main: ['index.html', 'assets/**/main.js', ':rest:'],
    // additional: [':rest:']
  },

  AppCache: {
    caches: [],
    FALLBACK: {
      '/': '/offline/offline.html',
      '/assets/': '/offline/offline-asset',
      '/icons/': '/offline/offline-asset',
    }
  },

  ServiceWorker: {
    events: true
  },

  updateStrategy: 'all',
  version: 'v' + (env.useVersion ? env.version + '_' : '') + (new Date).toLocaleString(),
  relativePaths: false,
  publicPath: '/',
  rewrites: function(asset) {
    if (publicPath && publicPath !== '/' && asset.indexOf('assets/') === 0) {
      return publicPath + asset;
    }

    return asset.replace(/^([\s\S]*?)index.htm(l?)$/, function(match, dir) {
      return dir || '/';
    });
  }
})
```

**Comment by NekR** [comment]
@Zhouzi btw, do you use latest version from npm, right?

**Comment by Zhouzi** [comment]
I must be missing something, here's what I am trying with:

**structure**

```
/dist
  /appcache
    /manifest.appcache
    /manifest.html
  /bundle.js
/index.html
/index.js
/node_modules
/package.json
/webpack.config.js
```

**index.html**

```html
<script src="dist/bundle.js"></script>
```

**index.js**

```javascript
var runtime = require('offline-plugin/runtime');
runtime.install();

var msg = 'Hello World';
module.exports = function () {
  return console.log(msg);
};
```

**package.json**

```json
{
  "private": true,
  "scripts": {
    "serve": "http-server",
    "build": "webpack"
  },
  "dependencies": {
    "http-server": "^0.9.0",
    "offline-plugin": "3.2.1",
    "webpack": "1.13.1"
  }
}
```

**webpack.config.js**

```javascript
var OfflinePlugin = require('offline-plugin');

module.exports = {
  entry: './index.js',
  output: {
    path: './dist',
    filename: 'bundle.js'
  },
  plugins: [
    new OfflinePlugin({
      ServiceWorker: null,
      publicPath: '/dist/'
    })
  ]
};
```

Run `npm run serve`, open up the address and there's a 404 not found `/appcache/manifest.html` which is normal since it's in `/dist/appcache/manifest.html`.

**Comment by NekR** [comment]
![image](https://cloud.githubusercontent.com/assets/1189265/15601384/b130c7ee-23f7-11e6-9f7b-c2b058926e96.png)
Have you seen your console when building project? It says about the problem, just set `relativePaths` to `false` to make `publicPath` work.

I am not sure it's done this way right now, but I suspect there was a reason a time.

**Comment by NekR** [comment]
-------------------------------------

**Comment by NekR** [comment]
I can change it v4 if it makes sense, of course.

**Comment by Zhouzi** [comment]
That's totally my fault. There's often so much warnings when building a webpack project that I'm no more reading them. I read the documentation and seen the mention of the incompatibility of publicPath/relativePaths but didn't pay attention to the fact that relativePaths is true by default and therefore disables publicPath. Maybe relativePaths should be ignored if there's a publicPath provided (as it can only be intentional since there's no default value) but really, that one is on me :)

Thanks for your kind support 👍

**Comment by NekR** [comment]
Oh, there seems be a lot of typos in my previous comments. Just fixed them. 

> Maybe relativePaths should be ignored if there's a publicPath provided (as it can only be intentional since there's no default value) but really, that one is on me :)

Yeah, it was this way in v2 when `publicPath` was called `scope` (don't ask why :-)) and I changed it in v3, also no idea why, it just happened.

I too think that it makes sense to revert to v2 behavior for `relativePaths` and `publicPath`, but I can do it only for v4 because I don't want to break people who use v3. Semver, etc.
