### ISSUE TITLE
Implement caches maps

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#59]
The idea is serve **one** cache for any navigation request, `/albums` for example. Same, if cache is empty, any navigation request should populate given cache.

Probably not _any_. Maybe something specified in map like this:

``` js
{
  '/albums': '/',
  '/gallery': '/'
}
// or
{
  '/*': '/shell.html'
}
```

Here is the use case number one: https://github.com/NekR/offline-plugin/issues/27
Second use case it to serve server-rendered content on network requests, but in ServiceWorker, cache the AppShell.

**Comment by nodkz** [comment]
Nice feature! 
But also will be great to have `rewriteThunk` in sw.js with your default `fetch` event in https://github.com/NekR/offline-plugin/blob/master/src/misc/sw-template.js#L241

This is right my case where I want replace custom routes to spa-shell-entry-html:
```
/job
/job/*
/company/*
...
// BUT NOT
/job/grapth
```
This can be done only via JS script, not mapper.

**Comment by NekR** [comment]
@nodkz so essentially it's just runtime-rewriter-function, right? Yeah, good idea 👍

**Comment by nodkz** [comment]
Exactly.

Cause routing operation often is too complex. And `maps` does not give enough flexibility and fine tuning.

Other use cases: 
* using url rewriter due anon user or authorized 
* due localization setting
* due time and date
* due expirity period
* may be tons other thing

**Comment by NekR** [comment]
I see your point, it's good idea and I think I may do it even before mapping as originally described here.
But I am not 100% sure about it yet. The idea of plugin was to have completely decorative output, but runtime rewrites requires JavaScript, which ins't declarative of course.

With declarative output, we can for example emit JSON file and later feed it to native app/code to handle app's caching.

I'll think about it.

**Comment by oscar-b** [comment]
@NekR Any new developments regarding this?

**Comment by NekR** [comment]
The only status about this us that I remember about it. Once there will be updates, they will be written here.

Anyway, thanks for letting me know about your interest. This will help me prioritize.

**Comment by NekR** [comment]
Is everyone here okay with this design for cache maps:

```js
new OfflinePlugin({
  cacheMaps: [
    {
      matchPath: /^\/\w+\.html$/,
      to: '/app-shell.html',
      navigateOnly: true
    },
    {
      matchUrl: function(input) {
        if (input !== '/something') {
          return '/other'; // rewrite
        }

        // Should return be implicit, i.e. use `input` if return is undefined?
        return input;
      },
    }
  ],
})
```

/cc @MoOx @developit @KyleAMathews

**Comment by NekR** [comment]
I moved the code example to separate issue for clarity.

**Comment by NekR** [comment]
Done in `v4` now :-)

**Comment by NekR** [comment]
Didn't add to readme yet though, going to do that..

**Comment by NekR** [comment]
Wrote some docs: https://github.com/NekR/offline-plugin/blob/master/docs/cache-maps.md
