### ISSUE TITLE
External URLs are prefixed with relative path

### ISSUE THREAD

**Issue by omichelsen** [NekR/offline-plugin#60]
If I add external resources for caching, they are prefixed with `./` like this:

```js
  "assets": {
    "main": [
      "./"
    ],
    "additional": [],
    "optional": [
      "./https://weblibrary.myserver.com/styles/main.css",
      "./https://weblibrary.myserver.com/fonts/icons.woff"
    ]
  },
```

I can set `relativePaths: false`, but I don't really see why you can't have both relative paths and a few external URLs. Should be easy to detect?

**Comment by NekR** [comment]
Yep, I know about the problem, this https://github.com/NekR/offline-plugin/issues/39 issue is kind of about it.

> Should be easy to detect?

Probably easy, just isn't done yet. Bad that it affects you :-(

**Comment by NekR** [comment]
@omichelsen Okay, just made a fix, please try it from `master`.

**Comment by omichelsen** [comment]
Works great, thanks man 👍

**Comment by NekR** [comment]
Great :-)

**Comment by NekR** [comment]
Closed via https://github.com/NekR/offline-plugin/commit/5bd591e59d2c8e7ab68f87b46b938ba5b765bb54

**Comment by NekR** [comment]
On `npm` now
