### ISSUE TITLE
how to get the registration object after install

### ISSUE THREAD

**Issue by pavankumarkatakam** [NekR/offline-plugin#61]
Doc says to install service worker use `runtime.install(options:Object)`, but i want the registered `reg` object so that i will make push manager use of it  as specified in the doc https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-06?hl=en , so here how i will get the `.then(function(){})` after registering the serviceWorker using the runtime.

**Comment by NekR** [comment]
```js
navigator.serviceWorker.ready.then((reg) => {
  // ....
})
```

https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web

**Comment by pavankumarkatakam** [comment]
Thanks for that doc.

**Comment by NekR** [comment]
No problem :-)
