### ISSUE TITLE
Never hitting to the server

### ISSUE THREAD

**Issue by burakcan** [NekR/offline-plugin#63]
Hi, i'm trying to use this plugin but i couldn't get it working right.

Webpack version: 2.1.0-beta.8
Plugin version: 3.2.1
Configuration: 
```
      updateStrategy: 'all',
      version: '[hash]',
      publicPath: '/',
      relativePaths: false,
      ServiceWorker: {
        output: 'offline/sw.js'
      },
```
On the first load, everything is ok and the app works offline on the next launch. But when i update something and build again, the cache/sw won't update. Also, there's no hits in the server logs. What i'm doing wrong? Should i put the runtime call in a non-cached chunk?

**Comment by NekR** [comment]
Hi @burakcan.

First of all, in your case SW can control only `/offline/*` requests scope, so it's surprisingly that it works for you at all. Do you test on localhost/HTTPS site or on simple domain?

Second thing is that SW doesn't update on refresh. It updates actually, but new SW doesn't take control of webpages unless you force it to do so or close all active tabs.

Third thing might be that I never tried this plugonv with webpack2, so everything might be broken with it.

**Comment by burakcan** [comment]
Hi @NekR , thank you for the response;

Im trying on both localhost:port and local.localdomain.com:port, it's working :) 

Yes, i'm aware that the sw doesn't take control unless all tabs are closed. But doing that doesn't help too. 

There's not too much change on the surface api of webpack in 2. But did try it with webpack 1.x it was the same. 

I'll try with a flat file structure by removing the /offfline/ path. 
Thank you.

**Comment by NekR** [comment]
> and local.localdomain.com:port,

Is it https? SW won't work there unless it's https. `AppCache` is on by default in `offline-plugin`, so that might be AppCache, if domain not https.

**Comment by burakcan** [comment]
I've just tried it with the default configuration `new OfflinePlugin()` it's still not working :(

**Comment by NekR** [comment]
@burakcan hmm.. weird. Does version/hash change when you build new version?

**Comment by burakcan** [comment]
I don't update the version(package.json) but the hash changes: 
<img width="215" alt="screen shot 2016-06-06 at 08 48 55" src="https://cloud.githubusercontent.com/assets/3121257/15812964/8bab93ae-2bc3-11e6-9de2-1c4c47ac0a5e.png">

**Comment by NekR** [comment]
@burakcan then it shouldn't work for everyone. Are you sure browser receives new SW version? e.g. it shouldn't be cached.

Also `offline-plugin` doesn't work with Hot Reload, if you are using it.

**Comment by burakcan** [comment]
I'm doing hot loading only in development (webpack config is separate).
How do i know if browser receives the new SW version? I guess it doesn't because there is no request in the server logs at all.
With webpack 1, nothing changed.

**Comment by burakcan** [comment]
Ah sorry :) it's the cache-control header. Setting it to zero fixed. Thank you @NekR 

So the update scenario is like this right?:
- first load (install)
- new build
- second load (updates the sw, but changes don't take effect)
- close the tab, open again
- see the new content

**Comment by NekR** [comment]
@burakcan right. In latest Chromes (e.g. Canary) you can set "Update SW on every navigation" option. Very useful for development. In this case SW is downloaded before pages loads, reinstalled and then page is downloaded.

Other way is apply update manually (this will work you users too):

```js
// config
new OfflinePlugin({
  ServiceWorker: {
    events: true
  }
})
```

```js
// the app
runtime.install({
  onUpdating: () => {
    console.log('SW Event:', 'onUpdating');
  },
  onUpdateReady: () => {
    console.log('SW Event:', 'onUpdateReady');
    // Apply update when available
    runtime.applyUpdate();
  },
  onUpdated: () => {
    console.log('SW Event:', 'onUpdated');
    // Reload immediately when updated
    window.location.reload();
  },

  onUpdateFailed: () => {
    console.log('SW Event:', 'onUpdateFailed');
  }
});
```

**Comment by burakcan** [comment]
Thank you so much @NekR
events are just what i'm looking for 💯

**Comment by tleunen** [comment]
What was the final solution for this?
I'm kinda having the same issue.

Here's what I see for the sw:
![screen shot 2017-02-17 at 3 45 32 pm](https://cloud.githubusercontent.com/assets/1972567/23082635/2ca505d2-f528-11e6-83b8-8d3c40f459e5.jpg)
Looks like the new SW never gets activated, even after a refresh

**Comment by NekR** [comment]
Please read here about SW update process and related stuff: https://github.com/NekR/offline-plugin/blob/master/docs/updates.md

**Comment by tleunen** [comment]
Thanks :)

> New SW doesn't start controlling pages until all tabs of your website are closed
