### ISSUE TITLE
Need help caching the parent root `/` path when specifying a `publicPath`

### ISSUE THREAD

**Issue by tribou** [NekR/offline-plugin#65]
I have my webpack publicPath set to `/static/` where I output all of my bundles.  However, when I set the following config for `offline-plugin`, I can't figure out how to cache my home route (`/`):

```js
  new OfflinePlugin({
    publicPath: '/static/',
    relativePaths: false,
    caches: {
      main: [
        '/',
        ':rest:',
      ],
    },
    externals: [
      '/',
    ],
  })
```

Since the `publicPath` is set to `/static/`, it's trying to fetch the root route from there instead of `/`:

```error
GET http://localhost:3000/static/?__uncache=6%2F6%2F2016%2C%208%3A03%3A21%20AM 403 (Forbidden)
```

How would I specify both my root route `/` and my webpack assets which output to `/static/`?

**Comment by NekR** [comment]
@Sounds like a bug. Ideally it has to work, but doesn't right now.

Until this fixed, there is a solution, try this:

```js
new OfflinePlugin({
  publicPath: '/',
  relativePaths: false,
  caches: {
    main: [
      '/',
      ':rest:',
    ],
  },
  externals: [
    '/',
  ],
  rewrites: function(asset) {
    if (asset !== '/') {
      return '/static/' + asset;
    }

    // This is code from default rewrites() function, feel free to remove it
    // if not needed
    return asset.replace(/^([\s\S]*?)index.htm(l?)$/, function(match, dir) {
      return dir || '/';
    });
  }
});
```

With `rewrites()` function you can actually alter routes as you want, e.g. prefix it with `cdn.example.com/static/` instead of just `/static/` for everything except `/`, which won't be possible with `publicPath` anyway.

**Comment by NekR** [comment]
Fixes `rewrites()`' function code a bit.

**Comment by tribou** [comment]
Rewriting the asset path worked!  Thanks @NekR!

Also, I've renamed this issue so it can be tracked for a future feature if needed.

**Comment by NekR** [comment]
Great, thanks!

**Comment by NekR** [comment]
@tribou Just to clarify: you generate all assets and SW/AppCache in the same folder by webpack, then you copy generated assets to `/static/` folder on your server and SW/AppCache to the root of your server?

**Comment by tribou** [comment]
Correct, I ended up adding separate routes for SW/AppCache to my Hapi.js server to serve those from the root (`/sw.js`).  Not ideal, but it got it working.

**Comment by NekR** [comment]
Problem here is that you generate flat structure with webpack, but on server you use it differently. Maybe you just set public path to `/` and then generate assets to `static/` subfolder of output, like this:

```js
output: {
  path: path.join(__dirname, 'output'),
  filename: 'static/[name].js',
  chunkFilename: 'static/[name].js',
  publicPath: '/'
},
```

This way all your generated scripts/css will be in `static/` subfolder, but SW and AppCache will be emitted into `output`. Of course, this won't help with your problem on server, but this may eliminate need of `offline-plugin` path rewrites and just in general make it more clean.

**Comment by NekR** [comment]
As per #66, also need to investigate support of absolute URLs in `publicPath`.

**Comment by NekR** [comment]
@tribou I just rechecked the code and both `ServiceWorker` and `AppCache` use `publicPath` to provide their location to runtime. For example, if your output SW is `sw.js` and public path is `/static/`, runtime will expect SW file to be on `/static/sw.js`. This is why it's wasn't allowed to cache `/` or specify `publicPath` as an absolute URL with domain because both SW and AppCache are meant to use public path too.

How you were able to make it work with `publicPath: '/static'` when your `sw.js` was on `/sw.js` path on server?

**Comment by NekR** [comment]
I think I can make `publicPath` affect only assets/cache and don't affect SW and AppCache files itself.

Your feedback, @KaboomFox, would be welcome too. Thanks.

**Comment by NekR** [comment]
Okay, I think this is fixed in `v4`. I didn't test for all edge cases yet, but if someone wants to test things with `v4`, it can be installed this way: `npm install offline-plugin@next`

**Comment by GGAlanSmithee** [comment]
Thanks @NekR 

>Problem here is that you generate flat structure with webpack, but on server you use it differently. Maybe you just set public path to / and then generate assets to static/ subfolder of output

This is sound advice for anyone having problem with this in the future 👍

**Comment by NekR** [comment]
@GGAlanSmithee thanks! It probably makes sense to add that to the docs. Still a lot of docs to write though. 

Also `v4` is more flexible for paths, e.g. you can generate it outside of you build/output directory or change its public path without affecting publicPath of assets in use. I planned to write a doc about it too :-)
