### ISSUE TITLE
make publicPath absolute

### ISSUE THREAD

**Issue by KaboomFox** [NekR/offline-plugin#66]
my webpack generated assets resolve to: `resource.example.com/something.js` but my webpage is `www.example.com`. Is there anyway of making the publicPath absolute?

Thanks

**Comment by NekR** [comment]
See this https://github.com/NekR/offline-plugin/issues/65#issuecomment-223964545

**Comment by KaboomFox** [comment]
👍  thanks for the quick response

**Comment by NekR** [comment]
No problem. Does it work for you?

**Comment by NekR** [comment]
Okay, closing this and tracking problem with absolute cache in #65

**Comment by NekR** [comment]
@KaboomFox just to make sure I understood you correctly: do you serve SW file from `www.mysite.com/sw.js` but your assets live `resource.mysite.com`? Do you have any other problems with paths? Do you use AppCache? Because AppCache doesn't support cross-domain caching over HTTPS.
