### ISSUE TITLE
Caching dynamic urls

### ISSUE THREAD

**Issue by kikoanis** [NekR/offline-plugin#67]
I am working on a react application and I use react-router for routing. My question is how do I cache dynamic routes or how do I tell cache storage to cache the response if it is successful for offline purposes. Currently, unless it is mentioned in one of the cache main categories [main, additional,...], there is no way to cache it.

**Comment by NekR** [comment]
See this: https://github.com/NekR/offline-plugin/issues/64

**Comment by kikoanis** [comment]
I can confirm your solution in [#64](https://github.com/NekR/offline-plugin/issues/64#issuecomment-223949743) works perfect for me. It is not the cleanest solution but it does work. thanks. 
So I am closing this issue

**Comment by NekR** [comment]
Yeah, we can do better. I'll let you know once something better is implemented.
