### ISSUE TITLE
Please add an example folder

### ISSUE THREAD

**Issue by EloB** [NekR/offline-plugin#68]
Hello

I would like to say thank you for a nice plugin but I have hard time to implement it. I would love to see some real working examples. A examples folder in your repo would be awesome!

I managed to get the service worker to work but I don't know how to get the AppCache to work.

Thanking you in advance.

**Comment by NekR** [comment]
Hi @EloB,

> A examples folder in your repo would be awesome!

Yes, I know that would be great, but I don't have time for it right now. Maybe later.
But feel free to ask any questions here.

> I managed to get the service worker to work but I don't know how to get the AppCache to work.

`AppCache` is enabled by default. What doesn't for you in it? If you have simple project `new OfflinePlugin()` (without options) often is good start, it should automatically make everything work and later you can add additional options.

**Comment by EloB** [comment]
I see that the `manifest.html` and the `manifest.appcache` file is created. I might got it wrong on the purpose of this library but I have a SPA with html5 push state routing so I need to have a fallback with `/ /manifest.html`. How do I add content to `manifest.html`?

**Current source in manifest.html**
```html
<!doctype html>
<html manifest="manifest.appcache"></html>
```

**Comment by NekR** [comment]
You don't need to add anything to it. Just run `runtime.install()` in your script and it will load and install `ServiceWorker` and `AppCache` for you. That's the point, you don't need to much to make it work.

**Comment by NekR** [comment]
How you install `ServiceWorker`, with `runtime.install()` or manually? What is the content of generated `manifest.appcache`? Does it have your assets listed in there?

**Comment by NekR** [comment]
Again, you don't have to do anything except of calling `runtime.install()`. Then runtime will do everything for you, it will loading iframe with `appcache/manifest.html` and then browser will load `appcache/manifest.appcache`.

I still don't understand what you are trying to do. Are you trying to add `<html manifest="/dist/appcache/manifest.appcache">` to your `index.html`? If so, then you don't need to. `runtime.install()` is enough and `AppCache` already to work for you.

**Comment by NekR** [comment]
BTW, it's probably bad to cache all fonts of all formants in either AppCache or ServiceWorker. Browser will use one format, but you will force it do download all of them.

**Comment by NekR** [comment]
@EloB did it help you?

**Comment by EloB** [comment]
@NekR Sorry that I didn't reply. Haven't have time to fix it. I will report back when I'm done! 👍

**Comment by NekR** [comment]
Sure! Just let me know if something doesn't work for you.

**Comment by EloB** [comment]
Do you have any good ideas how to just include only that browser specific font?

**Comment by NekR** [comment]
It's not possible with AppCache unless you send different fonts from a server to the save url in different browsers, which of course could be buggy.

With SW you can just use `optional` cache.

**Comment by NekR** [comment]
We started adding some examples: https://github.com/NekR/offline-plugin/tree/master/docs/examples
Feel free to contribute, thanks!
