### ISSUE TITLE
Why is relatives RegExp is using (\s\S*?) which seems to be the same as  (.*)

### ISSUE THREAD

**Issue by MoOx** [NekR/offline-plugin#70]
https://github.com/NekR/offline-plugin/blob/7bc086e319d8c1aa3f24e1511ad393f4f48eb3df/src/index.js#L27

Seems like they are the same

http://refiddle.com/refiddles/5760d0ef75622d01a97e2100
http://refiddle.com/refiddles/5760d11375622d4e39c28300

\s\S is everything (\s: everything whitespace, \S: everything but whitespace)
and ? seems useless since * is 0 or more.

**Comment by NekR** [comment]
Yep, I know what it does. Do you think it has any impact on anything here?

**Comment by MoOx** [comment]
A readability one, for sure :D

**Comment by NekR** [comment]
Sorry, but let's close. I don't tend to change things just to do a change. Maybe when I'll be releasing `v4` I can do this. Anyway, current;y it works fine and there are more important issues (and yours too) to consider. We can always polish it later :-)
