### ISSUE TITLE
How to have a fallback html entry point for Service Worker?

### ISSUE THREAD

**Issue by MoOx** [NekR/offline-plugin#71]
For SPA, it's very common to just have a single html file and most of the time, the server handle the redirection for all url (eg: /blah/ and / will send the same html entry file).

I don't have the hand of the server side, and by default my app generate all possible html entries (it's a [static website generator based on React](https://phenomic.io/) as well as json data for each pages.
This means if I go to a specific url (eg: http://phenomic.io/docs/setup/) without JS, I am getting the correct HTML page. But the default behavior is to just download some json data - which include page content for all pages (eg: you are on / and are accessing /docs/setup/, only a json request is made, handled by the client side, no html files are used).
The idea for my use case is to cache only json files, not html, so client side browsing offer a better UX.

With Appcache, there is a FALLBACK option, which is handy to send all offline request to a single (cached) entry point (eg: index.html), but with this plugin, I don't see how to reproduce this behavior for Service Worker, on the client side. Should I use the `rewrites` option? Any tip? Thanks in advance!

**Comment by NekR** [comment]
There is no way to specify fallback for `ServiceWorker` right now, but I thought about it. Also here is issue related to it: https://github.com/NekR/offline-plugin/issues/59

Unfortunately `rewrites` won't help here because it does its job on compile time, not at runtime.

I guess fallback will be easier to implement than request maps. Thanks for reporting this, I'll think today if there is a way to easily implement it.

**Comment by MoOx** [comment]
I am currently using this snippet (which seems to work as expected, I adjusted something find, see link at the top of the snippet).

```js
/* eslint-disable prefer-const, no-var */

// inspired from
// https://googlechrome.github.io/samples/service-worker/custom-offline-page/

function createCacheBustedRequest(url) {
  let request = new Request(url, { cache: "reload" })
  // See https://fetch.spec.whatwg.org/#concept-request-mode
  // This is not yet supported in Chrome as of M48, so we need to explicitly
  // check to see if the cache: "reload" option had any effect.
  if ("cache" in request) {
    return request
  }

  // If { cache: "reload" } didn't have any effect, append a cache-busting URL
  // parameter instead.
  var bustedUrl = new URL(url, self.location.href)
  bustedUrl.search += (bustedUrl.search ? "&" : "") + "cachebust=" + Date.now()
  return new Request(bustedUrl)
}

self.addEventListener("fetch", event => {
  // We only want to call event.respondWith() if this is a navigation request
  // for an HTML page.
  if (
    event.request.mode === "navigate" ||
    // request.mode of "navigate" is unfortunately not supported in Chrome
    // versions older than 49, so we need to include a less precise fallback,
    // which checks for a GET request with an Accept: text/html header.
    (
      event.request.method === "GET" &&
      event.request.headers.get("accept").indexOf("text/html") > -1
      // event.request.headers.get("accept").includes("text/html")
    )
  ) {
    console.log("Handling fetch event for", event.request.url)
    event.respondWith(
      fetch(createCacheBustedRequest(event.request.url)).catch(error => {
        // The catch is only triggered if fetch() throws an exception, which
        // will most likely happen due to the server being unreachable.
        // If fetch() returns a valid HTTP response with an response code in
        // the 4xx or 5xx range, the catch() will NOT be called.
        // If you need custom handling for 4xx or 5xx errors, see
        // https://github.com/GoogleChrome/samples/tree/gh-pages/
        // service-worker/fallback-response
        console.log("Fetch failed; returning offline page instead.", error)
        return caches.match("index.html")
      })
    )
  }

  // If our if() condition is false, then this fetch handler won"t intercept
  // the request.
  // If there are any other fetch handlers registered, they will get a chance
  // to call event.respondWith().
  // If no fetch handlers call event.respondWith(), the request will be
  // handled by the browser as if there were no service worker involvement.
})
```

**Comment by NekR** [comment]
Do you mean in hand-written SW or with `offline-plugin`? If think you can use it with `offline-plugin` by adding your snipper into `sw-handler.js` as in this gist: https://gist.github.com/NekR/06210fc9dea3a9f7850c1f89c9e5dcb5

Good temporal solution 👍 

I tried to implement `fallback` yesterday, but I didn't like how it looks. Basically it's the same as _routes-map_ I am planning to do, so reverted those changes.

**Comment by MoOx** [comment]
Yeah, I added this snippet via ServiceWorker.entry options.

**Comment by NekR** [comment]
Hmm.. one thing what bothers me is that `fallback` is meant to work only for `navigate` requests, but _routes-map_ 'll work for every request. Solution might to have a `navigate: true` option for a route to solve this, or maybe it's not needed because _routes-map_ can be more precise (match only needed routes). What do you think?

**Comment by MoOx** [comment]
routes-map API does not sound straight foward and user friendly, but maybe with proper documentation that can be enough.
`fallback: "index.html"` seems to be offer a nice and fast DX.  Otherwise `navigateFallback`?

**Comment by NekR** [comment]
Yep, I planned to call it `navigateFallbackURL`. Added:

> navigateFallbackURL: string. The URL being returned from the caches when requested navigation URL isn't available. Similar to AppCache.FALLBACK option.
Example: navigateFallbackURL: '/'

**Comment by MoOx** [comment]
Note that from my test, "/" don't work, you need to specify a file (eg: "index.html")

**Comment by NekR** [comment]
It works for me. Maybe you just cached it as `index.html` instead of `/`.
