### ISSUE TITLE
AppCache iframe src is relative

### ISSUE THREAD

**Issue by novascreen** [NekR/offline-plugin#73]
If i land on a page like `http://example.com/test/123` the iframe src `appcache/manifest.html` fails. Shouldn't there be an option to make this absolute: `/appcache/manifest.html`?

Or is the intention for this to be handled by a redirect rule on the server?

**Comment by NekR** [comment]
Yes, you can set use absolute paths there. Add this options:

```js
new OfflinePlugin({
  relativePaths: false,
  publicPath: '/'
})
```

This will set public path for loading AppCache/SW files and for assets URLs inside them.

**Comment by NekR** [comment]
Okay, closing this. Feel free to re-open or create another issue if this doesn't work for you.
