### ISSUE TITLE
Empty runtime

### ISSUE THREAD

**Issue by MoOx** [NekR/offline-plugin#74]
No sure why I am getting this now: my `offline/runtime` returns me the file with empty function defined at the root of this repo

```
exports.install = function() {};
exports.applyUpdate = function() {};
```

So nothing is working.

Are you doing some special transformation from with the plugin? What can explain this issue?

**Comment by NekR** [comment]
@MoOx Yes, I do handle `runtime.js` from plugin. There was similar issue with runtime because of webpack's inconsistencies in API https://github.com/NekR/offline-plugin/issues/41

Not sure what is wrong again. To use webpack's `cli` or call `webpack()` from program?

**Comment by NekR** [comment]
Also, if you don't include `new OfflinePlugin()` in config, runtime 'll be empty to let everything work in dev more.

**Comment by MoOx** [comment]
My use case is a bit complicated. I am tweaking a webpack config from a node_modules.
So I am adding both plugin and runtime not from the cwd, but from an extended config, and consume it via webpack node api.

**Comment by NekR** [comment]
I do similar things in my projects and everything seems to be fine. I am not sure if I can help until I see test project, very hard to guess with webpack.

You can of course try to debug it by yourself, if you want, here is what I am doing with runtime: https://github.com/NekR/offline-plugin/blob/master/src/index.js#L164

**Comment by MoOx** [comment]
I found my issue: I had duplicate offline-plugin and the runtime comparison was not accurate.
Maybe the "empty" module should display a console or something? That would prevent issue. At least this will warn the user.
Something like:

> "offline-plugin: install runtime executed without the OfflinePlugin. The installation of offline-plugin has not been executed. You can ignore this message if you are skipping the OfflinePlugin during development. Otherwise, you may have a configuration issue. "

**Comment by NekR** [comment]
Good idea, I'll add it 👍  Thanks!
