### ISSUE TITLE
[hash] in main caches

### ISSUE THREAD

**Issue by Sunil6591** [NekR/offline-plugin#75]
Here is my config - 
```
new OfflinePlugin({
      caches: {
        main: [
          '/vendor.[hash].js',
          '/bundle.[hash].js'
        ],
```
It gives me 
```
WARNING in OfflinePlugin: Cache pattern [/vendor.[hash].js] did not matched any assets
```
`vendor.{hash}.js` and `bundle.{hash}.js` are part of my output, however, i wanted to cache `externals`, 
```
externals: [ '/' ]
```
So as per the docs, i have to give `caches` key

**Comment by NekR** [comment]
Yeah, unfortunately externals aren't automatically included, I'll fix it soon.

But in your case, you can just use pattern matching, like this `vendor.*.js`. Also, I don't thinks that it's needs at all in your case, try this:

```
main: [
  '/', // external
  ':rear:' // special keyword, means everything else from build which wasn't included already
]
```

Hope it'll help.

**Comment by Sunil6591** [comment]
```
new OfflinePlugin({
      caches: {
        main: [
          '/vendor.*.js',
          '/bundle.*.js'
        ]
      },
      externals: ['/']
    })
```
It gives
`WARNING in OfflinePlugin: Cache pattern [/vendor.*.js] did not matched any assets`

And if i use 
```
new OfflinePlugin({
      caches: {
        main: [
          '/', // external
          ':rear:' // special keyword, means everything else from build which wasn't included already
        ]
      }
    })
```
It gives 
```
WARNING in OfflinePlugin: Cache asset [/] is not found in output assets,if it's an external asset, put it to |externals| option to remove this warning

WARNING in OfflinePlugin: Cache asset [:rear:] is not found in output assets,if it's an external asset, put it to |externals| option to remove this warning
```

**Comment by NekR** [comment]
It's `:rest:`, not rear. That was a typo which I fixed.

Also your assets don't start with `/`, it's just `vendor.*.js`. And, of
course, you have to still include `/` in externals as warning says to you.

**Comment by NekR** [comment]
Okay, now I am back to my computer and can show you full example:

This is what you need:
```js
new OfflinePlugin({
  caches: {
    main: [
      '/',
      ':rest:'
    ]
  },
  externals: ['/']
})
```

Other solution might be this:
```js
new OfflinePlugin({
  caches: {
    main: [
      '/',
      'vendor.*.js',
      'bundle.*.js'
    ]
  },
  externals: ['/']
})
```

but first example is better.

Hope it helps. Thanks.
