### ISSUE TITLE
[Feat] Callback for update

### ISSUE THREAD

**Issue by Luchillo** [NekR/offline-plugin#78]
## Feature request

The idea is simple, say you build a new version and you want the users to know, for example i'm the kind of people that keeps some windows open all day, if i never close it will never get updated, the idea is that if there's an update available we get to know and we notify the user then let them choose when they have finished current work before updating (which in turn should call `SkipWaiting` in the `Service Worker`.

I can see that the runtime has an `applyUpdate` method but haven't figured out how to use it.

**Comment by Luchillo** [comment]
I mean i know how to use applyUpdate but i will have to check manually for updates waiting, installing or finished in order to reload the page or something.

**Comment by NekR** [comment]
Runtime already has events, it's document in README: https://github.com/NekR/offline-plugin#install-options

Here is an example:
```js
const runtime = require('offline-plugin/runtime');

runtime.install({
  onUpdating: () => {
    console.log('SW Event:', 'onUpdating');
  },
  onUpdateReady: () => {
    console.log('SW Event:', 'onUpdateReady');
    runtime.applyUpdate();
  },
  onUpdated: () => {
    console.log('SW Event:', 'onUpdated');
    window.location.reload();
  },

  onUpdateFailed: () => {
    console.log('SW Event:', 'onUpdateFailed');
  }
});
```

To use runtime events you have to enable them first, like this:
```js
new OfflinePlugin({
  ServiceWorker: {
    events: true
  },
  AppCache: {
    events: true
  }
})
```

**Comment by Luchillo** [comment]
You're right, i didn't understand it had to go into options, i tough i would need to attach an event listener.
