### ISSUE TITLE
'navigateFallbackURL' config option does not get passed to ServiceWorker config

### ISSUE THREAD

**Issue by david-poirier-csn** [NekR/offline-plugin#81]
The 'navigateFallbackURL' setting is discarded, when it should be passed to the ServiceWorker config.

**Comment by NekR** [comment]
`navigateFallbackURL` lives on `ServiceWorker` option-object itself and is picked up here: https://github.com/NekR/offline-plugin/blob/master/src/service-worker.js#L15

Usage example:

```js
new OfflinePlugin({
  ServiceWorker: {
    navigateFallbackURL: '/'
  }
})
```

Closing this, but feel free to correct me if I'm missing something. Thanks.

**Comment by david-poirier-csn** [comment]
Does this wipeout the default ServiceWorker config?

**Comment by NekR** [comment]
Of course no.

5 Июл 2016 г. 0:58 пользователь "David Poirier" <notifications@github.com>
написал:

**Comment by NekR** [comment]
Oh, you edited the message. Feel free to ask any questions if something. Thanks :-)
