### ISSUE TITLE
Unable to cache external resorce

### ISSUE THREAD

**Issue by prijindal** [NekR/offline-plugin#85]
My Options look like this
```
{
  caches:{
    main:[
      'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
      'http://s.mlcdn.co/animate.css',
      'polyfills.*.js',
      'vendor.*.js',
      'main.*.js',
      '/',
      'sw.js'
    ],
    additional:[
      'assets/service-worker.js',
      'assets/img/angular-logo.png',
      'assets/css/loading.css',
      'assets/css/styles.css',
      'assets/css/forms.css'
    ],
    externals:[
      'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
      'http://s.mlcdn.co/animate.css'
    ]
  }
```

External Resources are loaded but when i refresh them in offline mode, only local resurces are loaded and external resources are met with a 404

PS: These caches are loaded with AppCache manifest rather than service worker

**Comment by NekR** [comment]
First of all, why do you put `sw.js` in the `caches`? It doesn't make sense for both SW and AppCache.

AppCache doesn't support cross-origin caches over HTTP**S**. Do you use https on your site?
Thanks.

**Comment by prijindal** [comment]
Yeah I solved it by moving to https 
And thanks for pointing it out my mistake
