### ISSUE TITLE
confuse on service worker

### ISSUE THREAD

**Issue by jackyon** [NekR/offline-plugin#86]
hi, 

I have test this plugin, the appCache worked but seems the service worker not working at all. I prefer to use service worker, so I disabled appCache in webpack config file, but  the console log or network log still not reminding anything about service worker, even sw.js is not include in the website.

is this issue happened only in http protocol? should I change mine as https protocol?

plz advise, thx!

**Comment by NekR** [comment]
Hi, yes, ServiceWorker works only on HTTPS.
