### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by glennreyes** [NekR/offline-plugin#87]
Is it possible to disable logs like [here](https://github.com/NekR/offline-plugin/blob/743a14d0201253bad46bd982858821abac444220/src/misc/sw-template.js#L32)?

```
[SW]: Install event
```

Couldn't find anything in the src.

**Comment by NekR** [comment]
No, there is no such option. What is wrong with it?

**Comment by glennreyes** [comment]
Ist is extremely useful! 👍 I just thought it could be disabled in production to keep the console clean from logs

**Comment by NekR** [comment]
I see. I think I can add such option. Thanks for reporting this :-)

**Comment by glennreyes** [comment]
I would really appreciate this, I'm sure others too! Let me know if you would need some helping hands to do this 💪

**Comment by NekR** [comment]
@glennreyes If you could do the PR then it would be great. If you will, please do it against `v4` branch.

**Comment by glennreyes** [comment]
I'll be off to holidays for a week but I can look after it

**Comment by NekR** [comment]
Btw, when you deploy to production with `uglify` plugin and set option to _strip console logs_, then they are removed from generated SW because `offline-plugin` automatically applied `uglify` plugin to SW when it's used in your build.

**Comment by glennreyes** [comment]
@NekR that sounds really good! That would solve this issue I guess. I can look at it when I am back from holidays this weekend.

**Comment by glennreyes** [comment]
Just revisited this issue:
```
compress: {
  drop_console: true,
},
```
... does that as expected 😉

**Comment by NekR** [comment]
@glennreyes Great!
