### ISSUE TITLE
Does this thing pre-load chunks!? AMAZING!

### ISSUE THREAD

**Issue by kentcdodds** [NekR/offline-plugin#89]
Hey, I just wanna say thanks to you for making this. It's amazingly simple. It "just works." Great work on it.

I just deployed [my webpack-ed TodoMVC to Surge.sh](https://todomvc-kent.surge.sh/) and noticed that it appears the service worker is pre-fetching all chunks (even code-split chunks). Which means that there's literally no latency when loading code for features as the user navigates around because it's already in the service worker cache before they get there. Totally mind blowingly awesome. Great work on this plugin @NekR!!!

**Comment by NekR** [comment]
Hi Kent, thanks for the kind words!

The idea of `offline-plugin` always was to have all params optional, so devs could progress from no configuration to something complicated as their project progresses too. I'm so glad it indeed works this way in real-world projects, thanks again! :-)
