### ISSUE TITLE
Offline Plugin doesn't work on old safari

### ISSUE THREAD

**Issue by chaintan17** [NekR/offline-plugin#90]
![image](https://cloud.githubusercontent.com/assets/2979072/17274260/8a3b03d6-5703-11e6-975e-3b99e0956b61.png)

I think it's regards to this issue
http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

**Comment by NekR** [comment]
So it's related to Private Browsing, right? If so, then Firefox also doesn't support `ServiceWorker`/`AppCache` in private browsing.

**Comment by NekR** [comment]
Should I close this? Any updates?

**Comment by chaintan17** [comment]
Yes, please close it. I misunderstand
