### ISSUE TITLE
NoUpdate event?

### ISSUE THREAD

**Issue by jefbarn** [NekR/offline-plugin#97]
Hi great work on this plugin,
I'm trying to setup my app to check for an update and load the update before bootstrapping the main js bundle.  The events provided work for loading a new version, but it doesn't seem like there is any way to detect the 'no update' case.  I would like to have my app loader wait for the service worker or appcache to finish the update check before continuing.
Is it possible to add an event that gets sent when the update check is finished and nothing changes?

**Comment by NekR** [comment]
Hi jefbarn, I think that it isn't possible with SW without some hacks. ServiceWorker doesn't provides any update events except of `updatefound`, so we cannot detect if browser is updating SW or if there is no update.

Also it's probably a bad idea to prevent app loading in favor of update process. Browsers don't guarantee that will start SW update immediately when they found it. `install` event of SW might be delayed up to **5 seconds** after your `onload` event of the page. Basically, best solution is to let the browser to perform updating in background and then ask or force a user to apply update.

Also you can probably display kind-of modal splashscreen on `onUpdating` event showing spinner and saying to users to "wait", but this generally a bad UX (no one wants to wait).

Does this help?

**Comment by jefbarn** [comment]
Thanks for the quick response.
Yeah, I was afraid of this.  I'm trying to make the UX of my app better by not forcing a refresh, but also would like to make sure the user is using the latest version.  Seemed logical to just wait for the latest version on page load, but it seems that Service Worker wasn't really designed this way.

**Comment by NekR** [comment]
> I think I can hack

Yeah, this is exactly what I meant by the hack. You can also just use `onUpdating` event from the offline-plugin's `runtime`.

> I'm trying to make the UX of my app better by not forcing a refresh, but also would like to make sure the user is using the latest version. 

This is actually a pretty common wish, my previous client also wanted this behavior. Probably it's a problem on the ServiceWorker's level.

Should we close this one then?

**Comment by jefbarn** [comment]
Yeah, my hack seems to be doing what I want.

In case anyone stumbles apon this in the future, here is the little plugin for webpack to emit the hash to a file.

`
class HashPlugin {
  apply(compiler) {
    compiler.plugin('emit', function(compilation, callback) {
      let hashfile = './dist/hash.txt'
      let hash = compilation.getStats().hash
      compilation.fileDependencies.push(hashfile)
      compilation.assets[path.basename(hashfile)] = {
        source: function () {
          return hash
        },
        size: function () {
          return hash.length
        }
      }
      callback()
    })
  }
}
`
