### ISSUE TITLE
To cache complete url

### ISSUE THREAD

**Issue by shishirarora3** [NekR/offline-plugin#98]
How to make cache to store response against complete url? Right now url.search is not included in cache key so same response is given on any search string.

Any option available, right now, to make this happen?

Any reason why search string is excluded?

Please advise.

**Comment by NekR** [comment]
Hi @shishirarora3, unfortunately there is no way to make this happen. The reason why that was made is to just easier cache things a easier handle problem with such urls `scripts.js?36`. But I see why you may need it. What is your exact use case here?

**Comment by shishirarora3** [comment]
I need to cache fetch/xhr get/post responses. If I keep querystring in key then at least get requests would work offline. Response differs for different query prams and I need to store all these in cache.

For scripts.js chunk caching, images etc things are working fine, only blocker is service resonses.

Please advise further.

**Comment by shishirarora3** [comment]
The use case is user searching for products and everytime it hits same url with different paarms and I wish to cache all responses.

**Comment by NekR** [comment]
> only blocker is service resonses.

Do you want put all your service responses into a cache when user visits your website or it's for dynamic caches? I hope it's for dynamic caches. 

`offline-plugin` doesn't have right caching for dynamic urls/routers, it only caches things what where built by webpack or explicitly specified in cache entries. If you need to cache dynamic routes then you need to do it manually, and there you will be able to cache it how you want: with search part or without.

**Comment by shishirarora3** [comment]
My use-case is all above scenarios. 

I needed prefetched webpack generated resources, dynamic service responses, any external links, dynamic routes. I mean all user activity chached offline+online for repeated requests. 

All these usecases are working fine with your plugin, except when url has query-string that it gets  ignored so I am getting first response everytime. So I will modify some part around including query-strings also in urls for cache keys. 

Will try and revert. 

Thanks

**Comment by NekR** [comment]
@shishirarora3 I understand that it's important and I'm not saying that I'm not going to implement. It's needed. As soon as I have time for -- I'll implement it.

**Comment by NekR** [comment]
This will be fixed in `v4`, probably in September.

**Comment by NekR** [comment]
Fixed in `v4`.
